### ISSUE TITLE
Initiator cannot rejoin session

### ISSUE THREAD

**Issue by fruiz500** [muaz-khan/RTCMultiConnection#10]
So far RTCMultiConnection is working great, but I find that if the initiator leaves a session where there are two other participants (I'm simulating this by running Firefox, Opera, and Chrome on the same machine. each with the same data session open), then he/she/it cannot return, and in fact nobody else can join the session.

But the other participants can leave and then return. Only the initiator has this restriction.

Is there a way around this? I'd like the initiator, who happened to be the first person checking in, to be able to leave and return like everyone else.

Thanks!

**Comment by snuggs** [comment]
Why is this still open? Needs closing @muaz-khan
