### ISSUE TITLE
onstream event on firefox

### ISSUE THREAD

**Issue by amallecourt** [muaz-khan/RTCMultiConnection#100]
Hi Muaz Kahn,
I am using your RTCMultiConnection to implement a video+audio+data broadcast. It's working fine on google chrome but I have an issue when I want to use it one firefox : the "onstream" event is not fired when someone is joining the room (so I am not able to add the media element at this moment..). Do you have an idea of what could happen?
Thanks in advance for your help

**Comment by muaz-khan** [comment]
You should try this:

```javascript
connection.enableFileSharing = false; // optional
connection.session = {
    audio: true,
    video: true,
    data: true,
    broadcast: true // DO NOT use "oneway:true"
};
```

Also please make sure that you are NOT trying to capture single camera simultaneously both form Chrome and Firefox.

```javascript
connection.onMediaError = function() {
    alert(JSON.stringify(arguments, null, '\t'));
};
```

**Comment by amallecourt** [comment]
This new configuration is not working.
And I have a problem with it because it ask the person who is joining the room to also share his video. Only the initiator should share his video. Which is not happening when I use "oneway: true". So I should keep using "oneway" and not using "broadcast". 
I am using the 3.2.89 version of your rtcmulticonnection-v3 library. It's maybe something you improve in newer version ?

**Comment by amallecourt** [comment]
I updated the rtcmulticonnection-v3 library to the newest version (3.2.98).
But the problem is persistent. I should maybe precise you the configuration I use :

From the broadcaster side : 
`	$scope.connection = new RTCMultiConnection();
	$scope.connection.session = {
    	audio: true,
    	video: true,
    	data: true,
    	broadcast: true
	};

	$scope.connection.sdpConstraints.mandatory = {
	    OfferToReceiveAudio: false,
	    OfferToReceiveVideo: false
	};

	$scope.connection.enableScalableBroadcast = true;
	$scope.connection.enableFileSharing = false;
`

From the listener side :
`	$scope.connection = new RTCMultiConnection();
	$scope.connection.session = {
	    audio: false,
	    video: false,
	    data: true,
	    oneway: true
	};

	$scope.connection.sdpConstraints.mandatory = {
    	OfferToReceiveAudio: true,
    	OfferToReceiveVideo: true
	};

	$scope.connection.enableScalableBroadcast = true;
	$scope.connection.enableFileSharing = false;
	$scope.connection.dontCaptureUserMedia = true;
	$scope.connection.autoReDialOnFailure = true; `

Do you have another idea why this is only working on Google Chrome ?

**Comment by muaz-khan** [comment]
Please try this:

```javascript
$scope.broadcaster = new RTCMultiConnection();

$scope.broadcaster.session = {
    audio: true,
    video: true,
    data: true,
    oneway: true
};

$scope.broadcaster.sdpConstraints.mandatory = {
    OfferToReceiveAudio: false,
    OfferToReceiveVideo: false
};

$scope.broadcaster.enableScalableBroadcast = false;
```

1. Use `oneway:true` instead of `broadcast:true`.
2. Set `enableScalableBroadcast=false`

#### If you're planning one-to-many broadcast rather than oneway streaming, then:

1.Set  `OfferToReceiveAudio==true` and `OfferToReceiveVideo==true` (you are using wrong values)
2. Set `enableScalableBroadcast=false`
3. Set `broadcast:true` (as you are already doing)

`enableScalableBroadcast` MUST be false in all situations.

`OfferToReceive Audio/Video` MUST be true so that broadcaster can also receive videos.

**Comment by amallecourt** [comment]
It's still not working on firefox.

**Comment by amallecourt** [comment]
Updated rtcm to the last version.
The event is now triggered on firefox.

**Comment by jtpdev** [comment]
I'm using the latest version of rtcmulticonnection, using a many-to-many connection with *vue* and when someone join to the room, the event *onNewParticipant* is triggered, but *onstream* not.
