### ISSUE TITLE
need help! turn/stun in android can't work 

### ISSUE THREAD

**Issue by vcluo** [muaz-khan/RTCMultiConnection#1012]
thank you code ,a'lot help me . 
before i read the issues need the turn server help the mobile connect in internet

now i set turn server and use the google stun server 
phone use mobilenetwork  still can't connect the pc create room .

this is my iceserver config :
connection.iceServers = [];
connection.iceServers.push({
    urls:[       
        'stun:stun.l.google.com:19302',
        'stun:stun1.l.google.com:19302',
        'stun:stun2.l.google.com:19302',
        'stun:stun.l.google.com:19302'
        ]  
});
connection.iceServers.push({
    urls: 'turn:103.210.236.58:3478',
    credential: 'xxxx',
    username: 'xxxx'
});

**Comment by vcluo** [comment]
![image](https://user-images.githubusercontent.com/22213918/116373063-99b34200-a83f-11eb-9626-6d8167953403.png)
well look like credential is error

**Comment by vcluo** [comment]
how i config the credential  in the turn  or  in code?

**Comment by vcluo** [comment]
i change my turn username right, but phone use the 4g network can't remote the stream to else user

**Comment by flayds** [comment]
Dear, in Turn try this code

connection.iceServers = [{
        'urls': [
		    'turn:mytturnurl:3478?transport=udp',
            'turn:mytturnurl:3478?transport=tcp', 
            'turn:.mytturnurl:443?transport=tcp',
        ],
		'username': 'username',
         'credential': 'password'
    },
];

**Comment by vcluo** [comment]
> 亲爱的，请依次尝试以下代码
> 
> connection.iceServers = [{
> 'urls :: [
> 'turn：mytturnurl：3478？transport = udp'，
> 'turn：mytturnurl：3478？transport = tcp'，
> 'turn：.mytturnurl：443？transport = tcp'，
> ]，
> 'username'：'username'，
> 'credential'：'password'
> }，
> ];

thanks it's seem look like this code need config turn server port open the 443

**Comment by vcluo** [comment]
> Dear, in Turn try this code
> 
> connection.iceServers = [{
> 'urls': [
> 'turn:mytturnurl:3478?transport=udp',
> 'turn:mytturnurl:3478?transport=tcp',
> 'turn:.mytturnurl:443?transport=tcp',
> ],
> 'username': 'username',
> 'credential': 'password'
> },
> ];

![image](https://user-images.githubusercontent.com/22213918/116497729-9faa3100-a8da-11eb-91bb-f7fcc9af86ff.png)

![image](https://user-images.githubusercontent.com/22213918/116497849-e0a24580-a8da-11eb-8912-0f6d3d1a1ede.png)

sorry i try this use turn 443 port but still can't work

**Comment by flayds** [comment]
> > Dear, in Turn try this code
> > connection.iceServers = [{
> > 'urls': [
> > 'turn:mytturnurl:3478?transport=udp',
> > 'turn:mytturnurl:3478?transport=tcp',
> > 'turn:.mytturnurl:443?transport=tcp',
> > ],
> > 'username': 'username',
> > 'credential': 'password'
> > },
> > ];
> 
> ![image](https://user-images.githubusercontent.com/22213918/116497729-9faa3100-a8da-11eb-91bb-f7fcc9af86ff.png)
> 
> ![image](https://user-images.githubusercontent.com/22213918/116497849-e0a24580-a8da-11eb-8912-0f6d3d1a1ede.png)
> 
> sorry i try this use turn 443 port but still can't work

Hi,

In your code, put the only URL turn server and port.

> > 'urls': [
> > 'turn:myturnurl',
> > ],

**Comment by flayds** [comment]
connection.iceServers = [{
'urls': [
'turn:103.210.236.58:3478',
],
'username': 'username',
'credential': 'password'
},
];

**Comment by vcluo** [comment]
> connection.iceServers = [{
> 'urls'：[
> 'turn：103.210.236.58：3478'，
> ]，
> 'username'：'username'，
> 'credential'：'password'
> }，
> ];

sadly of this ,when i use the sirsys turn server let phone use 4gnetwork connect this webrtc, but when i use the turn server of me 
still can't work it
