### ISSUE TITLE
Website Unreachable

### ISSUE THREAD

**Issue by careprod** [muaz-khan/RTCMultiConnection#1021]
Hello dear community,

Hope I can find some help there. I'm actually working on a solution for internal tchat and this project seems to perfectly suits.
I did some research and worked a lot about my solution, but I'm actually facing a problem.

In fact, I did host my app on AWS Amplify and works fine (have interactions, tchat, share files, etc... while i used it on localhost and when I hosted the node server of @muaz-khan on heroku). But now I wanna have my server on AWS EC2, so I followed instructions (create a ec2 instances, create elastic ip for the instance, buy a domain name and clone my server on the ubuntu virtual machine , create certificates..) But when it arrives at the certificates, I have many problems.

Currently i'm lauching my node server correctly but I have problem with SSL and I'm not really attracted by network and stuff like that... I keep getting this error : ERR_SSL_VERSION_OR_CIPHER_MISMATCH

I did some research but... I'm not you know.. the type of guy that is really the job, so i'll be glad if I can find some help

I'm also dropping you my server code in order to have some review if I also did something wrong

Best Regards,

Sam
![Capture d’écran 2021-07-16 à 17 00 29](https://user-images.githubusercontent.com/82519761/125971401-32491789-394d-4e4e-a804-e827b186ddd8.png)
![Capture d’écran 2021-07-16 à 17 00 46](https://user-images.githubusercontent.com/82519761/125971407-84a065f0-6d6d-49c8-9b3c-9a17bc59e061.png)
![Capture d’écran 2021-07-16 à 17 01 07](https://user-images.githubusercontent.com/82519761/125971412-00d29c8e-5cf0-47b2-a479-1d290fe9315e.png)
![Capture d’écran 2021-07-16 à 17 01 35](https://user-images.githubusercontent.com/82519761/125971415-b4cab33f-4791-4fe4-9858-2da6a1f00e0a.png)
![Capture d’écran 2021-07-16 à 17 01 58](https://user-images.githubusercontent.com/82519761/125971416-38c4e796-ae44-4e79-8437-2a9212ad2308.png)
![Capture d’écran 2021-07-16 à 17 02 12](https://user-images.githubusercontent.com/82519761/125971419-316f0a52-f566-4bf4-8d13-116afab4b3fa.png)
![Capture d’écran 2021-07-16 à 17 02 20](https://user-images.githubusercontent.com/82519761/125971422-fc4057f3-a45a-4818-a50c-326ab72644d3.png)
![Capture d’écran 2021-07-16 à 17 02 31](https://user-images.githubusercontent.com/82519761/125971425-f44ed9fa-862a-445a-913b-385617fc9d3b.png)

**Comment by vcluo** [comment]
hello ,but can't help you, maybe describle more detaile problem , or just show the broswer console error cut screen show our analyse

**Comment by careprod** [comment]
thx for responding @vcluo but now the back end developer working with me that recently join our team manage to host it on azure so everything is ok. 

I thank you a lot ,

Kind Regards , Sam
