### ISSUE TITLE
TURN server does not work 

### ISSUE THREAD

**Issue by CompoTeam** [muaz-khan/RTCMultiConnection#1028]
Hi, I try to use the turn server but it doesn't work and I cant connect two-node from different nat types.
here is my code :
```
`<script src="https://rtcmulticonnection.herokuapp.com/dist/RTCMultiConnection.min.js"></script>
<script src="https://rtcmulticonnection.herokuapp.com/socket.io/socket.io.js"></script>

<script>
var connection = new RTCMultiConnection();

// this line is VERY_important
connection.socketURL = 'https://rtcmulticonnection.herokuapp.com:443/';

// if you want audio+video conferencing
connection.session = {
    audio: true,
    video: true
};

// first step, ignore default STUN+TURN servers
connection.iceServers = [];
connection.trickleIce = false;

// as soon as RTCMultiConnection calls "peer.setLocalDescription"
connection.onSettingLocalDescription = function(peer) {
    var sdp = peer.localDescription.sdp; // get the SDP

            connection.renegotiate(peer.userid);

};
// second step, set STUN url
connection.iceServers.push({
    urls: 'iphone-stun.strato-iphone.de:3478'
});

// last step, set TURN url (recommended)
connection.iceServers.push({
    urls: 'turn:numb.viagenie.ca',
    credential: 'muazkh',
    username: 'webrtc@live.com'
});
connection.candidates = {
    turn: true
};
connection.iceTransportPolicy = 'relay';
connection.openOrJoin('this-is-your-room-id');
</script>`
```
i need help!
 very much!
@muaz-khan

**Comment by CompoTeam** [comment]
Turn server was out of date I used some working one and it worked
if anybody needed any help in the config of coturn just leave a comment.

**Comment by ROBERT-MCDOWELL** [comment]
yes please the config can be helpful thanks

**Comment by webleb** [comment]
> Turn server was out of date I used some working one and it worked if anybody needed any help in the config of coturn just leave a comment.

@CompoTeam 
please i need help in coturn configuration.

**Comment by CompoTeam** [comment]
> 

tls-listening-port=5349
cli-password=amir
# provide the public IP for your EC2
listening-ip=your server public ip
external-ip= your server public ip
# ports
min-port=49152
max-port=65535
realm=default realm
# enable verbose logging
verbose

# use fingerprint in Turn message
#fingerprint

# enable a log-term credential mechanism
lt-cred-mech

# server name 
#server-name=turnserver
listening-port=3754


# provide username and password
user=user:pass

# log file path
log-file=/var/tmp/turn.log

**Comment by CompoTeam** [comment]
> > Turn server was out of date I used some working one and it worked if anybody needed any help in the config of coturn just leave a comment.
> 
> @CompoTeam please i need help in coturn configuration.
try the raw config github markdown changed it a little bit
http://regprime.com/PermanentLink?Display#tls-listening-port%3D5349%0Acli-password%3Damir%0A%23%20provide%20the%20public%20IP%20for%20your%20EC2%0Alistening-ip%3Dyour%20server%20public%20ip%0Aexternal-ip%3D%20your%20server%20public%20ip%0A%23%20ports%0Amin-port%3D49152%0Amax-port%3D65535%0Arealm%3Ddefault%20realm%0A%23%20enable%20verbose%20logging%0Averbose%0A%0A%23%20use%20fingerprint%20in%20Turn%20message%0A%23fingerprint%0A%0A%23%20enable%20a%20log-term%20credential%20mechanism%0Alt-cred-mech%0A%0A%23%20server%20name%20%0A%23server-name%3Dturnserver%0Alistening-port%3D3754%0A%0A%0A%23%20provide%20username%20and%20password%0Auser%3Duser%3Apass%0A%0A%23%20log%20file%20path%0Alog-file%3D%2Fvar%2Ftmp%2Fturn.log
