### ISSUE TITLE
muazkhan.com:9001 is down

### ISSUE THREAD

**Issue by tobiasBora** [muaz-khan/RTCMultiConnection#1035]
Since March, the Heroku app has been moved to https://muazkhan.com:9001/ , unfortunately this server is down… Would it be possible to fix this? Also, is there some famous socketIo server that I could use that is more stable than https://muazkhan.com:9001/? Maybe some servers provided by Google or others.

**Comment by muaz-khan** [comment]
I think the server (https://muazkhan.com:9001/demos/) is up and running.

**Comment by tobiasBora** [comment]
I can't open this page (tried on both my phone with 4G and on my computer with the lab wifi). However I can access https://muazkhan.com/

**Comment by tobiasBora** [comment]
Now it seems to work. Thanks!
