### ISSUE TITLE
SSL certificate has expired. Please help.

### ISSUE THREAD

**Issue by mkocieda** [muaz-khan/RTCMultiConnection#1052]
SSL certificate has expired. Please help. https://muazkhan.com:9001/ - not work

**Comment by LucasCVentura** [comment]
Hi, how you solved this problem? I think im having the same issue.

**Comment by Romuloom** [comment]
Hi, did you manage to solve this problem?

**Comment by mkocieda** [comment]
Hi. He fix this, It's ok right now.
