### ISSUE TITLE
video appearing issue

### ISSUE THREAD

**Issue by khurram753** [muaz-khan/RTCMultiConnection#1059]
when I open stream or do live video chat the video that is rending in that mirroring is happening. can anyone help me with this?

**Comment by MediaKitApp** [comment]
Hello!

Can you send me a screenshot?

**Comment by khurram753** [comment]
> Hello!
> 
> Can you send me a screenshot?

means if I look on right side then on the screen i am looking on the left side

**Comment by MediaKitApp** [comment]
Thus, you only have to rotate the video with CSS, with that it will be enough to accommodate the local videos.

**Comment by MediaKitApp** [comment]
Example:
```css
video.local{ 
    transform: scaleX(-1);
}
```

**Comment by khurram753** [comment]
> Example:
> 
> ```css
> video.local{ 
>     transform: scaleX(-1);
> }
> ```

i will check this and let you know

**Comment by khurram753** [comment]
> Example:
> 
> ```css
> video.local{ 
>     transform: scaleX(-1);
> }
> ```

it works like a charm thanks for your help

**Comment by MediaKitApp** [comment]
No problem, I wish you luck!
