### ISSUE TITLE
How to change resolution when Broadcasting??

### ISSUE THREAD

**Issue by NguyenTungs** [muaz-khan/RTCMultiConnection#106]
Users can convert the video quality when a slow network access when it is live.
Please help me!!!

**Comment by muaz-khan** [comment]
Firefox supports [`applyConstraints ` API](https://github.com/muaz-khan/RTCMultiConnection#applyconstraints):

```javascript
var width = 1280;
var height = 720;

var supports = navigator.mediaDevices.getSupportedConstraints();

var constraints = {};
if (supports.width && supports.height) {
    constraints = {
        width: width,
        height: height
    };
}

connection.applyConstraints({
    video: constraints
});
```

Chrome, on the other hand, requires renegotiation:

```javascript
connection.getAllParticipants().forEach(function(uid) {
    var user = connection.peers[uid];

    user.peer.getLocalStreams().forEach(function(localStream) {
        user.peer.removeStream(localStream);
    });
});

connection.attacchStreams = [];

// or:
// connection.attachStreams.forEach(function(stream) { stream.stop(); });

connection.mediaConstraints = {
    audio: true,
    video: {
        mandatory: {
            maxWidth: 1920,
            maxHeight: 1080
        },
        optional: []
    }
};

connection.addStream({
    audio: true,
    video: true,
    oneway: true
});
```

**Comment by NguyenTungs** [comment]
Thank you!!!

**Comment by NguyenTungs** [comment]
Currently at version 2.2, then there is no applyConstraints function. So how to update it. Many thanks.

**Comment by muaz-khan** [comment]
For v2.2.2:

```javascript
function applyConstraints(stream) {
    var width = 1280;
    var height = 720;

    var supports = navigator.mediaDevices.getSupportedConstraints();

    var constraints = {};
    if (supports.width && supports.height) {
        constraints = {
            width: width,
            height: height
        };
    }

    stream.getVideoTracks().forEach(function(track) {
        track.applyConstraints(constraints);
    });
}

applyConstraints(connection.attachStreams[0]);
```

**Comment by NguyenTungs** [comment]
Thanks! I am most grateful! 
But can you explain to me this:
When the Open Room, you can change the resolution but Join Room then don't change it. Here I want the clients can change the resolution ... Is there any way to help me.

**Comment by NguyenTungs** [comment]
Code here!!

`<pre>
connection.applyConstraints({
                            video: constraints
                        },_obj_live.streamid);
</pre>`

**Comment by NguyenTungs** [comment]
Hi Muaz-Khan!! When I change resolution client side then get the message:
OverconstrainedError: Constraints could be not satisfied.

**Comment by mistris** [comment]
@muaz-khan Can you please provide an example how to change video resolution in v3 for Chrome and Firefox?

**Comment by muaz-khan** [comment]
Added new demo:

| DemoTitle        | TestLive           | ViewSource |
| ------------- |-------------|-------------|
| Change Video Resolutions in your Live Sessions | [Demo](https://rtcmulticonnection.herokuapp.com/demos/change-resolutions.html) | [Source](https://github.com/muaz-khan/RTCMultiConnection/tree/master/demos/change-resolutions.html) |

**Comment by NguyenTungs** [comment]
Thanks!!  But :
On FireFox tested: 
A broadcasting to B.. When B change resolution then A also change resolution...
P/s : Here I want to when B changes the resolution, only B changes, then The A keep the resolution 
**@muaz-khan** Can you please provide an example case this.

On Chrome : Change incorrect... . Tested on Version 49.0.2623.110 (64-bit). MacOS

**Comment by NguyenTungs** [comment]
@muaz-khan : Please help me!
