### ISSUE TITLE
Change video resolution on v3

### ISSUE THREAD

**Issue by mistris** [muaz-khan/RTCMultiConnection#110]
@muaz-khan Can you please provide an example how to change video resolution in v3 for Chrome and Firefox?

**Comment by muaz-khan** [comment]
You can try this demo using Firefox:

* https://rtcmulticonnection.herokuapp.com/demos/applyConstraints.html

**Comment by mistris** [comment]
Is there a demo for Chrome?

**Comment by mistris** [comment]
Thank you very much for you work! :+1:
