### ISSUE TITLE
connection.onstream + angularjs

### ISSUE THREAD

**Issue by mistris** [muaz-khan/RTCMultiConnection#111]
@muaz-khan I noticed that if the whole page is refreshed then `connection.onstream` is called but if you open the video page using angular link (change state) then `connection.onstream` is not called and HTML5 video element doesn't have `src` attribute. So without full page refresh video is not showing.
Any help would be appreciated.

**Comment by muaz-khan** [comment]
Seems socket.io issues. Maybe you should disconnect socket before starting/joining rooms e.g. `connection.disconnectSocket()`

**Comment by mistris** [comment]
I tried `connection.closeSocket()` after leaving room and before joining room. Still no luck.
It still skips `connection.connectSocket(function (socket) {...` part of code.

**Comment by mistris** [comment]
Thank you very much! :+1:
