### ISSUE TITLE
addStream not working on Demo (https://rtcmulticonnection.herokuapp.com/demos/addStream-in-Chat-room.html)

### ISSUE THREAD

**Issue by NguyenTungs** [muaz-khan/RTCMultiConnection#114]
Error : 
NotSupportedError: removeStream not yet implemented
connection.peers[p].peer.removeStream(stream);

How to fix it!!! Thank You!

**Comment by naturelgass** [comment]
the removeStream is not yet supported in firefox,
you can overcome this issue by wrapping all this to:
`if(DetectRTC.browser.name != "Firefox"){
connection.peers[p].peer.removeStream(stream);
}
`

you will have to also to add at the top `<script src="https://cdn.webrtc-experiment.com/DetectRTC.js"> </script>`

**Comment by NguyenTungs** [comment]
Yeah! Thanks! But The project run on FireFox, so How to fix!!! 
Thank you very much!
