### ISSUE TITLE
addStream in a Chat Room demo disconnects room after both parties remove Media

### ISSUE THREAD

**Issue by webchillie** [muaz-khan/RTCMultiConnection#119]
Hi, first of all, thanks for the great code you have written. And the great documentation. It's has been a great help. 

[https://rtcmulticonnection.herokuapp.com/demos/addStream-in-Chat-room.html](https://rtcmulticonnection.herokuapp.com/demos/addStream-in-Chat-room.html)

On the demo, when you create a new room and join the same room with another browser, it is possible to chat, add a stream and remove the stream. But after the 2nd browser removed the stream, the chat is not working anymore. And it is (most of the times) not possible to add the new webcam streams, so you have 2 camera's again. So it only works good the first time. 

It would be great if the room stayed open, so the chat keeps working and both users could enable the stream/camera again. So it would be possible to stay with a couple people in a room. Take a break, close the camera and after a couple of minutes start the camera again, without creating a new room. And keeping the chat on, so you can let the others know, you are ready to continue. 

I don't know if this is an issue or a new functionality, but it would be great if the "remove stream" would only remove the stream, but keep the room open. 

Keep up the good work! :+1:

**Comment by webchillie** [comment]
I found the solution to keep the chat working after the Stream was stopped. 

The solution is not to empty the **connection.attachStreams**

you can find it in this part of the demo source code: 

```
document.getElementById('btn-removeStream').onclick = function() {
                this.disabled = true;
                if(connection.attachStreams.length) {
                    connection.getAllParticipants().forEach(function(p) {
                        connection.attachStreams.forEach(function(stream) {
                            connection.peers[p].peer.removeStream(stream);
                        });
                    });
                    
                    connection.attachStreams.forEach(function(stream) {
                        stream.stop();
                    });
                    connection.attachStreams = [];  //Remove this line to keep the chat connection open.
                }
                connection.renegotiate();
                document.getElementById('btn-addStream').disabled = false;
            };
```

Can you confirm this is the appropriate way to do this?

**Comment by muaz-khan** [comment]
Here is the renegotiation logic in Chrome:

1. Call `peer.removeStream`
2. Call `peer.addStream`
3. Renegotiate
4. Stop old stream after when above renegotiation completes

In our case, we are [mistakenly using](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/addStream-in-Chat-room.html#L242-L244) `stream.stop` too early.

Personally I prefer addition or removal of streams MUST be happened by this code:

```javascript
connection.peers['userid'].peer.removeStream(oldStream);
connection.peers['userid'].peer.addStream(newStream);
connection.renegotiate('userid' || null);
```

Because we are calling native `addStream/removeStream` methods, we don't need `connection.attachStreams` array. So that array MUST be empty.

```javascript
connection.peers['userid'].peer.removeStream(oldStream);
connection.peers['userid'].peer.addStream(newStream);

connection.attachStreams = []; // must be empty, we don't need this
connection.renegotiate('userid' || null);

// stop old stream here
setTimeout(function() {
   oldStream.stop();
}, 5000);
```

Or a most preferred solution for `removeStream`:

```javascript
connection.peers['userid'].peer.getLocalStreams().forEach(function(localStream) {
    connection.peers['userid'].peer.removeStream(localStream);
});

connection.peers['userid'].peer.addStream(newStream);

connection.attachStreams = []; // must be empty, we don't need this
connection.renegotiate('userid' || null);

// stop old stream here
setTimeout(function() {
   oldStream.stop();
}, 5000);
```

For `userid` we can use `getAllParticipants` method:

```javascript
connection.getAllParticipants(function(userid) {
    var peer = connection.peers[userid].peer;
    peer.getLocalStreams().forEach(function_callback);
    peer.addStream(newStream);
});
connection.attachStreams = [];
connection.renegotiate(); // with all users

// stop old stream here
setTimeout(function() {
   oldStream.stop();
}, 5000);
```

**Comment by webchillie** [comment]
Thanks for the explanation, it would be great if the demo could be updated with this code, so I can play with it. Thanks in advance for all the trouble. It's really appreciated :+1:

**Comment by webchillie** [comment]
Dear Kahn, 

I believe some of the code in your reply, is not for the 3.0 version. Because for example: 
`connection.peers['userid'].peer.removeStream(oldStream); `and 
`connection.peers[userid].peer;` is not possible anymore. IMMO
 And the **oldStream ** object only exists in the first example. 

I solved it this way. Maybe it helps somebody.

```
      //Close the screen and connection.
      if(connection.attachStreams.length) {
          connection.getAllParticipants().forEach(function(p) {
              connection.attachStreams.forEach(function(stream) {
                  connection.peers[p].peer.removeStream(stream);
                  // stop old stream here
                  setTimeout(function() {
                     stream.stop();
                  }, 5000);
              });
          });

        instance.connection.attachStreams = [];

        connection.renegotiate(remoteUserId || null);
```

My last issue is when I want to add the stream again, just like the first time, with the same code. Only the local video gets shown on both the browsers. So my code works fine when the Room is opened and joined. I have 2 video's without any problem. Then I close the video's with this code. Then I want to start the videos again, but get only the local video. When i close the room and start over with Open and Join, it works again. .....

**Comment by NguyenTungs** [comment]
@webchillie @muaz-khan: How to removeStream On FireFox... Please help me!

**Comment by webchillie** [comment]
I am not working with this software anymore, closed it, so it will not be in my issue list anymore. If somebody still has the same problem, it can be opened again on request.
