### ISSUE TITLE
Share Screen in Chrome!!! NavigatorUserMediaError

### ISSUE THREAD

**Issue by BanhBao2911** [muaz-khan/RTCMultiConnection#123]
Chrome: I tried the Demo (https://rtcmulticonnection.herokuapp.com/demos/Audio+ScreenSharing.html), it worked. But when running on my web error
NavigatorUserMediaError: constraintName: ""message: ""name: "InvalidStateError"...
Is there a way fix? Please help me!

**Comment by kashifsulaiman** [comment]
@HuongPhams how did you fix this?
