### ISSUE TITLE
Exception in Firefox Mobile for Android

### ISSUE THREAD

**Issue by dnish** [muaz-khan/RTCMultiConnection#128]
I'm getting this in FF Mobile on Android:

    Exception in setTimeout callback:     RTCMultiConnection@http://192.168.178.28:3000/packages/package_rtcmulti.js?0a8498f5fb8302f3469106328fe5955a8127d00c:1472:1

Error is thrown while creating a new RTCMultiConnection object:

    RTCConnection =  new RTCMultiConnection();

**Comment by dnish** [comment]
This is what I get if I init the object via browser console:

    var bla = new RTCMultiConnection();
    TypeError: connection.mediaConstraints.audio.optional is undefined

**Comment by dnish** [comment]
I've fixed it temporary by adding try catch to the parts in your code. After connecting from Chrome Desktop to Firefox mobile, I only get a black screen without any stream.

**Comment by muaz-khan** [comment]
Maybe you should try:

```javascript
if(navigator.connection 
     && navigator.connection.type 
     && navigator.connection.type.toString().toLowerCase().search(/wifi|cell/g) !== -1) {
   navigator.connection.type = 'DSL';
}

var connection = new RTCMultiConnection({
    useDefaultDevices: true
});
```

PS. This issue will be fixed in the next commit.

**Comment by dnish** [comment]
@muaz-khan Nope, this isn't working, I still get none stream if I connect <code>Mobile Firefox -> Mac Chrome</code>

**Comment by muaz-khan** [comment]
I just tested following demo:

* https://rtcmulticonnection.herokuapp.com/demos/Video-Conferencing.html

It worked between `MacChrome<>AndroidFirefox` in all scenarios.

**Comment by dnish** [comment]
Yeah you are right, the demo also work's on my devices. I'll check my code.

**Comment by dnish** [comment]
Mhh...the only difference I see is that I connect to a user via

    RTCConnection.connect(fUser.peerkey)

while your demo is using join/open/openOrJoin. Could any differences in this methods explain the behavior of <code>Mac Chrome -> Firefox? </code>

**Comment by dnish** [comment]
Works fine after upgrading to newst version, thank you very much :)
