### ISSUE TITLE
Switch+Cameras using RTCMultiConnection-v3.0

### ISSUE THREAD

**Issue by Nitrick** [muaz-khan/RTCMultiConnection#130]
You have given this demo for switching many camera and show to live connection but in this the connection is not established for further time and I have used RTCMultiConnection older version and it let me connect for first time but not letting me to change the camera for live conference.

pl. help me to solve this problem.
![issue2](https://cloud.githubusercontent.com/assets/17708478/14580718/6137dbf6-03f4-11e6-8c5a-d5fcc48b4762.png)
![issue1](https://cloud.githubusercontent.com/assets/17708478/14580719/613cf2ee-03f4-11e6-9d12-97312121f752.png)

**Comment by dnish** [comment]
I'm handling camera switching atm with this code:
```
switchCamera() {

 RTCConnection.stopMediaAccess();

 setTimeout(() => {
   RTCConnection.mediaConstraints.video.optional = [{
                    sourceId: usedCamera //set here the new camera
                }];

  RTCConnection.addStream({audio: true, video: true});

  },2000);

}
```

Works good in <code>Chrome<->Chrome</code> but I have some issues with Firefox Android and Chrome Mac, if I change the camera on Firefox, it doesn't send the new stream to the Chrome user.

**Comment by Nitrick** [comment]
Hi Dnish,

thanks for Your answer but it will good for me if u will give me some demo regarding this answer

**Comment by Nitrick** [comment]
First screen shot: this about how the application start with the count of devices available on your computer.

Second screen shot: This screen shows how the connection is been established and how first time the other user's page is checking the session is available or not and if it get the session then it is connected to the owner of the room and then video calling starts.

Third screen shot: This screen shows us that when we use other devise to connect to the existing room then it is no able to connect to it or the another user's page is not getting another broadcast of the video screen, So what we want is that if the other user's page get update but the existing connection should not be effected.
![videocallingsnap1](https://cloud.githubusercontent.com/assets/17708478/14672325/bcf7a39a-0714-11e6-8239-1de5987e8c93.png)
![videocallingsnap2](https://cloud.githubusercontent.com/assets/17708478/14672326/bcf8808a-0714-11e6-9f1e-920e6e763e2f.png)
![videocallingsnap3](https://cloud.githubusercontent.com/assets/17708478/14672327/bcfb8f82-0714-11e6-808c-ebbeaad6dd11.png)

**Comment by Nitrick** [comment]
I have solved the issue Thanks

**Comment by karthivcet11** [comment]
> You have given this demo for switching many camera and show to live connection but in this the connection is not established for further time and I have used RTCMultiConnection older version and it let me connect for first time but not letting me to change the camera for live conference.
> 
> pl. help me to solve this problem.
> ![issue2](https://cloud.githubusercontent.com/assets/17708478/14580718/6137dbf6-03f4-11e6-8c5a-d5fcc48b4762.png)
> ![issue1](https://cloud.githubusercontent.com/assets/17708478/14580719/613cf2ee-03f4-11e6-9d12-97312121f752.png)

Nitrick-- i am struggle to implement switch camera can you help me

**Comment by karthivcet11** [comment]
Nitrick -- if you give code best for me
