### ISSUE TITLE
How to change Bandwidth on RTCMultiConnectionv.3

### ISSUE THREAD

**Issue by NguyenTungs** [muaz-khan/RTCMultiConnection#138]
In v.2.2.2 It work : https://www.webrtc-experiment.com/RTCMultiConnection/bandwidth.html?audio=30&video=30...
@muaz-khan : Can you please provide an example how to change video Bandwidth in v3 for Chrome and Firefox?
Thank a lot!!

**Comment by muaz-khan** [comment]
You can try this demo:

* https://rtcmulticonnection.herokuapp.com/demos/change-resolutions.html

Add following code at line [163](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/change-resolutions.html#L163):

```javascript
connection.bandwidth = {
   audio: 192, // kbps
   video: 512, // kbps
   screen: 1024 // kbps
};
```

**Comment by NguyenTungs** [comment]
Thanks @muaz-khan !!
I've checked the examples that you provided. But it is not true in my case.
My case!
When A open broadcast, after B join in broadcast, C too.
The problem here. 
I want B can change bandwidth:
<pre>
connection.bandwidth = {
   audio: 192, // kbps
   video: 256, // kbps
   screen: 1024 // kbps
};
</pre>

C can change bandwidth:
<pre>
connection.bandwidth = {
   audio: 192, // kbps
   video: 1024, // kbps
   screen: 1024 // kbps
};
</pre>

I find it difficult in this matter. Please leave little time to provide me the above case.
Please help me!!! Thanks @muaz-khan .

**Comment by NguyenTungs** [comment]
Thanks @muaz-khan !
So is there any solution for the problem auto quality in the customer?
Can you give me specific examples or suggestions.
Thank a lot!

**Comment by NguyenTungs** [comment]
Hi @muaz-khan !
I've checked the example that you provided. 
**(In BroadCast)** If the client wants to change resolution the video when the network is slow.
I find it 's difficult in this matter. Please spend little time to provide(help) me the above case.

Thanks!

**Comment by NguyenTungs** [comment]
@muaz-khan : Please help me!

**Comment by nrlchsn** [comment]
@muaz-khan can you help us ? my problem is same with him :D hehehehe
