### ISSUE TITLE
Behind two NATs : Peer connection is closed between you &  700 Object {} state: failed

### ISSUE THREAD

**Issue by adrianobrancher** [muaz-khan/RTCMultiConnection#141]
Hello Mr,  congratulations from Brazil.

Thank you for this wonderful work..

but let's go..

I setup a brand new UBUNTU 14.04 64bits with NPMv3 + NODEJS 5.0 everything runs fine with these 2 guys.
I installed rtcmulticonnection v3 through npm3 and everything installed ok.

I execute the server, "node server.js" with fake certs and show me the 9001 port to access https demos. no problems too.

so,  i tried to execute: Audio+Video+TextChat+FileSharing.html (demo)  and the following situations happened.. i tested with chrome last update, in both sides, and with firefox last update too in both side.

Situations:

1) The demo, with both chromes or firefox in public IPs, runs fine.
2) The demo, with one chrome in public ip and other behind NAT, runs fine.
3) The demo, with both chromes or firefox behind NATs, rise a error and the peer image do not appear.

rmc3.js:1409 Peer connection is closed between you &  888 Object {} state: failedRTCMultiConnection.connection.onPeerStateChanged @ rmc3.js:1409MultiPeers.onPeerStateChanged @ rmc3.js:2275onPeerStateChanged @ rmc3.js:1958PeerInitiator.peer.oniceconnectionstatechange.peer.onsignalingstatechange @ rmc3.js:3741
undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

So, i attached the complete session to understand better the problem.

If you can, please check if it is a bug or something like that.

[app.digital-farm.com.br-1461436167744.txt](https://github.com/muaz-khan/RTCMultiConnection/files/234877/app.digital-farm.com.br-1461436167744.txt)
[app.digital-farm.com.br-1461438055276.txt](https://github.com/muaz-khan/RTCMultiConnection/files/234878/app.digital-farm.com.br-1461438055276.txt)

**Comment by adrianobrancher** [comment]
Friend, i tried with your full demo Audio+Video+TextChat+FileSharing.html ( using yours servers ) just pointing the URL to your servers and appear the same bellow error.

RTCMultiConnection.js:1409 Peer connection is closed between you &  abcdef Object {} state: failedRTCMultiConnection.connection.onPeerStateChanged @ RTCMultiConnection.js:1409MultiPeers.onPeerStateChanged @ RTCMultiConnection.js:2275onPeerStateChanged @ RTCMultiConnection.js:1958PeerInitiator.peer.oniceconnectionstatechange.peer.onsignalingstatechange @ RTCMultiConnection.js:3741
undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

I will do more tests, but in fact there are some problem with ICE Candidates and the hand shake maybe.

Big hugg, i appreciate  your guidance.

**Comment by adrianobrancher** [comment]
external servers (cross-domains)  raise the same condition, i tried this script and do not run, behind 2 nats,  https://jsfiddle.net/zd9Lsdfk/

So, i need your help to solve this. thank you Mr.

**Comment by adrianobrancher** [comment]
I make a brand new STUN / TURN server in a Ubuntu server, and point to my own turn / stun server and everything work now. so the problem was the NAT traversal ( both sides behind NAT ).

**Comment by aazjcom** [comment]
@adrianobrancher  i want make a brand new stun/turn server in a ubuntu server .can you give me a config file to me .i always fail in config file.it can work in stun ,but cannot work in turn.
