### ISSUE TITLE
Several errors when using RTCMultiConnection

### ISSUE THREAD

**Issue by dnish** [muaz-khan/RTCMultiConnection#150]
Hey @muaz-khan,
today I've opened the console while getting connected to users, here are some common errors that occur:

```
1d0ccde….js?meteor_js_resource=true:387 Uncaught (in promise) DOMException: Failed to set local answer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set local audio description recv parameters..
```
```
1d0ccde….js?meteor_js_resource=true:387 Uncaught (in promise) DOMException: Failed to set remote offer sdp: Called with SDP without ice-ufrag and ice-pwd.
```

On some of this connections, <code>onStream</code> is fired but the stream never plays. We are using our own STUN + TURN servers (coturn).

**Comment by dnish** [comment]
Closing issue - we've called <code>con.renegotiate()</code> after the local stream of the user was received, to test if it fixes the issue with the empty stream. It didn't fix it but caused the error above.

**Comment by muaz-khan** [comment]
`connection.renegotiate` should be used only in a live-session. There must be at least two users in the room.
