### ISSUE TITLE
Signalr use ?

### ISSUE THREAD

**Issue by avspeed** [muaz-khan/RTCMultiConnection#151]
Hi Muaz,

With version 3 did you drop support for SignalR or can I still get it to work somehow ?
I successfully used a SignalR server with v 2.2 .. thanks

**Comment by muaz-khan** [comment]
[`setCustomSocketHandler `](https://github.com/muaz-khan/RTCMultiConnection#setcustomsockethandler) now supports many signaling options:

1. [XHRConnection.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/XHRConnection.js)
2. [WebSyncConnection.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/WebSyncConnection.js)
3. [SignalRConnection.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/SignalRConnection.js)
4. [SipConnection.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/SipConnection.js)
5. [FirebaseConnection.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/FirebaseConnection.js)
6. [PubNubConnection.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/PubNubConnection.js)

Here is how to use SignalR-Connection:

```html
<script src="/dev/globals.js"></script>
<script src="/dev/SignalRConnection.js"></script>
<script>
var connection = new RTCMultiConnection();
connection.setCustomSocketHandler(SignalRConnection);
</script>
```

**Comment by avspeed** [comment]
Perfect! Thank you

**Comment by asadcr** [comment]
i cannot make it work with SignalR - can any of you guys give me a working example or a head start Thank U

**Comment by avspeed** [comment]
@asadcr in addition to referencing the SignalRConnection.js script, you need a SignalR hub that has the sendToAll function ( note geckoHub is the hub name as specified in the SignalRConnection.js file 

```
public class geckoHub: Hub
    {`
public void sendToAll(string channelName, string message)
        {
            Clients.All.broadcastMessage(channelName, message);
        }`
}
```

This works just fine ..
