### ISSUE TITLE
Screen sharing demo does not work in chrome

### ISSUE THREAD

**Issue by jawadrasheed** [muaz-khan/RTCMultiConnection#163]
I tried to run the code of screen sharing demo  in localhost server. but it does not work. I have given the write path of socket.io.js also.

**Comment by muaz-khan** [comment]
First Step:

> Make sure you're using HTTPs

Second Step:

> Make sure following chrome extension is installed:
>
> https://chrome.google.com/webstore/detail/screen-capturing/ajhifddimkapgcifgcodmmfdlknahffk

Last step:

> Use latest [`screen-sharing.html`](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/screen-sharing.html) file.
> 
> Recently update file now automatically supports [cross-domain screen capturing](https://github.com/muaz-khan/RTCMultiConnection#cross-domain-screen-capturing).

**Comment by jawadrasheed** [comment]
Thanks alot. Actually I didn't have the latest screen-sharing.html file.
