### ISSUE TITLE
How to the Client detect screen sharing end on iOS???

### ISSUE THREAD

**Issue by NguyenTungs** [muaz-khan/RTCMultiConnection#182]
hi @muaz-khan !
Please help me this issues!
I open() function on Chrome Desktop. I using The device iOS join() function. When i stop share Screen. But event onstreamended not work on iOS.

Please help me how I can fix it? Thanks!

**Comment by Nitrick** [comment]
use Leave event instead of onstreamended event it will defiantly work.
