### ISSUE TITLE
TODAY: MACBOOK not working Everywhere demo about audio???

### ISSUE THREAD

**Issue by NguyenTungs** [muaz-khan/RTCMultiConnection#184]
hi @muaz-khan .
TODAY: MACBOOK not working Everywhere demo about audio ???

**Comment by muaz-khan** [comment]
Please recheck the demos. Seems fixed.

**Comment by NguyenTungs** [comment]
Every day I have to test it . But today everything except audio still works . I have test with two machines macbook , and win , it's still working .
link demo : https://rtcmulticonnection.herokuapp.com/demos/Scalable-Broadcast.html

**Comment by muaz-khan** [comment]
![screen shot 2016-06-18 at 1 07 24 pm](https://cloud.githubusercontent.com/assets/477092/16169809/c572cd5a-3555-11e6-92d5-683bdc98e955.png)

Please make sure following file is up-to-dated:

* https://cdn.webrtc-experiment.com/rmc3.min.js

```
// Last time updated: 2016-06-18 7:54:10 AM UTC
```

**Comment by NguyenTungs** [comment]
![screen shot 2016-06-18 at 3 14 41 pm](https://cloud.githubusercontent.com/assets/15043041/16169848/95a053d8-3567-11e6-8cfd-efa435a2c7e6.png)
I checked on your demo . I checked my mic on skype and it 's working well .

**Comment by NguyenTungs** [comment]
Yeah!.

**Comment by NguyenTungs** [comment]
![screen shot 2016-06-18 at 3 42 15 pm](https://cloud.githubusercontent.com/assets/15043041/16169955/7c20f4e0-356b-11e6-880a-79e618bd389d.png)
