### ISSUE TITLE
I have a problem with Screen Share needs help !!!

### ISSUE THREAD

**Issue by NguyenTungs** [muaz-khan/RTCMultiConnection#200]
Hi @muaz-khan.
I have a problem with Screen Share needs help !!!
![screen shot 2016-07-19 at 5 01 45 pm](https://cloud.githubusercontent.com/assets/15043041/16946197/894b9a1a-4dd2-11e6-9d5f-635460813854.png)
. When I open the Screen sharing functionality . A popup appears, but when I click on the Cancel button , then I open it again and click on the share button , but I did not receive a public stream . 
But when I refresh the page , then it's back to normal operation , but to repeat the steps above , it happens that error.
Can you help me a callback function when clicking the Cancel button...
![screen shot 2016-07-19 at 6 01 36 pm](https://cloud.githubusercontent.com/assets/15043041/16947730/e0e732d6-4dda-11e6-8c9f-8918dcfa0386.png)

Thanks & Regards
NguyenTung

**Comment by NguyenTungs** [comment]
Fixed !

**Comment by adershpv** [comment]
I am getting the same issue. How did you fix it?

**Comment by evandromoura** [comment]
After much searching for a solution on the internet, I decided to debug the API.
I solved the problem by commenting on the return.

<img width="531" alt="Captura de Tela 2020-05-29 às 14 10 05" src="https://user-images.githubusercontent.com/18651195/83286389-3267ba80-a1b6-11ea-8023-543b58f999e0.png">

**Comment by evandromoura** [comment]
> I am getting the same issue. How did you fix it?

do this test below
