### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by aemal** [muaz-khan/RTCMultiConnection#204]
Dear Mauz,

I hope you are doing well.

The certificate of the domain https://www.webrtc-experiment.com is expired on 30th July. Can you kindly renew it? I think the screen sharing chrome plugin is dependent on it, therefore I can't use it.

Regards,
Aemal

**Comment by muaz-khan** [comment]
Fixed.

arvixe.com guys took up to 48 hours to fix it!

It isn't easy to transfer domain; because such things takes 7-to-14 days. So I'm still on arvixe :)

BTW, the domain is working now.

_PS. Arvixe guys didn't alert me about SSL expiry._
