### ISSUE TITLE
Initiator's event.extra data is undefined

### ISSUE THREAD

**Issue by dOESoNE** [muaz-khan/RTCMultiConnection#206]
Hello Mr. Khan.
First of all, thank you for all your work.

``` javascript
connection.extra = {
	joinTime: new Date()
};
```

``` javascript
connection.onstream = function (event) {
	console.log(connection.isInitiator + ':' 
		+ connection.extra.joinTime + ':' + event.extra.joinTime);
};
```

Initiator : get connection.extra.joinTime & event.extra.joinTime are OK

Participant : get connection.extra.joinTime is OK, but event.extra.joinTime is undefined

How can participant get event.extra.joinTime (initiator's extra data) ?

**Comment by muaz-khan** [comment]
Are you using [`server.js`](https://github.com/muaz-khan/RTCMultiConnection/blob/master/server.js) and latest [`Signaling-Server.js`](https://github.com/muaz-khan/RTCMultiConnection/blob/master/Signaling-Server.js)

```javascript
connection.extra = {
    joinTime: new Date()
};
connection.updateExtraData();
```

BTW, here is how to get extra-data:

```javascript
var extra = connection.peers['remote-userid'].extra;
alert( extra.joinTime);
```

Recent commit supports this as well:

```javascript
connection.onstream = function(event) {
    if(event.type === 'remote') {
        connection.socket.emit('get-remote-user-extra-data', event.userid, function(extra) {
             alert( extra.joinTime );
        });
    }
}:
```

**Comment by dOESoNE** [comment]
It works great!!
Thank you for your help!!
