### ISSUE TITLE
looking for v3.0 version of get local stream

### ISSUE THREAD

**Issue by chaos986** [muaz-khan/RTCMultiConnection#211]
In 2.2.2 I use:
`var local = connection.streams.selectAll({
                local: true
            });`

but that is now undefined.

I'm using it most often to read or set the extra data of the local stream.

**Comment by muaz-khan** [comment]
```javascript
var localStreams = connection.attachStreams;
localStreams.forEach(function(localStram) {
    var localStreamId = localStream.streamid || localStream.id;
    var streamObject = connection.streamEvents[ localStreamId ];
});
```

Or:

```javascript
Object.keys(connectionstreamEvents).forEach(function(sEvent) {
    var streamObject = connection.streamEvents[ sEvent ];
    if(!streamObject.stream) return;
    if(streamObject.type !== 'local') return; // ignore remote streams

    var localStream = streamObject.stream;
    var localStreamId = streamObject.streamid;

    // yourCustomArray.push( streamObject );
});
```

**Comment by faizanrefai** [comment]
Hello, this is working for me, great,

I like to help you in developing more feature,

I am really impressed what you are developing in webRTC, I like to contribute you in this journey,

I am working in Streebo Inc. see the website,
http://www.streebo.com

But this project is for my self practice and for society. it is not related to Streebo Inc.


Thanks,
Faizan

**Comment by chaos986** [comment]
Thank you. The upgrade v2 to v3 guide is very incomplete, but I am looking forward to finally updating my app and using the new adaptive bandwidth features and future support for Edge that I expect will not make it into v2.
