### ISSUE TITLE
The MediaStream 'ended' event is deprecated.

### ISSUE THREAD

**Issue by gmbad** [muaz-khan/RTCMultiConnection#212]
Hello Muaz!

I am getting the following warning on google chrome:

"The MediaStream 'ended' event is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5730404371791872 for more details."

Can you help solve this problem?

Thank you very much,

Gabriel

**Comment by alexandrevilain** [comment]
I'm not sure about my answer, but to delete this deprecation warning, I replaced 3 event listeners.
Line 1042 - 4609 - 4699 remplace : 
`stream.addEventListener('ended', function() {`
by : 
`stream.addEventListener('inactive', function() {`

It works in chrome 52. I'll test it in other chrome version. 
Alexandre.

**Comment by gmbad** [comment]
Thank alexandrevilain and Muaz.
