### ISSUE TITLE
Android file error

### ISSUE THREAD

**Issue by mado1987** [muaz-khan/RTCMultiConnection#218]
Hi. After I run the app on Android, when i start broadcasting, i get the message : 
cordova-plugin-iosrtc.js:2577 GET blob:file%3A///e35d3b9f-e101-4a09-afff-7db8bec40593 404 (Not Found)
I see the name is wrong ,it it "%3A" instead of ":". Thanks!

**Comment by muaz-khan** [comment]
Did it work after replacing `%3A` with colon `:`?

**Comment by mado1987** [comment]
The name is auto generated. I don't know where to change it

**Comment by muaz-khan** [comment]
```javascript
connection.onstream = function(event) {
    var url = URL.createObjectURL( event.stream );
    url = url.replace('%3A', ':');
    event.mediaElement.src = url;
    event.mediaElement.play();
}:
```

**Comment by mado1987** [comment]
Now the name appears ok, but still says file not found. I used your app code and run it on an android device..

**Comment by mado1987** [comment]
Ok, now it works, but now the problem is that, if i broadcast from pc browser and open in the android app the same broadcast, is ok, i can see it from my phone. But if i change, and start broadcasting from the phone app, and try to see from the pc i got the following issue: 
" undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). "  and there is no video neither on the app, neither on the pc. Any idea?Thanks!

**Comment by muaz-khan** [comment]
Following error is forcing us use `promises` everywhere:

```sh
# it is NOT important, completely optional
undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). 
```

Please share Chrome console logs from desktop browser; and please try to use `new-broadcast-id` to make sure `Signaling-Server.js` is NOT the issue.

**Comment by mado1987** [comment]
These are the desktop logs, but i can't see also on the phone the preview of the video..

check-broadcast-presence 112233456 true
Scalable-Broadcast.html:169 join-broadcaster Object {typeOfStreams: Object, userid: "112233456", broadcastId: "112233456"}
rmc3.min.js:16 server-logs You <iaa28nrhkoz85mi> are getting data/stream from <112233456>
rmc3.min.js:15 112233456 online
rmc3.min.js:16 Remote peer's sdp: v=0
o=- 8936227257889581625 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS 2edV0Yh0bh8nJ4LixRDs42SD9p2PK391GnKm
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 0 8 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:xJ9XxDN61TWbjzoy
a=ice-pwd:LX/SeRI/OVK3zCwbpbWlcaK3
a=fingerprint:sha-256 BE:51:F4:58:46:9E:B7:CD:A4:C9:E9:88:0F:31:F6:2A:6E:2A:91:B9:CA:13:AB:CD:71:41:B7:C9:C2:DA:4F:08
a=setup:actpass
a=mid:audio
b=AS:128
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1; stereo=1; sprop-stereo=1; maxaveragebitrate=1048576; maxplaybackrate=1048576
a=maxptime:3
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:126 telephone-event/8000
a=ssrc:1352301016 cname:jLu7DnfJvQGQGmdu
a=ssrc:1352301016 msid:2edV0Yh0bh8nJ4LixRDs42SD9p2PK391GnKm f2f1d594-2ff9-46ba-bddf-0f21fe262c12
a=ssrc:1352301016 mslabel:2edV0Yh0bh8nJ4LixRDs42SD9p2PK391GnKm
a=ssrc:1352301016 label:f2f1d594-2ff9-46ba-bddf-0f21fe262c12
m=video 9 UDP/TLS/RTP/SAVPF 101 100 116 117 96 97 98
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:xJ9XxDN61TWbjzoy
a=ice-pwd:LX/SeRI/OVK3zCwbpbWlcaK3
a=fingerprint:sha-256 BE:51:F4:58:46:9E:B7:CD:A4:C9:E9:88:0F:31:F6:2A:6E:2A:91:B9:CA:13:AB:CD:71:41:B7:C9:C2:DA:4F:08
a=setup:actpass
a=mid:video
b=AS:512
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtpmap:101 VP9/90000
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtcp-fb:101 transport-cc
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=fmtp:100 x-google-min-bitrate=4194304; x-google-max-bitrate=4194304
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=101
a=rtpmap:98 rtx/90000
a=fmtp:98 apt=116
a=ssrc-group:FID 3505835486 492467887
a=ssrc:3505835486 cname:jLu7DnfJvQGQGmdu
a=ssrc:3505835486 msid:2edV0Yh0bh8nJ4LixRDs42SD9p2PK391GnKm 7827f83d-9e59-4750-9e34-9aaa31fd8b09
a=ssrc:3505835486 mslabel:2edV0Yh0bh8nJ4LixRDs42SD9p2PK391GnKm
a=ssrc:3505835486 label:7827f83d-9e59-4750-9e34-9aaa31fd8b09
a=ssrc:492467887 cname:jLu7DnfJvQGQGmdu
a=ssrc:492467887 msid:2edV0Yh0bh8nJ4LixRDs42SD9p2PK391GnKm 7827f83d-9e59-4750-9e34-9aaa31fd8b09
a=ssrc:492467887 mslabel:2edV0Yh0bh8nJ4LixRDs42SD9p2PK391GnKm
a=ssrc:492467887 label:7827f83d-9e59-4750-9e34-9aaa31fd8b09

undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
rmc3.min.js:16 Remote peer's candidate pairs: candidate:208782571 1 udp 2113937151 10.10.0.151 34669 typ host generation 0 ufrag xJ9XxDN61TWbjzoy
rmc3.min.js:16 Remote peer's candidate pairs: candidate:208782571 2 udp 2113937150 10.10.0.151 47675 typ host generation 0 ufrag xJ9XxDN61TWbjzoy
rmc3.min.js:16 Remote peer's candidate pairs: candidate:208782571 1 udp 2113937151 10.10.0.151 59723 typ host generation 0 ufrag xJ9XxDN61TWbjzoy
rmc3.min.js:16 Remote peer's candidate pairs: candidate:208782571 2 udp 2113937150 10.10.0.151 53726 typ host generation 0 ufrag xJ9XxDN61TWbjzoy

**Comment by mado1987** [comment]
And this are the phone logs:

check-broadcast-presence 112233456 false
index.js:138 start-broadcasting Object
loadRTCMultiConnection.js:5 server-logs You <112233456> are now serving the broadcast.
loadRTCMultiConnection.js:4 The MediaStream 'ended' event is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5730404371791872 for more details.
index.js:165 ObjectblobURL: "blob:file:///763cc5e1-3601-4205-b42e-7ac8845e3e0c"extra: ObjectisAudioMuted: truestream: MediaStreamstreamid: "2edV0Yh0bh8nJ4LixRDs42SD9p2PK391GnKm"type: "local"userid: "112233456"__proto__: Object
undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
loadRTCMultiConnection.js:5 server-logs You <112233456> are now relaying/forwarding data/stream to <iaa28nrhkoz85mi>
loadRTCMultiConnection.js:4 iaa28nrhkoz85mi online
loadRTCMultiConnection.js:7 Your candidate pairs: candidate:208782571 1 udp 2113937151 10.10.0.151 34669 typ host generation 0 ufrag xJ9XxDN61TWbjzoy
loadRTCMultiConnection.js:7 Your candidate pairs: candidate:208782571 2 udp 2113937150 10.10.0.151 47675 typ host generation 0 ufrag xJ9XxDN61TWbjzoy
loadRTCMultiConnection.js:7 Your candidate pairs: candidate:208782571 1 udp 2113937151 10.10.0.151 59723 typ host generation 0 ufrag xJ9XxDN61TWbjzoy
loadRTCMultiConnection.js:7 Your candidate pairs: candidate:208782571 2 udp 2113937150 10.10.0.151 53726 typ host generation 0 ufrag xJ9XxDN61TWbjzoy
loadRTCMultiConnection.js:5 Remote peer's sdp: v=0
o=- 8437116244999271572 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 0 8 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:QP3um55W/hKvtvDk
a=ice-pwd:50wwPSHchO0uZevzz19LQUd1
a=fingerprint:sha-256 BD:E0:2F:9F:AA:BF:9A:CB:28:9B:99:EC:37:8B:32:1F:9B:E6:49:FB:E9:6B:A4:56:40:12:05:84:68:71:07:17
a=setup:active
a=mid:audio
b=AS:128
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1; stereo=1; sprop-stereo=1; maxaveragebitrate=1048576; maxplaybackrate=1048576
a=maxptime:3
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:126 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 101 100 116 117 96 97 98
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:QP3um55W/hKvtvDk
a=ice-pwd:50wwPSHchO0uZevzz19LQUd1
a=fingerprint:sha-256 BD:E0:2F:9F:AA:BF:9A:CB:28:9B:99:EC:37:8B:32:1F:9B:E6:49:FB:E9:6B:A4:56:40:12:05:84:68:71:07:17
a=setup:active
a=mid:video
b=AS:512
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:101 VP9/90000
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtcp-fb:101 transport-cc
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=fmtp:100 x-google-min-bitrate=4194304; x-google-max-bitrate=4194304
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=101
a=rtpmap:98 rtx/90000
a=fmtp:98 apt=116

**Comment by mado1987** [comment]
I haven't yet implemented my server, i use yours for test for now: https://rtcmulticonnection.herokuapp.com:443/     :)

**Comment by muaz-khan** [comment]
If you shared desktop's logs, then it seems that android is using `recvonly` which means that android did NOT attach any stream.

Android must use either `sendonly` or `sendreceiv`.

BTW, please try following on android:

```javascript
$('#btn-check-attached-streams').click(function() {
    var attachedAnyStream = false;
    connection.getAllParticipants().forEach(function(p) {
          if(connection.peers[p].peer.getLocalStreams().length > 0) {
               attachedAnyStream = true;
          }
    });
    alert('attachedAnyStream: ' + attachedAnyStream);
});
```

**Comment by mado1987** [comment]
I can't use jquery, but i did it with js :
   document.querySelector('.btn-check-attached-streams').onclick = function() {
            var attachedAnyStream = false;
            console.log(connection);
            connection.getAllParticipants().forEach(function(p) {
                if(window.connection.peers[p].peer.getLocalStreams().length > 0) {
                    attachedAnyStream = true;
                }
            });
            alert('attachedAnyStream: ' + attachedAnyStream);


        };

I get connection undefined. Also if i do it with window.connection...

**Comment by mado1987** [comment]
Ok, for IOS is working perfectly, i made an app and the streaming is perfect..But for android still that issue..i get recvonly when i check the logs.Any idea how to change it to sendreceiv? :D

**Comment by mado1987** [comment]
Hi Muaz. I found the error. Practically, when i run it on android, and i log the DetectRTC.MediaDevices i get the following for any device:  HTTPs is required to get label of this videoinput device.


Object {deviceId: "default", kind: "audioinput", label: "HTTPs is required to get label of this audioinput device.", groupId: "2004946474", id: "default"}
controllers.js:328 Object {deviceId: "63050f06f93b77644f25950f3b581df7e6e0d4cf2742e8efa9357cf71b907678", kind: "videoinput", label: "HTTPs is required to get label of this videoinput device.", groupId: "", id: "63050f06f93b77644f25950f3b581df7e6e0d4cf2742e8efa9357cf71b907678"}deviceId: "63050f06f93b77644f25950f3b581df7e6e0d4cf2742e8efa9357cf71b907678"groupId: ""id: "63050f06f93b77644f25950f3b581df7e6e0d4cf2742e8efa9357cf71b907678"kind: "videoinput"label: "HTTPs is required to get label of this videoinput device."toJSON: toJSON()__proto__: Object
controllers.js:328 Object {deviceId: "835acea08d27ea4ae22fbe97aaf8fb554e4cb0b7d106a77e9407cd87ed1175a6", kind: "videoinput", label: "HTTPs is required to get label of this videoinput device.", groupId: "", id: "835acea08d27ea4ae22fbe97aaf8fb554e4cb0b7d106a77e9407cd87ed1175a6"}deviceId: "835acea08d27ea4ae22fbe97aaf8fb554e4cb0b7d106a77e9407cd87ed1175a6"groupId: ""id: "835acea08d27ea4ae22fbe97aaf8fb554e4cb0b7d106a77e9407cd87ed1175a6"kind: "videoinput"label: "HTTPs is required to get label of this videoinput device."toJSON: toJSON()arguments: nullcaller: nulllength: 0name: "toJSON"__proto__: ()apply: apply()arguments: (...)get arguments: ThrowTypeError()set arguments: ThrowTypeError()bind: bind()call: call()caller: (...)get caller: ThrowTypeError()set caller: ThrowTypeError()constructor: Function()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()__proto__: Object<function scope><function scope>__proto__: Object
controllers.js:328 Object {deviceId: "default", kind: "audiooutput", label: "HTTPs is required to get label of this audiooutput device.", groupId: "2004946474", id: "default"}deviceId: "default"groupId: "2004946474"id: "default"kind: "audiooutput"label: "HTTPs is required to get label of this audiooutput device."toJSON: toJSON()__proto__: Object
controllers.js:328 Object {deviceId: "default", kind: "audioinput", label: "HTTPs is required to get label of this audioinput device.", groupId: "2004946474", id: "default"}
controllers.js:328 Object {deviceId: "default", kind: "audiooutput", label: "HTTPs is required to get label of this audiooutput device.", groupId: "2004946474", id: "default"}

**Comment by mado1987** [comment]
I discovered the error. You need to ask user permission for the camera, the manifest modify isn't enough.  :dancer:
