### ISSUE TITLE
Recording in rtcmulticonnection v.3

### ISSUE THREAD

**Issue by alifyaqhi09** [muaz-khan/RTCMultiConnection#220]
Hi, i have a problem with recording in rtcmulticonnection v.3,,, i'm use getmediaelement.js for the layout and copy the recording code from API reference in rtcmulticonnection .. then i got this error

(index):497 Uncaught TypeError: Cannot read property 'VyQg2MfJWsczmm4CscCisojW13AW0GXgkaIq' of undefined
onRecordingStarted @ (index):497recordVideo
onclick @ getMediaElement.js:148

i'm also cant mute/unmute .....problem with the onstream event.streamid,,,. please help me, thanks ;)

**Comment by muaz-khan** [comment]
For any RTCMultiConnection version:

```html
<script src="https://cdn.WebRTC-Experiment.com/RecordRTC.js"></script>
<script>
connection.onstream = function(event) {
    var recorder = RecordRTC(event.stream, {type: 'video'});
    recorder.startRecording();

    var btnStopRecording = document.createElement('button');
    btnStopRecording.onclick = function() {
         btnStopRecording.onclick = function() {};

         recorder.stopRecording(function() {
               var blob = recorder.getBlob();
               window.open( URL.createObjectURL(blob) );
         });
    }:

     event.stream.oninactive = event.stream.onended = function() {
           btnStopRecording.onclick();
     };
};
</script>
```

**Comment by alifyaqhi09** [comment]
Thanks for the answer sir,, problem solved ;)

**Comment by rohitsharma4282** [comment]
@muaz-khan sir i want to record video with audio and upload that to php server ..... but it is needed to be done automatically on two events with jquery ..... i made 2 methods to start and stop ..... but chrome console gives error TypeError: Cannot read property 'stopRecording' of undefined on stop function stopRec() on line "recorder.stopRecording(function() {".
 Please help me with this issue .....
var recorder;
			
				navigator.mediaDevices.getUserMedia({ video: true, audio: true }).then(function(camera) {

					// preview camera during recording
					document.getElementById('your-video-id').muted = false;
					setSrcObject(camera, document.getElementById('your-video-id'));

					// recording configuration/hints/parameters
					var recordingHints = {
						type: 'video'
					};

					// initiating the recorder
					var recorder = RecordRTC(camera, recordingHints);
					// starting recording here
					recorder.startRecording();
					
				});
			function startRec() {
				
			}
               
                   

             function stopRec() {
           
				navigator.mediaDevices.getUserMedia({ video: true, audio: true }).then(function(camera) {
						 // stop recording
							recorder.stopRecording(function() {
								
								// get recorded blob
								var blob = recorder.getBlob();

								// generating a random file name
								var fileName = jQuery("#fName").val();//getFileName('webm');
								alert(jQuery("#fName").val());
								// we need to upload "File" --- not "Blob"
								var fileObject = new File([blob], fileName, {
									type: 'video/webm'
								});

								uploadToPHPServer(fileObject, function(response, fileDownloadURL) {
									if(response !== 'ended') {
										document.getElementById('header').innerHTML = response; // upload progress
										return;
									}

									document.getElementById('header').innerHTML = '<a href="' + fileDownloadURL + '" target="_blank">' + fileDownloadURL + '</a>';

									alert('Successfully uploaded recorded blob.');

									// preview uploaded file
									document.getElementById('your-video-id').src = fileDownloadURL;

									// open uploaded file in a new tab
									window.open(fileDownloadURL);
								});

								// release camera
								document.getElementById('your-video-id').srcObject = document.getElementById('your-video-id').src = null;
								camera.getTracks().forEach(function(track) {
									track.stop();
								});

							});
					});
			}   
            function uploadToPHPServer(blob, callback) {
                // create FormData
                var formData = new FormData();
                formData.append('video-filename', blob.name);
                formData.append('video-blob', blob);
                callback('Uploading recorded-file to server.');
                makeXMLHttpRequest('/record/uploads/save.php', formData, function(progress) {
                    if (progress !== 'upload-ended') {
                        callback(progress);
                        return;
                    }
                    var initialURL = '/record/uploads/' + jQuery("#fName").val();
                    callback('ended', initialURL);
                });
            }

            function makeXMLHttpRequest(url, data, callback) {
                var request = new XMLHttpRequest();
                request.onreadystatechange = function() {
                    if (request.readyState == 4 && request.status == 200) {
                        if (request.responseText === 'success') {
                            callback('upload-ended');
                            return;
                        }
                        alert(request.responseText);
                        return;
                    }
                };
                request.upload.onloadstart = function() {
                    callback('PHP upload started...');
                };
                request.upload.onprogress = function(event) {
                    callback('PHP upload Progress ' + Math.round(event.loaded / event.total * 100) + "%");
                };
                request.upload.onload = function() {
                    callback('progress-about-to-end');
                };
                request.upload.onload = function() {
                    callback('PHP upload ended. Getting file URL.');
                };
                request.upload.onerror = function(error) {
                    callback('PHP upload failed.');
                };
                request.upload.onabort = function(error) {
                    callback('PHP upload aborted.');
                };
                request.open('POST', url);
                request.send(data);
            }
