### ISSUE TITLE
onUserStatusChanged() getting fired more than once when a new user joins

### ISSUE THREAD

**Issue by codernavi18** [muaz-khan/RTCMultiConnection#221]
On the [demo](https://rtcmulticonnection.herokuapp.com/demos/) of Audio+Video+TextChat+FileSharing, 

when a new user joins, the onUserStatusChanged is fired more than once (about 6 times) for the new user joined.

**Comment by muaz-khan** [comment]
Yep, it is intentional, to make status as much reliable as possible.

Please use [`onUserStatusChanged`](http://www.rtcmulticonnection.org/docs/onUserStatusChanged/) only to update offline/online icons.

**Comment by codernavi18** [comment]
I have a webpage where I am showing the list of people in the current room (in which I am also present). When a new user joins, I want to add the new user to the list of users in the room, so that now there are (n+1) people in the room.

With this behaviour, my code will definitely add a new user 6 times to the list of users in the room.

How can I update existing users, about arrival of a new user then (only once, not 6 times or so)?

**Comment by muaz-khan** [comment]
```javascript
connection.onUserStatusChanged = function(event) {
    numberOfUsersBox.innerHTML = connection.getAllParticipants().length;
    updateUsersList();
};

function updateUsersList() {
     usersList.innerHTML = '';
     connection.getAllParticipants.forEach(function(p) {
         var li = document.createElement('li');
         li.id = p; // to reuse this <li>
         li = connection.peers[p].userid; // or extra-data.fullName
         usersList.appendChild(li);
     });
}
```

**Comment by codernavi18** [comment]
Thanks but this does not serve my purpose, as I am not showing a simple text string, otherwise this would have been great solution. I have added the animation for a new user. His icon drops from top to `user-in-room-div` , similar to StackOverflow chat rooms. So I have to know the exact user details.

Maintaining an array locally would also suffice.

Thanks.

[PS : Can you please give any idea about issue#220]

**Comment by muaz-khan** [comment]
To make sure `onUserStatusChanged` fires once.

```javascript
var onlineUsers = {};
var offlineUsers = {};

connection.onUserStatusChanged = function(event) {
    if (event.status === 'online' && !onlineUsers[event.userid]) {
        onlineUsers[event.userid] = event.userid;

        // place your code here
        // this user is online; show him online

        yourUnique_onUserStatusChanged_Event(event);
    }

    if (event.status === 'offline' && !offlineUsers[event.userid]) {
        offlineUsers[event.userid] = event.userid;

        // place your code here
        // this user is offline; show him offline

        yourUnique_onUserStatusChanged_Event(event);
    }
};

function yourUnique_onUserStatusChanged_Event(event) {
  // this fucntion is called once for each user
  // place your codes here
}
```

**Comment by codernavi18** [comment]
Thanks.....
This is how I just implemented, maintaining a local array.

However, you dedication made me your fan.
Thanks. This completely solves the problem.
