### ISSUE TITLE
different Local and remote videos container

### ISSUE THREAD

**Issue by alifyaqhi09** [muaz-khan/RTCMultiConnection#223]
can anyone help me,,,  i want to make diffrent size in local and remote videos container,, and modify the remote videos with extra data...
in the example code, they all have the same video containers.

i'm still learning this awesome project,, thank you sir ;)

**Comment by muaz-khan** [comment]
Please check & try this demo:

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/v2.2.2/demos/AppRTC-Look.html#L316
