### ISSUE TITLE
[Help] Make a custom message

### ISSUE THREAD

**Issue by alifyaqhi09** [muaz-khan/RTCMultiConnection#226]
i want to make a chatting,,, but i have a little problem...
i'm use canvas designer,, :

> connection.onmessage = function(event) {
>           if(event.data === 'plz-sync-points') {
>               designer.sync();
>               return;
>           }
>             designer.syncData( event.data );
>       };

i dont know how to add event chat in there,, so i'm using other way :

> connection.socketCustomEvent = 'chat';
> var socket = connection.getSocket();
> socket.emit(connection.socketCustomEvent, document.getElementById('chatbox').value);
> socket.on(connection.socketCustomEvent, function(message) {
>         alert(message);
>       });

no error... but nothing happend xD
can anyone give me a clue about this.... Thank you :)

**Comment by muaz-khan** [comment]
You can use WebRTC datachannels to share chat messages or files.

```html
<input type="text" id="txt-chat-message" placeholder="Enter chat message">
<button id="btn-send-chat">Send Chat</button>

<script src="jquery.js"></script> <!-- jQuery is optional -->
<script>
$('#btn-send-chat').click(function() {
    var chatMessagea = $('#txt-chat-message').val();
    connection.send({
        chatMessage: chatMessage,
        senderFullName: 'Bob'
    });
});

connection.onmessage = function(event) {
    if (event.data.chatMessage) { // if it is a chat-message
       showChatMessage(event.data.senderFullName, event.data.chatMessage); // your own method that displays chat message
        return; // skip rest
    }

    // chat-designer code goes here
};

// your own method that displays chat message
function showChatMessage(senderFullName, chatMessage) {
    // create DIV
    // append to somewhere
    alert(senderFullName + ' says: ' + chatMessage);
}
</script>
```
