### ISSUE TITLE
Problems on Cordova app

### ISSUE THREAD

**Issue by dnish** [muaz-khan/RTCMultiConnection#245]
Hey @muaz-khan,
just having an issue with my current Cordova project. Most of the time, the connection between the two clients get established, but the stream doesn't start playing. If I try it via browser, everything works fine. I'm using an Android 6 device and Chrome.

This is what my WebRTC internals show:

```
1.10.2016, 10:51:25	
addStream

1.10.2016, 10:51:25	
setRemoteDescription

1.10.2016, 10:51:25	
onRenegotiationNeeded

1.10.2016, 10:51:25	
signalingStateChange

1.10.2016, 10:51:25	
onAddStream

1.10.2016, 10:51:25	
setRemoteDescriptionOnSuccess

1.10.2016, 10:51:25	
createAnswer

1.10.2016, 10:51:25	
createAnswerOnSuccess

1.10.2016, 10:51:25	
setLocalDescription

1.10.2016, 10:51:25	
signalingStateChange

1.10.2016, 10:51:25	
setLocalDescriptionOnSuccess

1.10.2016, 10:51:25	
iceGatheringStateChange

1.10.2016, 10:51:25	
onIceCandidate

1.10.2016, 10:51:25	
onIceCandidate

1.10.2016, 10:51:26	
onIceCandidate

1.10.2016, 10:51:26	
onIceCandidate

1.10.2016, 10:51:26	
onIceCandidate

1.10.2016, 10:51:26	
iceGatheringStateChange

1.10.2016, 10:51:41	
stop
1.10.2016, 10:51:41	
iceConnectionStateChange

1.10.2016, 10:51:41	
signalingStateChange
```  

There are no error logs in the console, so I really don't know whats going on here. Both devices are in the same network without any restrictions. I also receive a remote MediaStream via <code>RTCConnection.getRemoteStreams()</code> and all local streams are also working fine.

**Comment by dnish** [comment]
For everyone who is running into the same problem, you need to set the following permission

        <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

Only setting "RECORD_AUDIO" isn't sufficient.

**Comment by demym** [comment]
Hi muaz-khan, great work here, really enjoying the node/web part of the story :-)

But

1) cannot find the cordova android samples you are talking in the demo notes page;

2) trying to create a cordova app and then putting into the index.html you code, i get 'Uncaught TypeError: Property 'getUserMedia' of object #<Navigator> is not a function '....

Really want to implement this in an Android Cordova app; i have setted up my local node server using your code correctly, but not able to find or solve Android Cordova part...

**Comment by muaz-khan** [comment]
@demym You can download (or view online) cordova apps here:

* http://webrtcweb.com:9001/cordova-apps/

**Comment by NazimMertBilgi** [comment]
Include the adapter.js file in index.html.
