### ISSUE TITLE
Android 6 problem?

### ISSUE THREAD

**Issue by ubuntutest** [muaz-khan/RTCMultiConnection#256]
Hi guys,
Scalable Broadcast worked quite well on Android 5.1, the problem was the communication between different networks.

Now I have upgraded my smartphone from android 5.1 to 6.0, and does not work anymore.
Start the app from  my smartphone, enter a room, and nothing happens. The webcam is not active.

Any idea?

**Comment by muaz-khan** [comment]
Please check scalable-broadcast Android "App permissions" and make sure that following options are enabled:

1. Camera
2. Microphone

Usually above options are disabled if you install APK from an unauthorized source.

PS. I'm using Android 7.0 on Nexus 6p; and scalable-broadcast app is working fine there.

**Comment by ubuntutest** [comment]
Solved,
thank you, I have not yet familiar with Android 6
