### ISSUE TITLE
Connect without microphone

### ISSUE THREAD

**Issue by mantaplatte** [muaz-khan/RTCMultiConnection#259]
Hello, i've made a audio+screen session with many user, is it possible that some users can join without a microphone? Now they get the error: DevicesNotFoundError
Thanks :)

**Comment by muaz-khan** [comment]
Yep, it is possible. I'll bring a demo shortly (1-2 days).

**Comment by mantaplatte** [comment]
Thank you :) can you post it here?

**Comment by mantaplatte** [comment]
Hm did you forget it?

**Comment by mantaplatte** [comment]
Is there any solution for it?

**Comment by mantaplatte** [comment]
var connection = new RTCMultiConnection();
connection.session = {
    audio: true,
    oneway:true,
    screen: true,
    data:true
};
if (!connection.isInitiator){
    console.log("is not I");
  if (DetectRTC.audioInputDevices.length) {
      console.log("add micro K");
                connection.addStream({
                    audio: true,
                });
            }
}
  connection.enableFileSharing = true;
var sessions = {};
connection.onNewSession = function(session) {
    // if room is not transmitted once;
    // "onNewSession" will be called multiple times for same session;
    // we need to store session-id in an object.
    if (sessions[session.sessionid]) return;
    sessions[session.sessionid] = session;

    session.join({
        audio: true
    });
};

This is how i solved it.

**Comment by mantaplatte** [comment]
var connection = new RTCMultiConnection();
connection.session = {
    audio: true,
    oneway:true,
    screen: true,
    data:true
};

  connection.enableFileSharing = true;
var sessions = {};
connection.onNewSession = function(session) {
    session.join({
        audio: true,
        screen:true,
        oneway:true
    });
};
if (!connection.isInitiator){
    console.log("is not I");
  if (DetectRTC.audioInputDevices.length) {
      console.log("add micro K");
                connection.addStream({
                    audio: true,
                });
            }
            else{
                connection.addStream({
                    screen: true,
                    oneway: true
                });
            }
}

My solution how to fix it.

**Comment by mantaplatte** [comment]
var connection = new RTCMultiConnection();
connection.session = {
    audio: true,
    oneway:true,
    screen: true,
    data:true
};

  connection.enableFileSharing = true;
var sessions = {};
connection.onNewSession = function(session) {
    session.join({
        audio: true,
        screen:true,
        oneway:true
    });
};
if (!connection.isInitiator){
  if (DetectRTC.audioInputDevices.length) {
                connection.addStream({
                    audio: true,
                });
            }
            else{
                connection.addStream({
                    screen: true,
                    oneway: true
                });
            }
}

**Comment by muaz-khan** [comment]
`DetectRTC.audioInputDevices` returns list of available audio-input devices, but it doesn't let us know if audio device is actually available or not.

So, this can be a solution:

```javascript
connection.dontCaptureUserMedia = true;

if (DetectRTC.audioInputDevices.length) {
    navigator.getUserMedia = navigator.getUserMedia || navigator.mozGetUserMedia || navigator.webkitGetUsermMedia;
    navigator.getUserMedia({
        audio: true,
        video: true
    }, function(stream) {
        connection.attachStreams = [stream]; // attachStreams.push
        connection.join('room-id');
    }, function() {
        joinWithOnlyVideoOrOnlyScreen(); // fallback
    });
} else {
    joinWithOnlyVideoOrOnlyScreen(); // fallback
}

function joinWithOnlyVideoOrOnlyScreen() {
    // either capture video or screen
    // or join with nothing (except data)
    connection.join('room-id');
}
```
