### ISSUE TITLE
cannot use JSON.stringify inside DetectRTC load function ?

### ISSUE THREAD

**Issue by avspeed** [muaz-khan/RTCMultiConnection#261]
Hello,

For some reason I cannot use JSON.stringify inside the DetectRTC load function
I get a Uncaught TypeError: Illegal invocation error

```
connection.DetectRTC.load(function() {
console.log(JSON.stringify(connection.DetectRTC.videoInputDevices));
});
``
Any idea ? Thanks`

**Comment by muaz-khan** [comment]
`toJSON` function seems causing the issue. Please try this instead:

```javascript
```

**Comment by avspeed** [comment]
Thank you very much! That works perfectly.
