### ISSUE TITLE
IndexSizeError

### ISSUE THREAD

**Issue by mantaplatte** [muaz-khan/RTCMultiConnection#267]
Hey, i get this error and i didnt manage it to solve it. 
rmc3.min.js:7 Uncaught IndexSizeError: Failed to set the 'volume' property on 'HTMLMediaElement': The volume provided (1.2) is outside the range [0, 1].
Thanks :)

**Comment by Patrick-Vogt** [comment]
```JavaScript
   getRMCMediaElement(stream, function(mediaElement) {
                mediaElement.id = stream.streamid;
                mediaElement.muted = true;
                mediaElement.volume = 0;

```
Change it to zero and try again. Only 0 or 1 (= true or false) are allowed.
I also would prefer the non-minified version for developement. When u're finished you can minify it yourself and upload it.

**Comment by mantaplatte** [comment]
Thank you :)

**Comment by muaz-khan** [comment]
A bug somewhere in the lib?

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/StreamsHandler.js#L123

**Comment by mantaplatte** [comment]
I changed Volume from 0 to 1 and then dont add volume.

 mediaElement.volume = 1; //like this
            afterEach(200, 5, function() {
                mediaElement.volume += 0; // and this
