### ISSUE TITLE
OnNewSession event is not fired when url's querystring is different

### ISSUE THREAD

**Issue by vinaybr** [muaz-khan/RTCMultiConnection#27]
Hi,

I am trying to integrate video conferencing onto an existing website which makes use of querystring to navigate between different sections in a page. So different participants might have a difference in the querystring part of the url. 
This is causing the onNewSession event to not fire for users who have a different querystring from the initiator. 
How do i workaround this problem?

**Comment by muaz-khan** [comment]
* http://www.rtcmulticonnection.org/docs/constructor/
* http://www.rtcmulticonnection.org/docs/channel-id/

```javascript
var connection = new RTCMultiConnection('channel-id');

// or
var connection = new RTCMultiConnection();
connection.channel = 'channel-id';
```

i.e. `channel-id` MUST be manually passed. If channel-id is absent, then this value is used:

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/RTCMultiConnection.js#L5

```javascript
window.RMCDefaultChannel = location.href.replace(/\/|:|#|\?|\$|\^|%|\.|`|~|!|@|\[|\||]|\|*. /g, '').split('\n').join('').split('\r').join('');
```

Reference where used:

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/RTCMultiConnection.js#L16

**Comment by vinaybr** [comment]
Hi muaz, thanks for your reply. This helped me resolve the issue.
