### ISSUE TITLE
how to use external stream with RMC?

### ISSUE THREAD

**Issue by jiangts** [muaz-khan/RTCMultiConnection#270]
According to the docs it appears that

```
connection.attachStreams.push(stream);
```

adds an external stream to RMC. But how does another client consume the stream? 
I'm listening to 

```
connection.onstream
```

event and am not getting anything

**Comment by muaz-khan** [comment]
Please try this:

```javascript
// there is NO 'onstream' event for external stream
yourOwnVideo.src = URL.createObjectURL ( externalStream );
yourOwnVideo.play();

connection.attachStreams = [ externalStream ];
connection.dontCaptureUserMedia = true; // if you want to share ONLY the external stream

// the rest is unchanged
connection.openOrJoin('room-id');
```

Now, `onstream` event will get fired only for remote videos. (for all users)

**Comment by jiangts** [comment]
Thanks for the response. For some reason, I am not getting the `onstream` event for my externalStreams still. Do I need to call `.openOrJoin` AFTER setting `attachStreams`? Because right now I open the connection and only then set `attachStreams`.

**Comment by jiangts** [comment]
aha, I found the `renegotiate` API. thank you so much!
