### ISSUE TITLE
 RTCConnection.onopen fires wrong

### ISSUE THREAD

**Issue by dnish** [muaz-khan/RTCMultiConnection#274]
Hey @muaz-khan,
since the last update, <code>RTCConnection.onopen</code> doesn't work correctly. We have a video chat application where the user get's notified if he gets a call. He can accept or decline the call. Since the new update, the <code>RTCConnection.onopen</code> is fired directly after creating a call on the caller side. Normally the function is called, when the receiver accepts the call. Everything has worked fine before the last update. The problem is that the caller now sees the video view instead the "Waiting for answer..." view.

**Comment by muaz-khan** [comment]
`onopen` seems working fine in this demo:

* https://rtcmulticonnection.herokuapp.com/demos/Audio+Video+TextChat+FileSharing.html

RTCPeerConnection.js is NOT updated since July 21:

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/RTCPeerConnection.js

**Comment by dnish** [comment]
Hey, I'm using the latest RTCMultiConnection.js (dist/RTCMultiConnection.js). After replacing the files, the behavior of <code>onopen</code> changes. Normally this is the way:

1. Caller calls receiver
2. Caller sees a waiting screen
3. Receiver sees a "New call" screen
4. Receiver accepts call, both users see the video screen.

Behavior after updating:

1. Caller calls receiver
2. Caller sees immediately the black video screen, instead the "New call" screen.
3. Receiver sees a "New call" screen
4. Receiver accepts call, both users see the video screen.

The only part in the code where we handle the video view is this one:

    RTCConnection.onopen = function (e) {
            ViewModel.findOne("video").showVideoView(true);
    };

RTCConnection is a <code>RTCMultiConnection</code> object.

After reverting the file, everything works fine again.

**Comment by muaz-khan** [comment]
Seems a bug somewhere in this function:

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/RTCMultiConnection.js#L391

Previously we were capturing stream [here](https://github.com/muaz-khan/RTCMultiConnection/commit/28f0f7488a648fe93abd4d5badd622c19dcd952d#diff-fcb653c72573f7cf04966219beac2738L344). Now using `beforeJoin` method instead.

BTW, hope you updated `Signaling-Server.js` as well?

**Comment by dnish** [comment]
Yep, the signaling server is up-to-date.

**Comment by dnish** [comment]
This is btw the code how we handle incoming call requests:

    RTCConnection.onNewParticipant = function (participantId, userPreferences) {


        // if OfferToReceiveAudio/OfferToReceiveVideo should be enabled for specific users
        userPreferences.localPeerSdpConstraints.OfferToReceiveAudio = true;
        userPreferences.localPeerSdpConstraints.OfferToReceiveVideo = true;

        userPreferences.dontAttachStream = false; // according to situation
        userPreferences.dontGetRemoteStream = false;  // according to situation


        //Only 1 connection peer user
        if (RTCConnection.getAllParticipants().length >= 1) return null;


        console.log("New call");

        //Accepting now in video_call
        newCallCB(participantId,userPreferences);




    };

Is there any workaround to make it work with the current RTCMulti version?

**Comment by muaz-khan** [comment]
Please check this demo:

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/One-to-One.html

**Comment by dnish** [comment]
@muaz-khan This demo doesn't show any "Accept / Reject" dialogue. It only limits the connections to 1 call, but in our application we are showing a dialogue to the receiver while the creator sees a "Waiting for answer" dialogue.

**Comment by dnish** [comment]
Closed, we had the function within onstream event and now checking for remote streams and ignoring all local data, so we get the functionality back.

**Comment by muaz-khan** [comment]
You can use this alternative method as well:

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/docs/api.md#setcustomsocketevent

```javascript
connection.connectSocket(function() {
    connection.instantChatId = connection.sessionid + '-chat';
    connection.setCustomSocketEvent(connection.instantChatId);
    connection.socket.on(connection.instantChatId, function(message) {
        if (message.join === true) {
            if (window.confirm(message.extra.fullName + ' wanna join your room. Do you accept?')) {
                connection.socket.emit(connection.instantChatId, {
                    accepted: true,
                    roomid: connection.sessionid
                });
            } else {
                connection.socket.emit(connection.instantChatId, {
                    rejected: true,
                    roomid: connection.sessionid
                });
            }
        }

        if (message.accepted === true) {
            connection.join(message.roomid);
        }

        if (message.rejected === true) {
            alert('You can NOT join this room: ' + message.roomid);
        }
    });
});

btnJoinRoom.onclick = function() {
    connection.socket.emit(connection.instantChatId, {
        join: true,
        userid: connection.userid,
        extra: connection.extra
    });
};
```
