### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by mantaplatte** [muaz-khan/RTCMultiConnection#288]
Hey, 
i get this error when i try to open a connection:
socket.io.js:2 GET https://rtcmulticonnection.herokuapp.com/socket.io/1/?userid=patorg-broadca…t-demo&socketCustomEvent=RTCMultiConnection-Custom-Message&t=1478842816086 400 (Bad Request)
Do you know a solution?
Thanks:)

**Comment by muaz-khan** [comment]
Ref: http://stackoverflow.com/a/40508213/552182

Please check latest release: https://github.com/muaz-khan/RTCMultiConnection/releases/tag/3.4.2

Latest release requires **latest** `socket.io.js`:

```html
<script src="https://rtcmulticonnection.herokuapp.com/dist/RTCMultiConnection.min.js"></script>
<script src="https://rtcmulticonnection.herokuapp.com/socket.io/socket.io.js"></script>
```

> Simply use/replace above two files and it will fix the issue.

Hints:

1. Do NOT use `rmc.min.js`. Use `/dist/RTCMultiConnection.min.js` instead.
2. Do NOT use `socket.io.js` from CDN. Use `/socket.io/socket.io.js` instead.

**Comment by mantaplatte** [comment]
That doesn't work for me, i used them already:
<script src="https://rtcmulticonnection.herokuapp.com/socket.io/socket.io.js"></script>
		<script src="https://rtcmulticonnection.herokuapp.com/dist/RTCMultiConnection.min.js"></script>
		<script src="rmc3.min.js"></script>
		<script src="https://cdn.webrtc-experiment.com:443/getScreenId.js"></script>
		<script src="https://cdn.webrtc-experiment.com:443/socket.io.js"></script>
		<script src="https://cdn.jsdelivr.net/vue/1.0.26/vue.min.js"></script>
		<script src="globals.js"></script>
		<script src="https://cdn.webrtc-experiment.com/DetectRTC.js"> </script>
        <script src="https://cdn.webrtc-experiment.com/screenshot.js"></script>
        <script src="https://cdn.webrtc-experiment.com/gumadapter.js"></script>
        <script src="https://cdn.webrtc-experiment.com/getMediaElement.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/vue-resource/1.0.3/vue-resource.min.js"></script>

**Comment by mantaplatte** [comment]
And also i use that in my js:
connection.socketURL = 'https://rtcmulticonnection.herokuapp.com:443/';

**Comment by mantaplatte** [comment]
Thank you :)
