### ISSUE TITLE
IOS audio volume

### ISSUE THREAD

**Issue by mado1987** [muaz-khan/RTCMultiConnection#295]
Hi Muaz. Thanks for your work!! I have the following issue : On the Android App, the sounds is hearing ok, loud,in the speakers, but for the IOS, the sound is hearing very low, in the earpiece
. How can i enable it by default to use the speakers? Thank you again!

**Comment by vahid263** [comment]
I have the same problem in IOS, Did you solve your problem?

**Comment by mado1987** [comment]
@vahid263 yes, use   
cordova.plugins.iosrtc.selectAudioOutput('speaker');

**Comment by thanhnt255** [comment]
@mado1987  please help me
I have same problem in iOS, I try your solution , but still not work, can you tell me : where write your code?

**Comment by Sarmastt** [comment]
Hi, check my answer on issuse: [Low volume in iphone #395](https://github.com/muaz-khan/RTCMultiConnection/issues/395)
