### ISSUE TITLE
RTCPeerConnection.getLocalStreams/getRemoteStreams are deprecated. Use RTCPeerConnection.getSenders/getReceivers instead.

### ISSUE THREAD

**Issue by TheOddler** [muaz-khan/RTCMultiConnection#307]
I get the following error when running this library:

RTCPeerConnection.getLocalStreams/getRemoteStreams are deprecated. Use RTCPeerConnection.getSenders/getReceivers instead.

(Line 4015 in the non-minified file)

It doesn't seem to be a problem for now, as everything seems to work fine, but thought I might make someone aware of this. I'm not confident enough to change it myself, though I think it would be a simple case of changing the used methods, but I'm not sure so perhaps someone more familiar with WebRTC and/or RTCMultiConnection should take a look at it.

**Comment by muaz-khan** [comment]
Currently only Firefox supports this feature. (`getSenders`)

We already have the implementation which is `disabled` currently.

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/RTCPeerConnection.js#L115-L125

**Comment by TheOddler** [comment]
That's great! Already way ahead of me. So since it's a known thing, I'll close this issue.
