### ISSUE TITLE
Media server

### ISSUE THREAD

**Issue by mado1987** [muaz-khan/RTCMultiConnection#311]
Thanks Muad for your work/help. RTCMultiConnection can be used with a media server? I mean something like a  person ( A ) sends the stream to media server, and then all other users take it from there, and not using peer to peer like Scalable Broadcast, so i can broadcast to a large number of users . Do you know any open source media server ? Thanks again!

**Comment by muaz-khan** [comment]
Nope. RTCMultiConnection merely targets JavaScript implementation inside the browsers.

RTCMultiConnection doesn't has any C++ implementation; it **doesn't** even support any media servers.

**Comment by mado1987** [comment]
Thanks!
