### ISSUE TITLE
Turn Server

### ISSUE THREAD

**Issue by mado1987** [muaz-khan/RTCMultiConnection#313]
Hi again Muaz. It's happening something strange. I have my own stun/turn server and I've forced the connection to use only the turn candidates  like this :  
connection.candidates = {
                        turn:    true,
                        host:    false,
                        stun:    false,
                    };
                    var iceServers = [];
                    iceServers.push({
                        urls: 'turn:myturnip:3478',
                        credential: '123',
                        username: '123'
                    });
connection.iceServers = iceServers;

Sometimes everything is ok, and  i get these logs 
![success](https://cloud.githubusercontent.com/assets/21129458/21721485/49b76452-d431-11e6-8bca-6160b729cf27.png)

And in the remote sdp i see :

a=candidate:3863262913 1 udp 33562367 10.10.0.110 49585 typ relay raddr 0.0.0.0 rport 0 generation 0 ufrag g+lOf77l9RGAWoJS

But sometimes, I get ice failed , and in the logs i can't see the remote candidate. It's like the broadcaster  is not connected to the turn server . The logs look like this 
![error](https://cloud.githubusercontent.com/assets/21129458/21721616/c27027c6-d431-11e6-850c-6bf9cd7dd587.png)
And there is nothing about the ip in the remote sdp

When does the broadcaster connects to the turn server? After i start the streaming, or after the first user joins? Thanks again!

**Comment by muaz-khan** [comment]
RTCPeerConnection is initiated for each participant as soon as he joins the moderator (room owner or initiator).

You can try this:

```javascript
// make sure that ice-candidates are included in the SDP
connection.trickleIce = false;

// as soon as RTCMultiConnection calls "peer.setLocalDescription"
connection.onSettingLocalDescription = function(peer) {
    var sdp = peer.localDescription.sdp; // get the SDP

    // check for relay or srflx pairs
    if (sdp.indexOf('typ relay') == -1) {
        // seems no relay candidates
        setTimeout(function() {
            // renegotiate or close & rejoin
            connection.renegotiate(peer.userid);
        }, 2000);
    }
};
```

**Comment by mado1987** [comment]
Thanks for your response. Now, with tricleIce = false, i see that the initator is connecting using host and is ignoring the candidates option. 
![screenshot from 2017-01-06 19-06-44](https://cloud.githubusercontent.com/assets/21129458/21726018/8b024276-d443-11e6-924a-0a45d261b64d.png)

**Comment by mado1987** [comment]
So..The problem is that sometimes i get no relay candidates from the initiator. I get only the host candidates. Like this:
RTCIceCandidate {candidate: "candidate:133161823 1 udp 2113937151 192.168.43.14…2819 typ host generation 0 ufrag yEmiQkmOXjrJHLYc", sdpMid: "video", sdpMLineIndex: 1}
Which may be the problem for not getting the relay candidates?

**Comment by mado1987** [comment]
Solved. The prooblem was the Crosswalk version. In the version 21, there is a bug and is not always gathering all candidates. Updated to 22 and everything is ok.Thanks Muaz for your help!!
