### ISSUE TITLE
Error mediaElement.play() on Chrome Android

### ISSUE THREAD

**Issue by SalvatoreAD** [muaz-khan/RTCMultiConnection#319]
Hi, I use this lib on mobile and I found this error:

> Uncaught (in promise) DOMException: play() can only be initiated by a user gesture. RTCMultiConnection.js:1080

Can you help me?

**Comment by Patrick-Vogt** [comment]
Some autoplay-features has been disabled on newer versions of Android...

**Comment by muaz-khan** [comment]
@SalvatoreAD Please try this demo on Android/iOS:

* http://webrtcweb.com/cordova-apps/video-conferencing/

**Comment by SalvatoreAD** [comment]
I checked, and he's right @Patrick-Vogt , because it seems that it needs a gesture to work. However it does not affect the proper functioning of the system. thanks for the answers @muaz-khan.
