### ISSUE TITLE
How to update configuration when stream is running?

### ISSUE THREAD

**Issue by Cylix** [muaz-khan/RTCMultiConnection#32]
Hi,

I'm currently facing an issue with the RTCMultiConnection library.
I'd like to update a connection configuration (for example, changing video stream resolution).

For example, I start a new video & audio stream:

```coffee
@stream = new RTCMultiConnection(@stream_id)

@stream.isInitiator = true

@stream.open
	session:
		audio: true
		video: true
```

Then, I want to allow user to change his video stream resolution.
So, after a user interaction I change the resolution:

```coffee
@stream.media.min someVal, someVal
@stream.media.max someVal, someVal
```

Unfortunately, the modifications are not applied: they must be made before opening the connection in order to be effective.

I've found a `refresh` function, but it looks like to behave more like a `reset` one.
When I try do make a `@stream.refresh()`, it just stops the stream and I need to reopen a new connection.

So, my question is: is it possible to make changes on the connection configuration (like muting sound or video, changing resolution, changing camera device, ...) without having to reopen a new one with the new configuration?

**Comment by muaz-khan** [comment]
It isn't yet possible to **switch between resolutions without renegotiating peers**. _However Firefox team shown interest to bring this feature soon._

Chrome requires a separate MediaStream instance to be captured with NEW configurations, and then both peers need to be "renegotiated" to make sure new RTP ports are applied.

RTCMultiConnection is having following methods that auto-performs renegotiation:

1. [addStream](http://www.rtcmulticonnection.org/docs/addStream/)
2. [removeStream](http://www.rtcmulticonnection.org/docs/removeStream/)
3. [switchStream](http://www.rtcmulticonnection.org/docs#switchStream)
4. [renegotiate](http://www.rtcmulticonnection.org/docs/renegotiate/)
5. [drop](http://www.rtcmulticonnection.org/docs/drop/)
6. [hold](http://www.rtcmulticonnection.org/docs#hold)
7. etc.

```javascript
var videoConstraints = {
    mandatory: {
        maxWidth: 1920,
        maxHeight: 1080
    },
    optional: []
};

connection.mediaConstraints = {
    video: videoConstraints,
    audio: true
};

// It'll capture a NEW stream with modified resolutions
// it'll also quickly renegotiate peers among all connected users
connection.addStream({
    video: true,
    audio: true
});
```

You can even remove/stop existing stream:

```javascript
connection.streams.selectFirst({ local: true }).stop();

// or
connection.removeStream({ local: true });

// or
connection.streams.stop('local');

// or
connection.removeStream('stream-id');
connection.addStream({ audio: true, video: true });
```

[`attachExternalStream`](http://www.rtcmulticonnection.org/docs/#attachExternalStream) is useful only when doing initial handshake.

[`connection.refresh`](http://www.rtcmulticonnection.org/docs/refresh/) isn't meant to renegotiate peers. It merely sets defaults for **local-peer-only**. E.g. it can stop all streams, remove all connected peers, close all sockets etc.

**Comment by Cylix** [comment]
@muaz-khan Thank you for your answer!
