### ISSUE TITLE
Echo comes after UnMute Event

### ISSUE THREAD

**Issue by danishnazir** [muaz-khan/RTCMultiConnection#323]
Hi Muaz Khan i hope that you are doing great!!
I have a small query i am using your Video Conferencing Sample which uses RTC multi connection v3 Now i have implemnted the mute and unmute functionality given as
onMuted: function(type) {

if(type=="audio")
{ alert(event.type);
connection.streamEvents[event.streamid].stream.mute('audio');

}
else if(type=="video")
{
connection.streamEvents[event.streamid].stream.mute('video');

}

},
onUnMuted: function(type) {
if(type=="audio")
{alert(event.type);
connection.streamEvents[event.streamid].stream.unmute('audio');

}
else if(type=="video")
{
connection.streamEvents[event.streamid].stream.unmute('video');

}

}
Now the problem is that when i mute the audio it works fine on both the local and remote stream but when i unmute it then a large echo come out and i can hear my voice as a double voice. I think that there is a bug in my function can you please take a look 
Regards

**Comment by wizzed** [comment]
I have the exact same problem, only when i do the following:

connection.attachStreams[0].mute();
connection.attachStreams[0].unmute();

echos can be heard from the same device. (Only android). I tried on the demo and it has the same problem. (https://rtcmulticonnection.herokuapp.com/demos/Audio-Conferencing.html)

**Comment by wizzed** [comment]
The problem is when you do unmute("audio"), it will echo on your local device.

I've tried doing just unmute(), and it works. Well, if you are trying to mute either audio or video only, then this solution wouldn't help you at all.

**Comment by furkan6116** [comment]
add "playsinline" to local video element

**Comment by afaq2327** [comment]
just use unmute() without audio attribute when you are unmuting the audio. works fine for me.

**Comment by furkan6116** [comment]
> just use unmute() without audio attribute when you are unmuting the audio. works fine for me.

little notice. it also unmutes webcam

**Comment by furkan6116** [comment]
> just use unmute() without audio attribute when you are unmuting the audio. works fine for me.

it doesnt works my friend. ı tried that solution. only add "playsinline" to local video element. that is the quickest and best solution
