### ISSUE TITLE
auto Rejoin and keeps room opened even if initiator leave (RTCMulticonnection v3)

### ISSUE THREAD

**Issue by SalvatoreAD** [muaz-khan/RTCMultiConnection#328]
hello, I would like to know how do you do the rejoin of a person who is out of the room because of the poor Internet line.
I try https://www.webrtc-experiment.com/RTCMultiConnection/session-reinitiation.html but not work on v3

**Comment by muaz-khan** [comment]
Did you try this?

* https://rtcmulticonnection.herokuapp.com/demos/Disconnect+Rejoin.html

**Comment by SalvatoreAD** [comment]
Yes but if initiator leave , he can't rejoin.

**Comment by SalvatoreAD** [comment]
I try this issue https://github.com/muaz-khan/RTCMultiConnection/issues/10 but not work on v3

**Comment by muaz-khan** [comment]
If initiator comes later, he will rejoin rather than reopen.

Did you try to click "Join" button for initiator (on his second attempt to join same room)?

**Comment by SalvatoreAD** [comment]
I try with initiator but other people can't see it. Can you give me an example?

**Comment by vrajroham** [comment]
@SalvatoreAD Same issue here! Did you got solution?
If the initiator leaves a session where there are other participants , then initiator cannot return, and in fact nobody else can join the session.

It seems that room get's closed and if Initiator returns then another room is created with same name and if any participant tries to refresh then it automatically connects to initiator. 

@muaz-khan any solution?

**Comment by nthung82** [comment]
My fixing:

        // temporarily disabled
        if (!!listOfUsers[params.userid]) {
            params.dontUpdateUserId = true;

            var useridAlreadyTaken = params.userid;
            params.userid = 'My_Room';//(Math.random() * 1000).toString().replace('.', '');
			console.log('params.userid'+params.userid+"/"+useridAlreadyTaken+"//"+listOfUsers[params.userid]);
            socket.emit('userid-already-taken', useridAlreadyTaken, params.userid);
        }

**Comment by duahimanshu100** [comment]
Any solutions to this yet?

**Comment by tobiasBora** [comment]
There is an issue, `/demos/Disconnect+Rejoin.html` 404 now. Any solution?

**Comment by GovindCS** [comment]
###
