### ISSUE TITLE
Error send some files in single chat Demos

### ISSUE THREAD

**Issue by ruben0909** [muaz-khan/RTCMultiConnection#329]
Hi

When I send some files the demo fail, for example this file:
https://administracionelectronica.gob.es/pae_Home/dms/pae_Home/documentos/OBSAE/Informes/Informe_IRIA_2014.pdf

In some demos work and not in others, that thing happen to me with other files like audio, pictures or other pdfs.

**Not Work**
TextChat+FileSharing
Audio+Video+File+TextChat

**Work**
FileSharing
WebRTC Scalable File Sharing

Thank you

**Comment by muaz-khan** [comment]
All demos worked for me; tested up to 130 MB files including your file.

You can reduce [chunkSize](http://www.rtcmulticonnection.org/docs/chunkSize/) as well.

```javascript
connection.chunkSize = 10 * 1000; // 10 KB
```

**Comment by ruben0909** [comment]
I'm sorry I'm late, 
It was my fault, I was trying in Chrome with one normal session, and other in Private. 
When I try PC+Mobile everythings are OK.
Thank you, so much
