### ISSUE TITLE
Add camera to existing connection between two user 

### ISSUE THREAD

**Issue by Nitrick** [muaz-khan/RTCMultiConnection#330]
Hi

I am facing this error when i add camera to existing connection, here is code by which i am connecting or adding the additional camera to the connection 
`  if (connection.mediaConstraints.video.optional.length && connection.attachStreams.length) {
                                            connection.mediaConstraints.video.optional[0].sourceId = videoSourceId;
                                            var stream = event.stream
                                            connection.removeStream({ audio: true });
                                            connection.addStream({ audio: true, video: true })
                                            videoId = this.id;
     }`
and this error occurs when i am trying this
![error](https://cloud.githubusercontent.com/assets/17708478/22828726/e62e2e48-efc4-11e6-8471-01ac08d23bf1.PNG)

and by searching for this error i have tried every things but got no solution

**Comment by muaz-khan** [comment]
Please try this:

```javascript
if (DetectRTC.browser.name === 'FIrefox') {
    connection.mediaConstraints.video = {
        deviceId: videoSourceId
    };
} else {
    connection.mediaConstraints = {
        audio: connection.mediaConstraints.audio, // true or false
        video: {
            mandatory: {},
            optional: [{
                sourceId: videoSourceId
            }]
        }
    };
}

connection.addStream({
    audio: true,
    video: true
});
```

**Comment by Nitrick** [comment]
Thank you @muaz-khan  for giving this solution it worked for me.
