### ISSUE TITLE
v2 Broadcast-Multiple-Cameras not working on windows

### ISSUE THREAD

**Issue by Anupammallick** [muaz-khan/RTCMultiConnection#331]
Hi khan,
I have problem on Broadcast-Multiple-Cameras. v2 Broadcast-Multiple-Cameras not working on windows, Broadcast button always disabled and camera name dose not fetch. but its working fine on mac. pls replay.
![capture](https://cloud.githubusercontent.com/assets/24692820/22852284/d6e04f4e-f05e-11e6-8c32-e92a83f4c40d.PNG)

**Comment by muaz-khan** [comment]
Please check this page: https://www.webrtc-experiment.com/DetectRTC/

Make sure that DetectRTC can display list of all your cameras.

I just tested the demo, and it is working for me:

![screen shot 2017-02-11 at 1 07 38 pm](https://cloud.githubusercontent.com/assets/477092/22852318/48951844-f05b-11e6-8713-4a9a26680be3.png)

**Comment by Anupammallick** [comment]
Thank you for replay, i check this page: https://www.webrtc-experiment.com/DetectRTC/
my all camera list are fetch on this page: https://www.webrtc-experiment.com/DetectRTC/
![capture1](https://cloud.githubusercontent.com/assets/24692820/22852406/9f6afab6-f061-11e6-9734-05f488964250.PNG)
But this page https://www.webrtc-experiment.com/RTCMultiConnection/Broadcast-Multiple-Cameras.html not working , and i try also on local server result is same. this problem is occurred the previous day. but past its working fine same as local/your site.

**Comment by muaz-khan** [comment]
Just updated the demo. Please test again.

**Comment by Anupammallick** [comment]
Thank Mr. khan

**Comment by Anupammallick** [comment]
Hi Mr. khan, 
There is also problem on camera selection, pls check it.
