### ISSUE TITLE
Cannot join an audio conference

### ISSUE THREAD

**Issue by MasteryMatt** [muaz-khan/RTCMultiConnection#339]
![image](https://cloud.githubusercontent.com/assets/25163595/23241266/1789ba88-f9ad-11e6-936f-d8a04d88a26a.png)
****

How to solve this ?

**Comment by jersobh** [comment]
It took me some time to figure this out, but if you check your that url, there's a missing letter (the first one), and maybe the last one also. IDK also why does this happn, but at least I was able to solve it.

**Comment by muaz-khan** [comment]
[`socketURL`](http://www.rtcmulticonnection.org/docs/socketURL/) MUST look like this:

```javascript
connection.socketURL = 'https://separateDomain.com:443/';
```

I included port `443` as well to make sure it always uses valid port.
