### ISSUE TITLE
Websocket vs SocketIO

### ISSUE THREAD

**Issue by gmbad** [muaz-khan/RTCMultiConnection#343]
Hello Muaz,

What's the difference in using websocket or socketio? 
What is the best?

Tks,

Gabriel

**Comment by muaz-khan** [comment]
> ### Socket.IO uses WebSockets when it can. (Otherwises fallback to possible options e.g. xhr/json polling etc.)
> 
> ...... I would avoid using WebSockets directly unless you are very familiar with what environments they don't work and you are capable of working around those limitations.

via: http://stackoverflow.com/a/10112562/552182
