### ISSUE TITLE
Not getting Audio in all Demos 

### ISSUE THREAD

**Issue by VeiderCode** [muaz-khan/RTCMultiConnection#348]
i followed this simple demo nad worked but today i tested again and im not getting audio, also video works only in firefox but in chrome i get this getUserMedia() no longer works on insecure origins.

how can i fix this?

<script src="https://rtcmulticonnection.herokuapp.com/dist/RTCMultiConnection.min.js"></script>
<script src="https://rtcmulticonnection.herokuapp.com/socket.io/socket.io.js"></script>

<button id="btn-open-room">Open Room</button>
<button id="btn-join-room">Join Room</button><hr>

var connection = new RTCMultiConnection();

// this line is VERY_important
connection.socketURL = 'https://rtcmulticonnection.herokuapp.com:443/';

// all below lines are optional; however recommended.

connection.session = {
    audio: true,
    video: true
};

connection.sdpConstraints.mandatory = {
    OfferToReceiveAudio: true,
    OfferToReceiveVideo: true
};

connection.onstream = function(event) {
    document.body.appendChild( event.mediaElement );
};

Last step is, add click-handlers for above two buttons:

var predefinedRoomId = 'YOUR_Name';

document.getElementById('btn-open-room').onclick = function() {
    this.disabled = true;
    connection.open( predefinedRoomId );
};

document.getElementById('btn-join-room').onclick = function() {
    this.disabled = true;
    connection.join( predefinedRoomId );
};

**Comment by muaz-khan** [comment]
Please try this demo, and let me know if you're able to record your microphone:

* https://www.webrtc-experiment.com/RecordRTC/

**Comment by VeiderCode** [comment]
now its working fine bro, dont know what was the problem, but now its all fine, thanks for this you are awesome ImI
