### ISSUE TITLE
screen Broadcast from firefox not visible  in chrome

### ISSUE THREAD

**Issue by manurajmr1** [muaz-khan/RTCMultiConnection#349]
https://rtcmulticonnection.herokuapp.com/demos/Audio-Video-Screen.html

Check this URL 

Screen Broadcast from firefox not visible  in chrome.
But chrome to firefox is working fine.

Can you please look on it

**Comment by muaz-khan** [comment]
Firefox maybe unable to send multiple parallel video streams.

Please try this demo instead:

* https://rtcmulticonnection.herokuapp.com/demos/Screen-Sharing.html

This one may work.
