### ISSUE TITLE
Mixed Content: The page at 'https://' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://xxx/websocket'. This request has been blocked; this endpoint must be available over WSS.

### ISSUE THREAD

**Issue by svillegasc** [muaz-khan/RTCMultiConnection#350]
I have a problem, Help me

Mixed Content: The page at 'https://expzero.com/todolist/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://54.88.59.233:3000/websocket'. This request has been blocked; this endpoint must be available over WSS.

I have a proxy that has the SSL certificate, the proxy sends the requests to an application and that application connects to a backend that has the address shown in the error 'ws: //54.88.59.233: 3000 / websocket'.

**Comment by muaz-khan** [comment]
> ### Please run websockets server on port 443 or any other SSL port.

Demo websocket implementation:

* https://github.com/muaz-khan/WebRTC-Experiment/blob/master/websocket-over-nodejs/ssl.js
