### ISSUE TITLE
How to get the file sharing event and write my own code. Right now chat event is only available and couldnt find event for file sharing

### ISSUE THREAD

**Issue by manurajmr1** [muaz-khan/RTCMultiConnection#351]
How to get the file sharing event and write my own code. Right now only chat event is only available couldnt find event for file sharing

how to remove the iframe appended when a user shares a video/ other files to others. Currently iframe along with  download link is appended to div, i want only a download link to be displayed on the screen is it possible. Can you please help

**Comment by muaz-khan** [comment]
Here is the file that is doing file sharing job; download and reuse in your HTML:

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/FileProgressBarHandler.js

Copy-paste in your HTML or simply link the script:

```html
<script src="/dev/FileProgressBarHandler.js"></script> <!-- first step; it is important -->
<script>
var connection = new RTCMultiConnection();

// second step; you need to add this line in your HTML page
FileProgressBarHandler.handle(connection); // ----- <<<<<<<<<<<
</script>
```

There are three events in the above file:

1. [onFileStart](http://www.rtcmulticonnection.org/docs/onFileStart)
2. [onFileProgress](http://www.rtcmulticonnection.org/docs/onFileProgress)
3. [onFileEnd](http://www.rtcmulticonnection.org/docs/onFileEnd)

You need to modify only the `onFileEnd` event. Here is how to modify it inside `/dev/FileProgressBarHandler.js`:

```javascript
connection.onFileEnd = function(file) {
    var helper = progressHelper[file.uuid];
    if (!helper) {
        console.error('No such progress-helper element exist.', file);
        return;
    }

    if (file.remoteUserId) {
        helper = progressHelper[file.uuid][file.remoteUserId];
        if (!helper) {
            return;
        }
    }

    var div = helper.div;
    if (file.type.indexOf('image') != -1) {
        div.innerHTML = '<a href="' + file.url + '" download="' + file.name + '">Download <strong style="color:red;">' + file.name + '</strong> </a><br /><img src="' + file.url + '" title="' + file.name + '" style="max-width: 80%;">';
    } else if (file.type.indexOf('video') != -1) {
        div.innerHTML = '<a href="' + file.url + '" download="' + file.name + '">Download <strong style="color:red;">' + file.name + '</strong> </a><br /><video controls src="' + file.url + '" title="' + file.name + '" style="max-width: 80%;"></video>';
    } else if (file.type.indexOf('audio') != -1) {
        div.innerHTML = '<a href="' + file.url + '" download="' + file.name + '">Download <strong style="color:red;">' + file.name + '</strong> </a><br /><audio controls src="' + file.url + '" title="' + file.name + '"></audio>';
    } else {
        div.innerHTML = '<a href="' + file.url + '" download="' + file.name + '">Download <strong style="color:red;">' + file.name + '</strong> </a>';
    }
};
```

You can see that I'm comparing `file.type` to check the incoming file type; whether it is an image, a video or an audio file.

I also removed `<iframe>`. You can use `<iframe>`, `<object>` or `<embed>` elements to display PDF+similar files.

**Comment by manurajmr1** [comment]
Thank you. :+1:
