### ISSUE TITLE
I want to run the demos from file, no server

### ISSUE THREAD

**Issue by fruiz500** [muaz-khan/RTCMultiConnection#359]
Is this even possible in version 3? It was in version 2. I only had to copy a few files locally, including firebase.js and geticeservers.html, and it used to work. But version 3 doesn't.
I copied one of your demos to a local file, and as soon as I get on the console: 
       `socket.io is connected at:  file:///`
The rest is a series of errors of this kind:
       `GET http://file/socket.io/?userid= etc. etc. etc.`
Which tells me that the location isn't getting transmitted right.
Any way to fix this? I'd really love to use something similar to your demos to connect two users, but I don't want to involve any server (other than perhaps firebase.io or socket.io), including one I control.

Thanks!

**Comment by muaz-khan** [comment]
v3 has following demos:

1. [SSE over PHP](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/SSEConnection.html)
2. [Firebase](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/Firebase-Demo.html) - **Recommended**
3. [PubNub](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/PubNub-Demo.html)

Enable this command-line flag: `--allow-file-access-from-files`

And try any of the above demos; and they must work.

PS. Please close this issue if solved.
