### ISSUE TITLE
Better way to get all rooms from server?

### ISSUE THREAD

**Issue by COM8** [muaz-khan/RTCMultiConnection#362]
Hi,
is there a better way to get all currently active rooms from the Server?
Until now I was using:
```java
connection.getPublicModerators(function(array) {
    console.log(array.length + ' rooms found.');
    ...
}
```
in combination with:
``` java
connection.openOrJoin(roomid.value || connection.token(), function() {
	if(!connection.isInitiator) {
		return; // this line is optional
	}
		connection.becomePublicModerator();
});
```

It's not working all the time for me and the client who created the room can't see the room either (once it is working :-D).

**Comment by muaz-khan** [comment]
Just tested `video conferencing` (and same technique applies to all demos). Paste following code for the session initiator:

```javascript
connection.open('roooooom', true); // check the second paramter
```

Use following code for participants:

```javascript
connection.getPublicModerators(function(array) {
    array.forEach(function(initiator) {
        connection.join(initiator.userid); // initiator.extra or initiator.userid
    });
});
```

`initiator.userid` is the room-id.

Do not use [`openOrJoin`](http://www.rtcmulticonnection.org/docs/openOrJoin/). Use [`checkPresence`](http://www.rtcmulticonnection.org/docs/checkPresence/) instead:

```javascript
connection.checkPresence('room-id', function(isRoomExists, roomid) {
    if (isRoomExists === false) {
        connection.open(roomid, true); // check the second paramter
    }
});
```
