### ISSUE TITLE
Get all clients in all rooms

### ISSUE THREAD

**Issue by COM8** [muaz-khan/RTCMultiConnection#363]
Hi again,
Is there a way to get all clients in all rooms?

**Comment by muaz-khan** [comment]
Please check this:

* https://rtcmulticonnection.herokuapp.com/demos/getPublicModerators.html

All rooms public rooms will be visible on the above page.

To test it privately, either change `socketURL` or `socketMessageEvent`:

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/getPublicModerators.html#L119

```javascript
connection.socketMessageEvent = 'your-private-demo';
```

PS. Next conversation will happen here: #362
