### ISSUE TITLE
how to render mediaElement on react element

### ISSUE THREAD

**Issue by karamata** [muaz-khan/RTCMultiConnection#368]
hi all,
on connection.onstream method, I have get mediaElement but I don't how to render that object on react js, can you help me?

**Comment by muaz-khan** [comment]
Please take this repository as a demo/example:

* https://github.com/szwang/recordrtc-react

It is capturing camera, and appending to a DIV whose `id` is "container":

* https://github.com/szwang/recordrtc-react/blob/master/src/app.js#L5

You should use above code inside the `onstream` event listener:

* http://www.rtcmulticonnection.org/docs/onstream/

**Comment by barakjobs** [comment]
do you have react code for Video + Screen Sharing using RTCMultiConnection

**Comment by mansur1020** [comment]
please share react based code  using RTCMultiConnection
