### ISSUE TITLE
Stun server: stun.l.google.com vs Stuntman vs XirSys

### ISSUE THREAD

**Issue by gmbad** [muaz-khan/RTCMultiConnection#377]
Good afternoon, Muaz,

I think of using google public stun server. (stun:stun.l.google.com:19302)

```
connection.getExternalIceServers = false;
connection.iceServers = [];
connection.iceServers.push({ urls: 'stun:stun.l.google.com:19302' });
```

What would be the advantage in paying for using XirSys or installing StuntMan on my server?

Thank you very much for your contribution.

**Comment by muaz-khan** [comment]
v3 is using **its own** (CoTURN+reStund) servers (**no third party**):

* [dev/IceServersHandler.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/IceServersHandler.js)

I donno much about xirsys so I can't comment. Sorry.

_PS. v3 don't have 3rd-party ICE options anymore (except Google STUN). However you an always add in your HTML files._

**Comment by gmbad** [comment]
Thank you @muaz-khan!
