### ISSUE TITLE
Event listener for files

### ISSUE THREAD

**Issue by vrajroham** [muaz-khan/RTCMultiConnection#379]
I would like to know is there any listener for files sharing? like :file_folder:  `onmessage` for chat messages.

Don't know it's available or not but can suggest enhancement like `onFileRecieved` etc. 

Buffered reader will broadcast this event on completely receiving  the file.

Thanks

**Comment by vrajroham** [comment]
Hey closing this issue. There are already multiple methods available related to file sharing.

But they need to be documented in API Reference.

For this issue solution was as above,

    // www.RTCMultiConnection.org/docs/onFileEnd/
    connection.onFileEnd = function (file) {
        //Your stuff
    }

Although [RTCMulticonnection.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dist/RTCMultiConnection.js) itself is the great documentation. Implementation of `onFileEnd` can be found [here on line #L390](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dist/RTCMultiConnection.js#L390) of [RTCMulticonnection.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dist/RTCMultiConnection.js)

**Comment by muaz-khan** [comment]
All three API (onFileStart, onFileProgress and onFileEnd) are documented for long time:

1. http://www.rtcmulticonnection.org/docs/onFileStart/
2. http://www.rtcmulticonnection.org/docs/onFileProgress/
3. http://www.rtcmulticonnection.org/docs/onFileEnd/

and you can search them on "docs" page:

* http://www.rtcmulticonnection.org/docs/

Version 3 created a reusable file as well:

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/FileProgressBarHandler.js

E.g.

```html
<script src="/dist/RTCMultiConnection.js"></script>

<!-- your modified file goes here -->
<script src="/dev/FileProgressBarHandler.js"></script>
<script>
var connection = new RTCMultiConnection();

// your modified file handler
FileProgressBarHandler.handle(connection); // dev/FileProgressBarHandler.js will be used here
</script>
```

**Comment by vrajroham** [comment]
Yes later I got that documentation. Thanks
