### ISSUE TITLE
Screen sharing not working with RTCMUlticonnection V3.0

### ISSUE THREAD

**Issue by prabhuashwin** [muaz-khan/RTCMultiConnection#38]
Hi,

I am trying to use screen sharing provided in RTCMUlticonnection V3.0 (Socket.IO over node.js) you have provided but i keep getting the below error. What the problem is i am not able to figure out. Please do have a look at the below error trace and let me know if you see anything amiss from my end.

onLocalMediaError NavigatorUserMediaErrorconstraintName: ""message: ""name: "InvalidStateError"__proto__: NavigatorUserMediaErrorMultiPeersHandler.js:272 MultiPeers.onLocalMediaError
RTCMultiConnection.js:812 NavigatorUserMediaErrorconstraintName: ""message: ""name: "InvalidStateError"__proto__: NavigatorUserMediaError
RTCMultiConnection.js:270 socket.io connection is opened.

I do have the chrome screen sharing extension installed on my machine and followed all the steps as mentioned in Screen-Capturing.js.

**Comment by muaz-khan** [comment]
Steps are explained in this repo:

* https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture

Simply deploy extension to Google App Store or enable developer mode and locate the extension directory. Here is [how to deploy?](https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture#how-to-publish-yourself)

**Comment by prabhuashwin** [comment]
We resolved the above issue by using getScreenId.js instead of Screen-Capturing.js. Now we are able to do screen sharing effortlessly.
