### ISSUE TITLE
Low volume in iphone

### ISSUE THREAD

**Issue by vikas0vanvi** [muaz-khan/RTCMultiConnection#395]
Even after using window.iOSDefaultAudioOutputDevice = 'speaker'; 
still gets very low volume

**Comment by Sarmastt** [comment]
Use below mention code in 'MainViewController.m'

` [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(didSessionRouteChange:) name:AVAudioSessionRouteChangeNotification object:nil];
`

and this one also, obviously :)

`- (void)didSessionRouteChange:(NSNotification *)notification
{
    NSDictionary *interuptionDict = notification.userInfo;
    NSInteger routeChangeReason = [[interuptionDict valueForKey:AVAudioSessionRouteChangeReasonKey] integerValue];
    
    switch (routeChangeReason) {
        case AVAudioSessionRouteChangeReasonCategoryChange: {
            // Set speaker as default route
            NSError* error;
            [[AVAudioSession sharedInstance] overrideOutputAudioPort:AVAudioSessionPortOverrideSpeaker error:&error];
        }
            break;
            
        default:
            break;
    }
}
`

**Comment by Psiloscop** [comment]
@syedzainulabideen cay you explain in details how to implement your fix? It doesn't even compiles.
