### ISSUE TITLE
ORTC support?

### ISSUE THREAD

**Issue by Ken2050** [muaz-khan/RTCMultiConnection#396]
Any plans for ORTC (Microsoft  Edge) support on RTCMultiConnection?  

Thanks!

**Comment by muaz-khan** [comment]
Next commit will support MS-Edge.

**Comment by Ken2050** [comment]
That's great news, Will I be able to connect MS-Edge & Chrome/FireFox in to the same room?

**Comment by muaz-khan** [comment]
I'm trying to integrate this:

* https://github.com/webrtc/adapter/blob/master/release/adapter.js

Hopefully (it seems that) it supports cross-browser connections (Edge-to-Chrome and vice versa).

**Comment by gmbad** [comment]
@muaz-khan Any news about this integration?

Tks

**Comment by itzurkarthi** [comment]
@muaz-khan Is there any update on this?

**Comment by muaz-khan** [comment]
@itzurkarthi RTCMultiConnection supports [adapter.js](https://webrtc.github.io/adapter/adapter-latest.js) which fixes this issue. Which means that now we support following browsers:
1. Microsoft **Edge** (this is ORTC and it is supported through adapter.js)
2. **Safari** 11+ (both on iOS and MacOSX)
3. **Firefox** (iOS excluded; all others are supported)
4. **Chrome** (iOS excluded; all others are supported)
5. **Opera**  (iOS excluded; all others are supported)

additionally electron+cordova+similar.
