### ISSUE TITLE
RTCmulticonnecions problema with my server socket io

### ISSUE THREAD

**Issue by RafaelSalomao1981** [muaz-khan/RTCMultiConnection#397]
Hi Friends,

I'm trying to implement RTCmulticonnection in my application however when I try to change the client socket to my socket server the web cam is not sent from one client to another.

Code application.

My server.js 

![image](https://cloud.githubusercontent.com/assets/28539765/25918339/766ec7fc-35a1-11e7-8a13-acfabc027c5c.png)

RTCmulticonnection

config.json 
![image](https://cloud.githubusercontent.com/assets/28539765/25918442/cf63231c-35a1-11e7-9e22-5f3d1c7cde5b.png)

server.js
![image](https://cloud.githubusercontent.com/assets/28539765/25918225/164e497e-35a1-11e7-9dd6-5561f9c858e1.png)

![image](https://cloud.githubusercontent.com/assets/28539765/25917368/2139d3c4-359e-11e7-9797-97f5e5475e34.png)

vhost nginx 

![image](https://cloud.githubusercontent.com/assets/28539765/25916742/24e32cd4-359c-11e7-9719-b6314a5c551d.png)

In my console i don't receive any error.

Open Room 
![image](https://cloud.githubusercontent.com/assets/28539765/25917475/936ca4c6-359e-11e7-9564-0b742b643b0f.png)

join Room
![image](https://cloud.githubusercontent.com/assets/28539765/25917541/d0ca039a-359e-11e7-9cc8-ffd56583c156.png)

My client page 
![image](https://cloud.githubusercontent.com/assets/28539765/25917650/28a727fa-359f-11e7-8b60-e8e10b359a6c.png)
![image](https://cloud.githubusercontent.com/assets/28539765/25917610/0a761d68-359f-11e7-8d41-7376ebd506e9.png)

The chat of my nodejs application works perfect with socket.  Only the camera is not shown. What can I have done wrong?

thank you for any help.

**Comment by muaz-khan** [comment]
Your server side socket.io implementation must match this (**transports must match**):

* [dev/SocketConnection.js#L42-L46](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/SocketConnection.js#L42-L46)

i.e. you must be using latest socket.io on server-end. Otherwise modify above file and recompile `RTCMultiConnection.js` using `grunt`.

**Comment by RafaelSalomao1981** [comment]
Thank you so much! It's work....
