### ISSUE TITLE
can v3 use ASP.NET SignalR

### ISSUE THREAD

**Issue by aazjcom** [muaz-khan/RTCMultiConnection#408]
i use meeting.js for Video conferencing now,but your Suggestions is RTCMultiConnection.js. so can v3 use ASP.NET SignalR?
what  is difference between [Video conferencing](https://www.webrtc-experiment.com/video-conferencing/#46860582531284955) and [meeting](https://www.webrtc-experiment.com/meeting/).

**Comment by avspeed** [comment]
if anyone is interested in a signalr example with v3  ping me

**Comment by pksorensen** [comment]
@avspeed Do you have post/demo anywhere ?

**Comment by Jhordan92** [comment]
@avspeed  How can it be done?

**Comment by muaz-khan** [comment]
SignalR demo: https://github.com/muaz-khan/RTCMultiConnection-SignalR
