### ISSUE TITLE
openOrJoin Failure - v3.4.4

### ISSUE THREAD

**Issue by deathlover** [muaz-khan/RTCMultiConnection#412]
openOrJoin function not working as expected.
RTCMultipleConnection.js - v3.4.4

Open and join are working separately 

Note: checkPresence not working as well.

**Comment by muaz-khan** [comment]
`openOrJoin` in this demo is working for me:

* https://rtcmulticonnection.herokuapp.com/demos/Video-Conferencing.html

`checkPresence` demo is also working for me:

* https://rtcmulticonnection.herokuapp.com/demos/checkPresence.html

Please reopen if this issue persists.
