### ISSUE TITLE
adapter.js

### ISSUE THREAD

**Issue by gmbad** [muaz-khan/RTCMultiConnection#413]
Hello Muaz!

Is using the adapter.js script before rtcmulticonnection.js is recommended?

Tks,

Gabriel

**Comment by muaz-khan** [comment]
RTCMultiConnection is not supporting `adapter.js` yet.

Please catch #396 for `adapter.js` support.

PS. Seems that it requires huge changes to support ORTC/Edge/Adapterjs, that's why #396 is still pending.

**Comment by vipinrajoria** [comment]
Hello muaz-khan,
Actually i am not able to show video with Mozilla but in chrome working properly.
