### ISSUE TITLE
How to disable `controls` of `video` tag?

### ISSUE THREAD

**Issue by tearsofphoenix** [muaz-khan/RTCMultiConnection#414]
in `RTCMultiConnection.js`:
```js
mediaElement.controls = true;
```
It always show controls on video tag, but I want to custom the control, how to ?

**Comment by tearsofphoenix** [comment]
I see https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/Audio-Video-Screen.html

**Comment by 2gen** [comment]
@tearsofphoenix How did you go about solving this? Your link doesn't work anymore and I am unable to find a demo title "audio-video-screen.html".
