### ISSUE TITLE
Firebase script not working

### ISSUE THREAD

**Issue by Lkrpsk** [muaz-khan/RTCMultiConnection#415]
Hi, We facing some script issue, please guide me.

Error: The Firebase database you're trying to use has exceeded its quota limit and has been temporarily disabled. See https://firebase.google.com/support/faq/#database-overquota for more information.

We using RTCMulticonnection version 2.2.

**Comment by Carmi333** [comment]
I have the same problem!
Help me please.

**Comment by taylsonmartinez** [comment]
i have the same problem!

Any solution ?

**Comment by datnguyenthang** [comment]
Should be change to websocket.

**Comment by muaz-khan** [comment]
## Fixed the CDN link.

BTW, you can always set your own firebase URL (in your HTML files):

```javascript
// https://webrtc.firebaseIO.com/
// https://rtcweb.firebaseIO.com/
// https://muazkh.firebaseIO.com/
// https://signaling.firebaseIO.com/

connection.resources.firebaseio = 'https://webrtc.firebaseIO.com/';
```

* http://www.rtcmulticonnection.org/docs/firebase/
