### ISSUE TITLE
Disable loading of filebufferReader.js?

### ISSUE THREAD

**Issue by boynet** [muaz-khan/RTCMultiConnection#42]
There is a lot of "magic" happening that can be very confusing.. I think that if some libary isn't included and we need it than trigger some error to let us know.. but dont auto fetch it for us..

for example right now its auto fetch filebufferReader for me without me ever using it from here: https://cdn.webrtc-experiment.com/FileBufferReader.js.

this is my simple js:
````
 var connection = new RTCMultiConnection();
connection.session = {
        audio: true,
        video: true,
        data:  true // only need to pass messages between clients no files
    };
connection.getExternalIceServers = false; //another unwanted magic
connection.connect();
````
any idea? thanks

**Comment by muaz-khan** [comment]
```javascript
// to disable loading the file
// define global function before using RTCMultiConnection
window.FileBufferReader = function() {};

var connection = new RTCMultiConnection();
```

You can even set different file-buffer-reader URI:

```javascript
connection.resources.FileBufferReader = 'NULL';

// or
connection.resources.FileBufferReader = '/dir/fbr.js';
```

**Comment by boynet** [comment]
thanks :+1:
