### ISSUE TITLE
Adapter.js

### ISSUE THREAD

**Issue by gmbad** [muaz-khan/RTCMultiConnection#436]
Hello Muaz,

any news about integration with adapter.js?

Tks,
Gabriel

**Comment by dnish** [comment]
@muaz-khan Is this really a good idea? Adapter.js is changing frequently, so there is no need to add it to this package. Users should be install & include it separately.
.

**Comment by muaz-khan** [comment]
Adapterjs is downloaded and included in the DEV directory; which means that their recent updates will not affect v3. (until we manually replace it in the DEV directory & recompile v3)

BTW, we **can make** adapterjs optional. So we will use our own implementation if adapterjs is missing in the demo files.
