### ISSUE TITLE
Sender gets the files hyperlink more than once if more than 2 peers connected in rtcmulticonnection-v3

### ISSUE THREAD

**Issue by Simhabharath** [muaz-khan/RTCMultiConnection#44]
Hi Muaz,
Tried executing the experiments in rtcmulticonnection-v3. Example "Audio+Video+TextChat+FileSharing.html" and "TextChat+FileSharing.html" in the latest commit the files shared by the sender is been shown twice for the sender if there are more than 2 peers connected.
How to avoid or rectify this issue. Please suggest

**Comment by muaz-khan** [comment]
This should happen only for the person who shares the file. It'll NEVER happen for the receivers.

Please check FileBufferReader.js relevant commit:

* https://github.com/muaz-khan/FileBufferReader/commit/10e8937dd7dccd0c8f3693f2187cd9aa247488c5

You can always override `onFileStart`, `onFileEnd` and `onFileProgress` events. Ref doc:

* http://www.rtcmulticonnection.org/docs/onFileStart/

Currently `onFileStart` or `onFileEnd` doesn't seems having any clue that let us know that current progress-bar is shown for sending or receiving the file. It can be added easily in FileBufferReader.

**Comment by Simhabharath** [comment]
Thanks for your quick reply Muaz.
It helped a lot.
