### ISSUE TITLE
cordova request was denied for security

### ISSUE THREAD

**Issue by luonadelee** [muaz-khan/RTCMultiConnection#445]
Mr. Khan
       I deploy the RTCMultiConnection project on my server referring to your install guide , and I have got my SSL certification and replace the old certification, video conference work well on browser now but android app can't work ,it display request was denied for security .help!

**Comment by luonadelee** [comment]
close issue，thanks！

**Comment by srajabhoj** [comment]
how did you solved it?

**Comment by muaz-khan** [comment]
Here is a demo file:

* http://webrtcweb.com/cordova-apps/video-conferencing/www/js/index.js

Here is config.xml:

```
view-source:http://webrtcweb.com/cordova-apps/video-conferencing/config.xml
```

It is using `cordova-plugin-android-permissions` to request camera/mic permissions on demand. It will solve all such issues.

`index.js` demo file has `checkAndroidPermissions` method.  This method request for permissions if camera isn't allowed yet.
