### ISSUE TITLE
How to differentiate between screen and video elements in RTCMulticonnection-v3

### ISSUE THREAD

**Issue by Simhabharath** [muaz-khan/RTCMultiConnection#45]
Hi Muaz,
In connection.onstream in RTCMulticonnection 3.0 how can we add isScreen object to know if a person has shard his screen. Currently it is not possible to distinguish the same.In the current version there's no difference between video and screen element as in previous version 2.2.5. How do we differentiate between the video and screen video element. Please suggest.

**Comment by muaz-khan** [comment]
```javascript
connection.onstream = function(event) {
    if(event.stream.isScreen) {
        // screen stream
    }

    if(event.stream.isVideo) {
        // audio+video or video-only stream
    }

    if(event.stream.isAudio) {
        // audio-only stream
    }
};
```

More info: [ReadMe.md#Migrating+From+Older+Versions](https://github.com/muaz-khan/RTCMultiConnection/tree/master/RTCMultiConnection-v3.0#migrating-from-older-versions)
