### ISSUE TITLE
how to debug  ?how to know where is error?

### ISSUE THREAD

**Issue by aazjcom** [muaz-khan/RTCMultiConnection#519]
i use RTCMultiConnection. about 100 men use this sample  .eveyone use chrome.there are some prombles .someone can not get video.someone can not get audio.how to debug ?how to know where is error?

**Comment by aazjcom** [comment]
eveyone use chrome.

**Comment by duchuan1** [comment]
Is it resolve?  I have the same problem with 10 people on my local network
