### ISSUE TITLE
Your WSS server is down?

### ISSUE THREAD

**Issue by MartinCarlson** [muaz-khan/RTCMultiConnection#524]
Demo's can't connect , stuck on 'Searching for existing rooms...'

**Comment by muaz-khan** [comment]
You can try this one instead:

```javascript
var SIGNALING_URI = 'wss://websocket-over-nodejs.herokuapp.com:443/';
```

You can deploy on heroku as well:

* https://github.com/muaz-khan/WebRTC-Experiment/tree/master/websocket-over-nodejs

**Comment by MartinCarlson** [comment]
closing as using my own server
