### ISSUE TITLE
RTCMultiConnection 3.1.3 will not connect at all

### ISSUE THREAD

**Issue by chaos986** [muaz-khan/RTCMultiConnection#55]
I have a creator.html 
https://raw.githubusercontent.com/chaos986/Michael-WebRTC/master/demos/creator.html

and an answerer.html
https://raw.githubusercontent.com/chaos986/Michael-WebRTC/master/demos/answerer.html

when I run them I get the message RTCMultiConnection-v3.1.3.js:324 socket.io connection is opened.
connection.onstream fires.
connection.onopen does not. 

as such no actual connection is made between the 2 browsers. (both chrome 45)

https://v3n1-u-ia.e-sdn.com:3124/socket.io/socket.io.js is socketio-over-nodejs (npm install socketio-over-nodejs)

everything else is POSH on iis8 running over localhost.

should i switch to reliable-signaler ?

**Comment by muaz-khan** [comment]
* http://www.rtcmulticonnection.org/docs/session/

```javascript
connection.session = {
    data: true,     // onopen/onmessage events
    video: true,   // video
    audio: true    // +audio
};
```

Did you try this demo?

* [Audio+Video+TextChat+FileSharing.html](https://github.com/muaz-khan/RTCMultiConnection/blob/master/RTCMultiConnection-v3.0/demos/Audio%2BVideo%2BTextChat%2BFileSharing.html#L121)

**Comment by chaos986** [comment]
I added the data: true,   No effect. 

I have not been able to get any of the 3.0 demos working with the socketio-over-nodejs running just fine for my 2.2.5 demos. 

I've only been making browser side code changes.

**Comment by muaz-khan** [comment]
RTCMultiConnection-3.0 accepts this file only:

* [Signaling-Server.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/RTCMultiConnection-v3.0/Signaling-Server.js)

You should try v2.2.2 or earlier builds for [`socketio-over-nodejs`](https://github.com/muaz-khan/WebRTC-Experiment/tree/master/socketio-over-nodejs) signaling.

**Comment by chaos986** [comment]
so i need to run everything from nodejs now? 

or can i still split my webrtc app code and point SIGNALING_SERVER or connecection.socketURL to my node.js server with npm install socket.io?

my end goal is to integrate videoconferencing into a C# webapp, which i am doing with 2.2.5.  I would like to get 3.0 working because you mentioned in another issue that the onopen fireing twice was fixed in 3.0

my project went from the guest appearing twice to not appearing at all.

**Comment by muaz-khan** [comment]
[v2.2.2](https://cdn.webrtc-experiment.com/RTCMultiConnection.js) is recommended and it doesn't fires `onopen` twice.

```html
<script src="https://cdn.webrtc-experiment.com/RTCMultiConnection.js"></script>
```

v3.0 doesn't accepts other options except "specific-socket.io-server" which means that you can't use firebase or socketio-over-nodejs or reliable-signaler or websocket-over-nodejs or xhr-signaling or websync-signaling etc.

You can see that all these demos are using v2.2.2:

* https://www.webrtc-experiment.com/RTCMultiConnection/

v2.2.2 works using any signaling option except SIP.

* [Custom Signaling Servers for v2.2.2](https://github.com/muaz-khan/RTCMultiConnection/wiki/Custom-Private-Servers#signaling-servers)

**Comment by chaos986** [comment]
ok thank you
