### ISSUE TITLE
userid Vs roomid in getAllParticipants()

### ISSUE THREAD

**Issue by FlorianHergo** [muaz-khan/RTCMultiConnection#551]
Hello,

I understand that the creator (moderator) of the room has userid = roomid.
However, it is a user and therefore why does not appear in: getAllParticipants ()
Is this a bug?

If not, how to SEE the moderator in getAllParticipants (), knowing that the session is open with a userid = roomid.

Thanks

**Comment by muaz-khan** [comment]
`getAllParticipants` returns list of all connected users excluding yourselves. Means that **it do not return your own userid**.

Here are a few examples:

```javascript
getAllParticipants() for userA => userB, userC
getAllParticipants() for userB => userA, userC
getAllParticipants() for userC => userA, userB
```

You can easily make this hack:

```javascript
var listOfAllUsers = connection.getAllParticipants().pus(connection.userid);
```

Now table looks like this:

```javascript
getAllParticipants() for userA => userB, userC, userA
getAllParticipants() for userB => userA, userC, userB
getAllParticipants() for userC => userA, userB, userC
```

**Comment by FlorianHergo** [comment]
First of all I want to thank you for the speed of your answer.
And for the answer. Perfect !
