### ISSUE TITLE
Not work v3.4.4 on cordova ios

### ISSUE THREAD

**Issue by c3bola** [muaz-khan/RTCMultiConnection#569]
I'm tired of trying to solve the remote video problem on iOS.

When I use Android works perfectly, when trying to use iOS I can send audio and video, but I get neither audio nor video.

I am using the code below, please someone help me

```javascript
connection.videosContainer = document.getElementById('videos-container');
connection.onstream = function(event) {
    var div = document.createElement('div');
    div.id = event.streamid || event.stream.id;

    div.appendChild(event.mediaElement);



    connection.videosContainer.insertBefore(div, connection.videosContainer.firstChild);
    connection.fixAllVideos();
};

connection.onstreamended = function(event) {
    removeStreamById(event.streamid || event.stream.id);
};

connection.fixAllVideos = function() {
    Object.keys(connection.streamEvents).forEach(function(key) {
        var event = connection.streamEvents[key];
        var div = document.getElementById(key);
        if (!div) return;
        var video = div.querySelector('video');
        if (!video) return;
        video.src = URL.createObjectURL(event.stream);
        video.play();


        document.getElementById('room-urls').innerHTML += key;

        setTimeout(function() {
            video.play();
        }, 2000);
    });
};
```

**Comment by c3bola** [comment]
@muaz-khan cordova

**Comment by guiluigi** [comment]
I get the same problem :(

**Comment by c3bola** [comment]
@muaz-khan I believe the problem is in this section, because I can send audio and video, I just do not receive remote audio and video in ios (iphone x, in the test)


connection.fixAllVideos = function() {
    Object.keys(connection.streamEvents).forEach(function(key) {
        var event = connection.streamEvents[key];
        var div = document.getElementById(key);
        if (!div) return;
        var video = div.querySelector('video');
        if (!video) return;
        video.src = URL.createObjectURL(event.stream);
        video.play();


        document.getElementById('room-urls').innerHTML += key;

        setTimeout(function() {
            video.play();
        }, 2000);
    });
};

**Comment by pimengd** [comment]
I've got the same problem, did you solve it?

**Comment by c3bola** [comment]
@pimengd Not yet, I'm trying.

**Comment by c3bola** [comment]
@pimengd Not yet, I'm trying. I'm waiting for a feedback from him @muaz-khan , I hope he can help me

**Comment by muaz-khan** [comment]
@c3bola I didn't test cordova for a while. I'll make some tests & share updated demos as well.

**Comment by c3bola** [comment]
Thanks @muaz-khan , I'll keep trying here.
I believe the error is just the loop to display the remote videos.

Thank you very much in advance

**Comment by c3bola** [comment]
@muaz-khan If you have an example of how to use this upgrade, it would help me a lot.

https://github.com/muaz-khan/RTCMultiConnection/blob/master/docs/upgrade.md

An example that shows how to retrieve remote videos

**Comment by muaz-khan** [comment]
```javascript
connection.getAllParticipants().forEach(function(pid) {
    connection.getRemoteStreams(pid).forEach(function(sid) {
        console.log('getRemoteStreams', pid, sid);
    });

    // or below code
    var native = connection.peers[pid].peer;
    console.log('native.getRemoteStreams', native.getRemoteStreams());
});
```

**Comment by c3bola** [comment]
Thank you very much @muaz-khan , I got the

var native = connection.peers [pid] .peer;

The example I have to display the video is

var event = connection.streamEvents [key];
                var div = document.getElementById (key);
                if (! div) return;
                var video = div.querySelector ('video');
                if (! video) return;
                video.src = URL.createObjectURL (event.stream);
                video.play ();

I'm not sure how to adapt it to this return, can you help me?

**Comment by muaz-khan** [comment]
Please try this:

```javascript
// updated according to your "onstream" event
connection.fixAllVideos = function() {
    Object.keys(connection.streamEvents).forEach(function(key) {
        var event = connection.streamEvents[key];
        var video = document.getElementById(key);
        if (!video) return;
        video.src = URL.createObjectURL(event.stream);
        video.play();

        setTimeout(function() {
            video.play();
        }, 2000);
    });
};
```

Or:

```javascript
connection.fixAllVideos = function() {
    connection.getAllParticipants().forEach(function(pid) {
        connection.getRemoteStreams(pid).forEach(function(stream) {
            var video = document.getElementById(stream.id);
            video.src = URL.createObjectURL(stream);
            video.play();

            setTimeout(function() {
                video.play();
            }, 2000);
        });
    });
};
```

**Comment by c3bola** [comment]
@muaz-khan 
I tried it that way, and the error was video.play is not a function

connection.videosContainer = document.getElementById ('videos-container');
onnection.onstream = function (event) {
document.body.appendChild (event.mediaElement);
var div = document.createElement ('div');
div.id = event.streamid || event.stream.id;
div.appendChild (event.mediaElement);
connection.fixAllVideos ();
}
connection.fixAllVideos = function () {
Object.keys (connection.streamEvents) .forEach (function (key) {
var event = connection.streamEvents [key];
var video = document.getElementById (key);
if (! video) returns;
video.src = URL.createObjectURL (event.stream);
video.play ();
setTimeout (function () {
video.play ();
}, 2000);
});
};

**Comment by c3bola** [comment]
@muaz-khan 

I tried that way,
This way, it does not return an error, but it also does not display the remote video.

# connection.getRemoteStreams (pid) .forEach (function (stream) {
empty back stream

I tried it
# var native = connection.peers [pid] .peer;

I was returned an object

connection.videosContainer = document.getElementById ('videos-container');
        connection.onstream = function (event) {
            var div = document.createElement ('div');
            div.id = event.streamid || event.stream.id;
            div.appendChild (event.mediaElement);
            connection.videosContainer.insertBefore (div, connection.videosContainer.firstChild);
            connection.fixAllVideos ();
        }
        connection.fixAllVideos = function () {
            connection.getAllParticipants (). forEach (function (pid) {
                connection.getRemoteStreams (pid) .forEach (function (stream) {
                    var video = document.getElementById (stream.id);
                    video.src = URL.createObjectURL (stream);
                    video.play ();
        
                    setTimeout (function () {
                        video.play ();
                    }, 2000);
                });
            });
        };

**Comment by c3bola** [comment]
@muaz-khan this is the return of this function

connection.getAllParticipants().forEach(function(pid) {
    var native = connection.peers[pid].peer;
    console.log('native.getRemoteStreams', native.getRemoteStreams());
});

native.getRemoteStreams()[object Blob]
_listeners 
addEventListener 
removeEventListener 
dispatchEvent 
localDescription 
remoteDescription 
signalingState 
iceGatheringState 
iceConnectionState 
pcConfig 
pcId 
localStreams 
remoteStreams 
onicecandidate 
onsignalingstatechange 
oniceconnectionstatechange 
onremovestream 
nativeClose 
close 
createOffer 
createAnswer 
setLocalDescription 
setRemoteDescription 
addIceCandidate 
getConfiguration 
getLocalStreams 
getRemoteStreams 
getStreamById 
addStream 
removeStream 
createDataChannel 
createDTMFSender 
getStats 
 
native.getRemoteStreams()[object Blob]
_listeners 
addEventListener 
removeEventListener 
dispatchEvent 
localDescription 
remoteDescription 
signalingState 
iceGatheringState 
iceConnectionState 
pcConfig 
pcId 
localStreams 
remoteStreams 
onicecandidate 
onsignalingstatechange 
oniceconnectionstatechange 
onremovestream 
nativeClose 
close 
createOffer 
createAnswer 
setLocalDescription 
setRemoteDescription 
addIceCandidate 
getConfiguration 
getLocalStreams 
getRemoteStreams 
getStreamById 
addStream 
removeStream 
createDataChannel 
createDTMFSender 
getStats

**Comment by c3bola** [comment]
Hello @muaz-khan , I was able to get the remote id with this command

#for (var k in connection.peers[pid].peer.remoteStreams) {}
k = id remoto

For the local video I used,

# var div = document.createElement('div');
# div.id = event.streamid || event.stream.id;
#div.appendChild(event.mediaElement);
#connection.videosContainer.insertBefore(div, connection.videosContainer.firstChild);

div.id gets the id that this row returns,

However, I can not view the remote video

Can you help me?

This is my complete code
connection.peers.getAllParticipants().forEach(function (pid) {
for (var k in connection.peers[pid].peer.remoteStreams) {
connection.getRemoteStreams(k).forEach(function (stream) {
                         var div = document.createElement('div');
                         div.id = stream.id;
                         var video = document.getElementById(stream.id);
                         video.src = URL.createObjectURL(stream);
                         video.play();
     
                         setTimeout(function () {
                             video.play();
                         }, 2000);
                     });
}
                 });

**Comment by YKKate** [comment]
I has the same problem, but I solved it. Maybe this can help you :)

I found that my remote video has a width of 0. 
After I set the size to remote video, it succeeded.
