### ISSUE TITLE
Client ip adresses not private.

### ISSUE THREAD

**Issue by leftspace89** [muaz-khan/RTCMultiConnection#578]
wireshark can log peer ip adresses how Can I block this ? 
I need some server like proxy but I dont know how to do.

**Comment by muaz-khan** [comment]
_"....the only solution is block or disable WebRTC!...."_

Though we can filter ip-addresses before sharing candidate pairs with the remote parties. In this case, TURN will be the only solution to setup WebRTC calls.

TURN's relay addresses can be a workaround. _But no one wanna use TURN for longer calls._

RTCMultiConnection provides this API to ignore local and public ip-addresses:

```javascript
connection.candidates = {
    host: false,
    stun: false, // or reflexive: false
    turn: true   // or relay: true
};
```

Version 3 supports this as well:

```javascript
connection.iceTransportPolicy = 'relay';
```

You can test above two snippets in the chrome console and watch wireshark again.
