### ISSUE TITLE
iOS error: do not working ios video on android

### ISSUE THREAD

**Issue by hardcorelite** [muaz-khan/RTCMultiConnection#581]
[Error] Not allowed to load local resource: blob:blobinternal:

**Comment by muaz-khan** [comment]
Is that fixed? What was the bug?

**Comment by hardcorelite** [comment]
@muaz-khan  no, it's just been a long time, there's no point in keeping the question. but if you have any thoughts please tell me

**Comment by hardcorelite** [comment]
@muaz-khan I also can't solve the issue of how to see the video on ios it is not displayed

**Comment by hardcorelite** [comment]
`this.connection.socketURL = 'https://ezmaven.com:8888/';
    this.connection.socketMessageEvent = 'video-conference-demo';
    this.connection.session = {
      audio: true,
      video: true
    };
    this.connection.mediaConstraints = {
      audio: true,
      video: true
    };
    this.connection.sdpConstraints.mandatory = {
      OfferToReceiveAudio: true,
      OfferToReceiveVideo: true
    };
    //this.connection.audiosContainer = this.myAudio;
    this.connection.onstream = (event)=> {
      console.log(event)
      console.log(window.URL.createObjectURL(event.stream))
      this.streemAudio.push({id:event.streamid, url:this.sanitizer.bypassSecurityTrustUrl(window.URL.createObjectURL(event.stream))});
      console.log(this.streemAudio)
    };

    this.connection.onstreamended = (event)=> {
      this.streemAudio.splice(this.getMsgIndexById(event.streamid), 1);
    };
    this.connection.maxParticipantsAllowed = 1;
    this.connection.onRoomFull = (roomid)=> {
      this.connection.closeSocket();

      this.connection.attachStreams.forEach((stream)=>{
        stream.stop();
      });

      this.disableInputButtons()

      alert('Room is full.');
    };`

**Comment by muaz-khan** [comment]
I'm have video rendering issues on iOS10 as well. I'll fix this cordova demo soon for iOS:

* https://webrtcweb.com/cordova-apps/video-conferencing/

**Comment by hardcorelite** [comment]
@muaz-khan We are ready to help you and release the source code for the project ionic 3 if you are interested) How soon can we see the video on ios 11?
