### ISSUE TITLE
problem join to room

### ISSUE THREAD

**Issue by vanbinh2811** [muaz-khan/RTCMultiConnection#59]
i have problem below:
owner : share session {video:true.audio:true,oneway} => was successful
user join to room then not stream and received message: 
Signaling channel is connected. Joining the session again...
detecting-room-presence: Checking presence of the room.
room-available: Initiator is available and room is active.
Seems data-only connection.
connecting-with-initiator: Checking presence of the initiator; and the room.
i dont know why?

**Comment by muaz-khan** [comment]
Please try this demo and it should be working:

* [https://jsfiddle.net/c46de0L8/198/](https://jsfiddle.net/c46de0L8/198/)
