### ISSUE TITLE
Can't send file if it is more than 65k using share file, do you have a fix?

### ISSUE THREAD

**Issue by IndranilSarkar87** [muaz-khan/RTCMultiConnection#606]
I am unable to send file in share connection, if we use Share file option and the size is more than 65k file bufffer size is exceeding to receive it
error message "FileBufferReader.js:1228 Uncaught DOMException: Message too large (can send a maximum of 65536 bytes)"
![error](https://user-images.githubusercontent.com/40937981/42634683-83e76f3c-85ec-11e8-96e6-8665f5a1c283.JPG)

**Comment by anilk9096** [comment]
hi i am also facing same issue due you got work around for this

**Comment by muaz-khan** [comment]
Did you try to set lower values for `chunkSize`?
* https://www.rtcmulticonnection.org/docs/chunkSize/

E.g.

```javascript
// both chrome/firefox now accepts 64 kilo-bits for each data-chunk
connection.chunkSize = 60 * 1000;

// to make sure it works on all devices
connection.chunkSize = 15 * 1000;
```

Here is an alternative to FileBufferReader:

* https://github.com/muaz-khan/RTCMultiConnection/issues/378#issuecomment-291499023

**Comment by IndranilSarkar87** [comment]
I fixed that using following code below

var chunksize = 15000, chunkinterval = 100;
connection.chunkSize = +chunksize;
connection.chunkInterval = +chunkinterval;

**Comment by anilk9096** [comment]
Thank you issue solved
