### ISSUE TITLE
Custom Signaling server

### ISSUE THREAD

**Issue by ph4t0o0o0om** [muaz-khan/RTCMultiConnection#624]
Hi can anyone help me how to implement a custome connection.socketUrl for the canvas-designer repo? Please help me badly need it.  Thank you so very much!!!

**Comment by muaz-khan** [comment]
Here is the documentation: https://www.rtcmulticonnection.org/docs/socketURL/

I'll recommend you install socket.io on your own instance of heroku server, or nodejs hosting.

Here are non-socketio demos:

* [demos/PubNub-Demo.html](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/PubNub-Demo.html)
* [demos/Firebase-Demo.html](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/Firebase-Demo.html)
* [demos/WebSocket-Demo.html](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/WebSocket-Demo.html)

Here is documentation for `setCustomSocketHandler`; a method that allows you use external (non-socketio) signaling servers: https://www.rtcmulticonnection.org/docs/setCustomSocketHandler/

**Comment by ph4t0o0o0om** [comment]
@muaz-khan please help me :( . I comment several times on the canvas designer ask and question please check it i badly need this thank you so much :(

**Comment by muaz-khan** [comment]
Source code is here:
```sh
mkdir demo && cd demo
git clone https://github.com/muaz-khan/RTCMultiConnection.git ./
npm install --production
node server --port=9002 --ssl --ssl_key=/home/ssl/ssl.key --ssl_cert=/home/ssl/ssl.crt
```
Documentation:
* https://github.com/muaz-khan/RTCMultiConnection/tree/master/docs/installation-guide.md

Now you can change URL in the `index.html`:

```javascript
connection.socketURL = 'https://domain:9002/';
```
----
### Behind the scene

You need only these two files:
1. [server.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/server.js)
2. [Signaling-Server.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/Signaling-Server.js)

Rest of the code from RTCMultiConnection repository is irrelevant.

If you download only these two files, then you need to manually install `socket.io`:

```sh
wget https://raw.githubusercontent.com/muaz-khan/RTCMultiConnection/master/server.js
wget https://raw.githubusercontent.com/muaz-khan/RTCMultiConnection/master/Signaling-Server.js
npm install socket.io --save-dev
node server --port=9002 --ssl --ssl_key=/home/ssl/ssl.key --ssl_cert=/home/ssl/ssl.crt
```

**Comment by ph4t0o0o0om** [comment]
What is this sir? Is this the PDF upload function>?

**Comment by numerized** [comment]
Hi Muaz thanks for amazing code!

firebase demo is gone?
