### ISSUE TITLE
Create a local server

### ISSUE THREAD

**Issue by c3bola** [muaz-khan/RTCMultiConnection#629]
How can I create a local server with web socket to run RTC with the same settings of the demo server?

Demo server:
https://rtcmulticonnection.herokuapp.com:443/

**Comment by muaz-khan** [comment]
```sh
mkdir demo
cd demo
git clone https://github.com/muaz-khan/RTCMultiConnection.git ./
mkdir node_modules
npm install --production
node server --port=9001
```

I use [`pm2`](https://github.com/Unitech/pm2) to keep server alive and auto restart on failure or auto start on system reboot:

```sh
m2 start server.js --port=9001
```

**Comment by ph4t0o0o0om** [comment]
@muaz-khan please notice my issue . Entitled SAME LAYOUT ON OTHER USERS

**Comment by c3bola** [comment]
@muaz-khan tks
