### ISSUE TITLE
Make this work properly as an npm package

### ISSUE THREAD

**Issue by Masterxilo** [muaz-khan/RTCMultiConnection#635]
You should make this work like any npm package which one can install and then use with `require('rtcmulticonnection')` for both the client side and signaling-server-side functionality.

Ideally, this should just work with the standard way of using React (in jsx code...).

See https://github.com/peers/peerjs (npm package peerjs) and https://github.com/peers/peerjs-server (npm package peer) for inspiration. They apparently split the server and the client component, but I think you don't even need to do that. 

Just make `const rtcmulticonnection = require('rtcmulticonnection')` export two objects:
* `rtcmulticonnection.RTCMultiConnection`, the object that is currently exported globally by the client library `dist/RTCMultiConnection.min.js` as `window.RTCMultiConnection`
* `rtcmulticonnection.SignalingServer`, the object that is currently exported by `Signaling-Server.js`

You can make it such that either object is null when the library is used on the server or on the client.

From what I see, at the moment, even though this library can be installed from npm, it cannot be used at all via `require('rtcmulticonnection')`.

I am not quite sure of all the things you need to do to make this work myself.

**Comment by clarkwkw** [comment]
@muaz-khan Any thoughts?

**Comment by ph4t0o0o0om** [comment]
It is already in NPM . see the latest commits

**Comment by muaz-khan** [comment]
@clarkwkw its in my todo list. Actually I need to remove all `window` keywords. Need to force [jshint](https://github.com/muaz-khan/RecordRTC/blob/master/Gruntfile.js#L77) as well.

**Comment by muaz-khan** [comment]
* https://npm.runkit.com/rtcmulticonnection
