### ISSUE TITLE
User cannot join to an existing room 

### ISSUE THREAD

**Issue by rameshsilva** [muaz-khan/RTCMultiConnection#641]
2 days ago I tested the demos/dashboard.html page in Firefox,it worked. But today I checked it but the second tab new user cannot join to the previous tab same room id. It joins as new always.

I changed the 2 lines as well as below.
```

<!--<script src="/socket.io/socket.io.js"></script>-->
    <script src="https://rtcmulticonnection.herokuapp.com/socket.io/socket.io.js"></script>

connection.socketURL = 'https://rtcmulticonnection.herokuapp.com:443/';
```

But no luck, what happens here.

**Comment by rameshsilva** [comment]
I found the issue, yesterday release have changed the code.I got a new release of 3.4.7. Tested, Working fine.

**Comment by ph4t0o0o0om** [comment]
Hi I already test it and made the changes you made . But still now working fine. After I create a room no message like (Please share this link) . Can you please share your code?

**Comment by ph4t0o0o0om** [comment]
It works fine now. Thank you!
