### ISSUE TITLE
does my own signal server need ssl?

### ISSUE THREAD

**Issue by learn333** [muaz-khan/RTCMultiConnection#648]
### Demo link
Are you using a demo from `./demos` directory?

### JavaScript
```javascript
// javascript codes goes here
```

### HTML
```html
// HTML codes goes here
```

**Comment by learn333** [comment]
Does my own signal server need ssl to run if i am using firefox browser?

**Comment by avspeed** [comment]
Read this
https://www.digicert.com/blog/https-only-features-in-browsers/

look at the section about getUserMedia
it will answer your question and more!

Regards
Gaetan Siry
AVSPEED

**Comment by muaz-khan** [comment]
Yes. SSL is recommended. You may wanna check [this otherwise](https://github.com/muaz-khan/Chrome-Extensions/tree/master/getUserMedia-on-http).
