### ISSUE TITLE
Maximum users.

### ISSUE THREAD

**Issue by ph4t0o0o0om** [muaz-khan/RTCMultiConnection#660]
Hi sir Good day. How to set a maximum participants  that can join a room in dashboard.html demo?

**Comment by muaz-khan** [comment]
Please check this:
* https://www.rtcmulticonnection.org/docs/maxParticipantsAllowed/

**Comment by ph4t0o0o0om** [comment]
Okay sir. It prevents participants to join but it is still proceed to the dashboard. How can I do that has a alert message IE "The room is full" and the user can't join the room not proceeding the room?

**Comment by muaz-khan** [comment]
Fixed. https://github.com/muaz-khan/RTCMultiConnection/commit/cd9198374e8db828b68437b58d56357fcf8d8a55
