### ISSUE TITLE
yarn install with node expected ver 'latest' error 

### ISSUE THREAD

**Issue by kelvin2go** [muaz-khan/RTCMultiConnection#661]
### Describe the bug
when yarn install, the expect latest node engine. is that possible to use number + instead?

### Expected behavior
when yarn install, most common npm ver should be able to install

### Demo link
```
warning adapterjs@0.15.3: The engine "grunt" appears to be invalid.
error rtcmulticonnection@3.5.0: The engine "node" is incompatible with this module. Expected version "latest".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by Adizbek** [comment]
Please specify version, as versions are changing, it may cause problems during development and deployment
