### ISSUE TITLE
I'm trying to run this on production live server, but couldn't achieved!

### ISSUE THREAD

**Issue by Im10Anish** [muaz-khan/RTCMultiConnection#662]
I already following your tuts everything works fine when running on localhost but when deploying same code with changes in config.json it stops working. To confirm that what I'm doing wrong I make same changes in localhost files then I get to know by changing socketURL in config.json will not works, I also go other files which I thought will help but no hopes.

**Comment by muaz-khan** [comment]
Did you fix it?

**Comment by Im10Anish** [comment]
I'm reading from your docs folder, you explain there about this but not yet
implemented because what you suggesting I already done before but not
succeed i'm looking for something new that I haven't tried. What I am
trying to do run the same code on the server i made changes in config.json
like URL with and without port, declare same port number on port but
couldn't work. And yes How I can improve video quality of the stream when
i am trying to do this by changing resoultion then it's not responsive. I
am trying to run same code on web and mobile browser too.

**Comment by Im10Anish** [comment]
Thanks for your help, Sir. I already implemented whatever you said and good news everything works fine now. Suddenly, that implemented codes showing CORS error I am amazed because this error should show from the start why suddenly after 2 days from implementation. And, one more thing checkPresence() works fine when refreshing the page but what will happen when during the stream there is no network and after some time it again found the network to continue. Is there any other method to re-join the break session or I should stick with checkPresence() method just increase the interval time.

**Comment by Im10Anish** [comment]
Now, It's automatically gone. can you please tell me what was happened at that time or what are the chances the same will repeat in future. If yes, what steps should I take to avoid them. Now, i have one more question what's the steps to hide time with progess bar that's show time during stream i tried but couldn't find any way.

**Comment by Im10Anish** [comment]
Why i'm suddenly getting an error: OverconstrainedError on localhost as well as on production server.

**Comment by muaz-khan** [comment]
Did you check this?

```
chrome://settings/content/camera?search=camera
chrome://settings/content/camera?search=microphone
```

Maybe your system is blocking the device. **Otherwise please relanch chrome browser**.

**Comment by Im10Anish** [comment]
Yes, it started now but can you explain what's the problem at that time.
