### ISSUE TITLE
is it possible to set DataChannel bandwidth up/down limit?

### ISSUE THREAD

**Issue by jimmywarting** [muaz-khan/RTCMultiConnection#684]
I Found a wiki of how to set bandwidth on audio and video stream
But is it also possible to set it for the DataChannel as well and control upload/download speed?

i tried adding `b=AS` after a `a=mid:data` but it's still sending me data faster then what i'm able to handle

**Comment by VShtaba** [comment]
Can this https://github.com/muaz-khan/RTCMultiConnection/wiki/Bandwidth-Management help you?

**Comment by muaz-khan** [comment]
@jimmywarting I don't think SCTP [spec](https://datatracker.ietf.org/doc/draft-ietf-mmusic-sctp-sdp/?include_text=1) has this option.

`b=AS` or `x-google-min-bitrate=` seems applies only to RTP streams/packets. (`a=fmtp:VP9`)
