### ISSUE TITLE
Not working in Microsoft Edge

### ISSUE THREAD

**Issue by itzurkarthi** [muaz-khan/RTCMultiConnection#688]
@muaz-khan

I tried your demo - https://rtcmulticonnection.herokuapp.com/demos/TextChat+FileSharing.html in firefox and microsoft edge.

Demo url is already loaded with adapter.js .

In microsoft edge console I'm getting this error
"Object doesn't support property or method 'createDataChannel' "

Could you please tell us what could be the issue?

Thanks
Karthikeyan K

**Comment by itzurkarthi** [comment]
@muaz-khan Is there any update? Could you please help me to resolve this issue

Thanks

**Comment by muaz-khan** [comment]
It seems that Microsoft Edge **does not supports WebRTC data channels** at the moment.
1. [Neither in ORTC](https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?q=specName%3Aortc)
2. [Nor in WebRTC 1.0](https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?q=specName%3Awebrtc)
