### ISSUE TITLE
Force RTCMultiConnection to use the TURN server

### ISSUE THREAD

**Issue by Woosah** [muaz-khan/RTCMultiConnection#689]
We are using the RTCMultiConnection for an audio + video call. Next to that we set up our own coTURN-server. The question is, how can we force all participants in the call to use the TURN-Server and to NOT use just only the P2P-Connections?

Do we have to change some settings / parameters for RTCMultiConnection or on the coTURN-server? Any hints would be greatly appreciated...

**Comment by muaz-khan** [comment]
```javascript
connection.candidates = {
    turn: true
};
connection.iceTransportPolicy = 'relay';
```
* https://www.rtcmulticonnection.org/docs/candidates/
* https://www.rtcmulticonnection.org/docs/iceTransportPolicy/

**Comment by ph4t0o0o0om** [comment]
@muaz-khan if have much time sir please check my email. thanks!

**Comment by Woosah** [comment]
Thx a lot for the immediate answer!

This works for the 3.5.8 version?

**Comment by muaz-khan** [comment]
@Woosah Yes. It should work with all v3 version.

Did you face any issue; or did you find any HOST or SRFLX candidates via `chrome://webrtc-internals/`?

**Comment by Woosah** [comment]
Everything's working just fine! Thx!
