### ISSUE TITLE
RTCMulticonnection doesn't work with firefox

### ISSUE THREAD

**Issue by bnara1** [muaz-khan/RTCMultiConnection#690]
When two users using firefox on different networks, use RTCMulticonnection for audio call, it doesn't work most of the time.
Users get this error 
ICE failed, your TURN server appears to be broken
Peer connection is closed between you & ...

Is this a known issue that RTCMulticonnection doesn't work with firefox ?
Anyone knows the reason for this? Any workarounds ?

**Comment by ph4t0o0o0om** [comment]
I have this same error too. That is why I'm using chrome as of now.  I'm pretty sure @muaz-khan going to fix this soon.

**Comment by bnara1** [comment]
Thanks for the reply. 
Hope @muaz-khan will fix the rtcmulticonnection firefox issue soon

Other than chrome, do you know any browser where rtcmulticonnection works fine without turn server issues ?

**Comment by ph4t0o0o0om** [comment]
I'm not sure . Use chrome for now if you want to settle the issue

**Comment by bnara1** [comment]
Hi @muaz-khan , I tried the latest version of rtcmulticonnection, but I still get ICE Failed error with firefox.

**Comment by bnara1** [comment]
@ph4t0o0o0om did you get a chance to try out latest fix from @muaz-khan ?
Due to some reason I still get ICE failed error on firefox

**Comment by muaz-khan** [comment]
Please try this: (in your HTML file)

```javascript
connection.iceServers = [{
        'urls': [
            'stun:webrtcweb.com:7788',
            'stun:webrtcweb.com:7788?transport=udp',
        ],
        'username': 'muazkh',
        'credential': 'muazkh'
    },
    {
        'urls': [
            'turn:webrtcweb.com:7788',
            'turn:webrtcweb.com:4455?transport=udp',

            'turn:webrtcweb.com:8877?transport=udp',
            'turn:webrtcweb.com:8877?transport=tcp',
        ],
        'username': 'muazkh',
        'credential': 'muazkh'
    },
    {
        'urls': [
            'stun:stun.l.google.com:19302',
            'stun:stun1.l.google.com:19302',
            'stun:stun2.l.google.com:19302',
            'stun:stun.l.google.com:19302?transport=udp',
        ]
    }
];
```

**Comment by zhangalex** [comment]
@muaz-khan    Why your turn udp port is 4455, could you please tell me where I can change it?

**Comment by bnara1** [comment]
Hi @muaz-khan, I added the suggested line in the file where I create the new instance of RTCMulticonnection, 

connection.iceServers = [{
		        'urls': [
		            'stun:webrtcweb.com:7788',
		            'stun:webrtcweb.com:7788?transport=udp',
		        ],
		        'username': 'muazkh',
		        'credential': 'muazkh'
		    },
		    {
		        'urls': [
		            'turn:webrtcweb.com:7788',
		            'turn:webrtcweb.com:4455?transport=udp',

		            'turn:webrtcweb.com:8877?transport=udp',
		            'turn:webrtcweb.com:8877?transport=tcp',
		        ],
		        'username': 'muazkh',
		        'credential': 'muazkh'
		    },
		    {
		        'urls': [
		            'stun:stun.l.google.com:19302',
		            'stun:stun1.l.google.com:19302',
		            'stun:stun2.l.google.com:19302',
		            'stun:stun.l.google.com:19302?transport=udp',
		        ]
		    }
		];
            if (typeof window.InstallTrigger !== 'undefined') {
            	connection.iceServers = [{
                    'urls': [
                        'turn:webrtcweb.com:7788',
                        'stun:webrtcweb.com:7788',
                    ],
                    'username': 'muazkh',
                    'credential': 'muazkh'
                }];
            }



but I still get the ICE failed error in firefox when I connect to another person who uses chrome browser.

When I close connection (after the error) and reconnect in firefox, then connection seems fine.

Anything else I have to do to prevent the error ?

**Comment by bnara1** [comment]
Hi @muaz-khan , any update on my query ?

**Comment by bnara1** [comment]
@ph4t0o0o0om did you get a chance to try out latest fix from @muaz-khan ?

**Comment by bnara1** [comment]
I still get ICE failed, your TURN server appears to be broken errors

**Comment by muaz-khan** [comment]
Hi, just tested this demo on Firefox 63 Android 7:
* https://rtcmulticonnection.herokuapp.com/demos/Video-Conferencing.html

Firefox started the session and Chrome 70 desktop joined him.

Firefox 67 on Android was using 3G. However Chrome 70 on desktop was using DSL/broadband.

And it worked for me using same demo:
* https://rtcmulticonnection.herokuapp.com/demos/Video-Conferencing.html

Though Firefox didn't receive Chrome' screen however desktop was getting HD/smooth stream from android. It didn't fail. And YES, it was using relay addresses both android applies too many firewall rules. And 3G is a different network.

**Comment by sergzach** [comment]
@muaz-khan Hi, Muaz! 

Excuse me, but the example does not work currently when I start conferencing via Firefox 65 then join via Chrome 72 (both in Ubuntu 16.04). When I press "join" in Chrome nothing happens.
