### ISSUE TITLE
File Share can send a maximum of 65536 bytes

### ISSUE THREAD

**Issue by nenadfemic** [muaz-khan/RTCMultiConnection#695]
Hi Muaz

Is it possible from code change limit 65536 bytes in File sharing :

**FileBufferReader.js:1228 Uncaught TypeError: Message too large (can send a maximum of 65536 bytes)**
    at RTCDataChannel.dc.send [as internalSend] (adapter.js:4201)
    at RTCDataChannel.channel.send (RTCMultiConnection.min.js:15)
    at RTCMultiConnection.min.js:15
    at Array.forEach (<anonymous>)
    at RTCMultiConnection.min.js:15
    at FileBufferReader.js:116
    at FileBufferReader.js:545
    at FileBufferReader.js:1215
    at FileBufferReader.js:1135
    at FileBufferReader.js:1061

I know that can try with edit 65536 directly in **adapter.js** file, but i don't  think is good approach.

Can you help.

**Comment by nenadfemic** [comment]
This is problem on Google Chrome

**https://bugs.chromium.org/p/webrtc/issues/detail?id=8419**

is there solutions for this

**Comment by muaz-khan** [comment]
* https://www.rtcmulticonnection.org/docs/chunkSize/

```javascript
// both chrome/firefox now accepts 64 kilo-bits for each data-chunk
connection.chunkSize = 60 * 1000;

// to make sure it works on all devices
connection.chunkSize = 15 * 1000;
```
