### ISSUE TITLE
Every Client Joining The room Have Same UserName

### ISSUE THREAD

**Issue by Qaisarimran** [muaz-khan/RTCMultiConnection#70]
Assalam-o-Alikum Muaz Bhai,

Muaz bhai first of all thanks a lot for help me through my previous problem. As am newbie in JavaScript so am facing a problem in BroadCast and do not understand why this is happening. The problem is that when a person join to the room all the previous person stream get the same name of the new person. Am setting the name of person in cookies at Page1 and retrieving that cookies at the BroadCast page. For example

Page 1:

<script>
    document.cookie = "Person = Ali";
</script>

BroadCast:

<script>
            // Muaz Khan     - https://github.com/muaz-khan
            // MIT License   - https://www.webrtc-experiment.com/licence/
            // Documentation - https://github.com/muaz-khan/RTCMultiConnection
            var connection = new RTCMultiConnection();
            connection.session = {
                audio: true,
                video: true,
                broadcast: true
            };
            connection.extra = {
                //username: 'muazkh',
                username : getCookie("Person"), 
                fullname: 'Muaz Khan',
                email: 'muazkh@gmail.com'
            };
            connection.onstream = function (e) {
                e.mediaElement.width = 600;
                //check remote videos
                var userData = e.extra;
                if (e.type == 'remote') {
                    videosContainer.insertBefore(e.mediaElement, videosContainer.firstChild);
                    videosContainer.title = userData.username.toString();
                    rotateVideo(e.mediaElement);
                    scaleVideos();
                }

                videosContainer.insertBefore(e.mediaElement, videosContainer.firstChild);
                videosContainer.title = userData.username.toString();
                rotateVideo(e.mediaElement);
                scaleVideos();
            };
            function rotateVideo(mediaElement) {
                mediaElement.style[navigator.mozGetUserMedia ? 'transform' : '-webkit-transform'] = 'rotate(0deg)';
                setTimeout(function () {
                    mediaElement.style[navigator.mozGetUserMedia ? 'transform' : '-webkit-transform'] = 'rotate(360deg)';
                }, 1000);
            }
            connection.onstreamended = function (e) {
                e.mediaElement.style.opacity = 0;
                rotateVideo(e.mediaElement);
                setTimeout(function () {
                    if (e.mediaElement.parentNode) {
                        e.mediaElement.parentNode.removeChild(e.mediaElement);
                    }
                    scaleVideos();
                }, 1000);
            };
            var sessions = {};
            connection.onNewSession = function (session) {
                if (sessions[session.sessionid]) return;
                sessions[session.sessionid] = session;
                var tr = document.createElement('tr');
                tr.innerHTML = '<td><strong>' + session.sessionid + '</strong> is an active room.</td>' +
                '<td><button class="join">Join the Room</button></td>';
                roomsList.insertBefore(tr, roomsList.firstChild);
                var joinRoomButton = tr.querySelector('.join');
                joinRoomButton.setAttribute('data-sessionid', session.sessionid);
                joinRoomButton.onclick = function () {
                    this.disabled = true;
                    var sessionid = this.getAttribute('data-sessionid');
                    session = sessions[sessionid];
                    if (!session) throw 'No such session exists.';
                    connection.join(session);
                };
            };
            var videosContainer = document.getElementById('videos-container') || document.body;
            var roomsList = document.getElementById('rooms-list');
            document.getElementById('setup-new-broadcast').onclick = function () {
                this.disabled = true;

                connection.dontCaptureUserMedia = true;
                connection.sdpConstraints.mandatory = {
                    OfferToReceiveAudio: true,
                    OfferToReceiveVideo: true
                };
                connection.open(document.getElementById('broadcast-name').value || 'Anonymous');
            };
            connection.dontCaptureUserMedia = false;
            connection.sdpConstraints.mandatory = {
                OfferToReceiveAudio: false,
                OfferToReceiveVideo: false
            };
            // setup signaling to search existing sessions
            connection.connect();
            (function () {
                var uniqueToken = document.getElementById('unique-token');
                if (uniqueToken)
                    if (location.hash.length > 2) uniqueToken.parentNode.parentNode.parentNode.innerHTML = '<h2 style="text-align:center;"><a href="' + location.href + '" target="_blank">Share this link</a></h2>';
                    else uniqueToken.innerHTML = uniqueToken.parentNode.parentNode.href = '#' + (Math.random() * new Date().getTime()).toString(36).toUpperCase().replace(/\./g, '-');
            })();
            function scaleVideos() {
                var videos = document.querySelectorAll('video'),
                length = videos.length,
                video;
                var minus = 130;
                var windowHeight = 700;
                var windowWidth = 600;
                var windowAspectRatio = windowWidth / windowHeight;
                var videoAspectRatio = 4 / 3;
                var blockAspectRatio;
                var tempVideoWidth = 0;
                var maxVideoWidth = 0;
                for (var i = length; i > 0; i--) {
                    blockAspectRatio = i * videoAspectRatio / Math.ceil(length / i);
                    if (blockAspectRatio <= windowAspectRatio) {
                        tempVideoWidth = videoAspectRatio * windowHeight / Math.ceil(length / i);
                    } else {
                        tempVideoWidth = windowWidth / i;
                    }
                    if (tempVideoWidth > maxVideoWidth)
                        maxVideoWidth = tempVideoWidth;
                }
                for (var i = 0; i < length; i++) {
                    video = videos[i];
                    if (video)
                        video.width = maxVideoWidth - minus;
                }
            }
            window.onresize = scaleVideos;

            function getCookie(cname) {
                var name = cname + "=";
                var ca = document.cookie.split(';');
                for (var i = 0; i < ca.length; i++) {
                    var c = ca[i];
                    while (c.charAt(0) == ' ') c = c.substring(1);
                    if (c.indexOf(name) == 0) return c.substring(name.length, c.length);
                }
                return "";
            }
        </script>

[BroadCast.txt](https://github.com/muaz-khan/RTCMultiConnection/files/34173/BroadCast.txt)

**Comment by muaz-khan** [comment]
If you're using v2.2.2 then please make sure that you're testing between Chrome and Firefox or between Chrome normal mode and "incognito" mode.

Make sure that you're NOT testing between two-similar tabs because both tabs will be using same cookies-base.

Otherwise, use `prompt(...)` instead of taking `username` from cookies.

Also, v3.* always keeps extra-data synced, which means that as soon as you'll modify extra object for any value, all the extra-data will be synced with all connected users. That's why v3.* is preferred over v2.2.2.

PS. Looking into your code, I found that you're setting `title` for `videosContainer` instead of setting title for `<video>` itself. Try something like this:

```javascript
// works with both v2.2.2 and v3.*
connection.onstream = function(event) {
     event.mediaElement.title = event.extra.username;

    // or
    var div = document.createElement('div');
     div.innerHTML = '<h2>' + event.extra.username + '<h2>';
     div.appendChild(event.mediaElement);
     div.className = 'video-overlaper';  // set CSS styles to this class
     videosContainer.appendChild( div );
};
```

**Comment by Qaisarimran** [comment]
Thank you very much Muaz bhai.
ALLAH bless you. Ameen
JAZAKALLAH KHAIR
