### ISSUE TITLE
GET https://webrtcexperiment-webrtc.netdna-ssl.com/common.js net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by zanyarhasani** [muaz-khan/RTCMultiConnection#713]
hi when i run the server i get this error:
GET https://webrtcexperiment-webrtc.netdna-ssl.com/common.js net::ERR_CONNECTION_REFUSED
how can i solve it?

**Comment by zanyarhasani** [comment]
thanks i find solution :
add :443 port to domain

**Comment by muaz-khan** [comment]
This file is redundant. This file is used only to include `disqus.com` comments. Please remove that file in your own local codes.
