### ISSUE TITLE
High cpu usage for the broadcaster

### ISSUE THREAD

**Issue by Proxy08** [muaz-khan/RTCMultiConnection#719]
Hi @muaz-khan,
Thanks for your amazing job. In scalable broadcasting when user A broadcast to all users, every time a new user gets the streams from the user A, the cpu of the user A keeps increasing. is there any way to fix that ?

**Comment by VShtaba** [comment]
A high load on the processor is normal for WebRTC, my friend. Each stream for the new connection is separately processed by the processor.
