### ISSUE TITLE
How does work the Signaling-Server with a newer version socket.io

### ISSUE THREAD

**Issue by nova76** [muaz-khan/RTCMultiConnection#75]
Hi

This server is very simple and works with '0.9.16' socket.io version: 
https://github.com/muaz-khan/RTCMultiConnection/blob/master/RTCMultiConnection-v3.0/Signaling-Server.js

But how does work this SignalServer a newer version of socket.io (1.3.6).
The browser gives the message of the following error : 
{ "code" : 0, " message": " Transport unknown "}

I would like to join with the socket-io-client from another server. But I give the error from the server log (socket.io version: 0.9.16): 
 info  - unhandled socket.io url

**Comment by muaz-khan** [comment]
You may need to change this link: [Signaling-Server.js#L10](https://github.com/muaz-khan/RTCMultiConnection/blob/master/RTCMultiConnection-v3.0/Signaling-Server.js#L10)

```javascript
var io = require('socket.io')(app, {
    log: false,
    origins: '*:*'
});
```

and this line: [Signaling-Server.js#L24](https://github.com/muaz-khan/RTCMultiConnection/blob/master/RTCMultiConnection-v3.0/Signaling-Server.js#L24)

```javascript
io.on('connection', function(socket) {
    // ...
});
```

Change this line as well: [SocketConnection.js#L2](https://github.com/muaz-khan/RTCMultiConnection/blob/master/RTCMultiConnection-v3.0/dev/SocketConnection.js#L2)

```javascript
var socket = io((connection.socketURL || '/') + '?userid=' + connection.userid + '&msgEvent=' + connection.socketMessageEvent, connection.socketOptions);
```

**Comment by nova76** [comment]
thanks
