### ISSUE TITLE
Force Scalable Audio/Video Broadcast to use your own turn server

### ISSUE THREAD

**Issue by Proxy08** [muaz-khan/RTCMultiConnection#782]
Hello,
We are using the RTCMultiConnection Scalable Audio/Video Broadcast. We set up our own coTURN-server, but it does not seem to work even though I've followed these https://www.rtcmulticonnection.org/docs/iceServers/
we are still getting this error even in the same network 
> peer connnection close between you and userid 
```// first step, ignore default STUN+TURN servers
connection.iceServers = [];

// second step, set STUN url
connection.iceServers.push({
    urls: 'stun:yourSTUN.com:port'
});

// last step, set TURN url (recommended)
connection.iceServers.push({
    urls: 'turn:myTURN.com:port',
    credential: 'mypassword',
    username: 'myusername'
});
```
do you know how can we force Scalable Broadcast to use my own coturn???

**Comment by muaz-khan** [comment]
Please try this:

```javascript
connection.iceTransportPolicy = 'relay'
connection.candidates = {
    turn: true
};
```

**Comment by Proxy08** [comment]
still not working, I even try to combine with 
>   connection.getExternalIceServers = true;

but I still get that error  ```peer connnection close between you and userid```

**Comment by Proxy08** [comment]
After intensive searching, it looks like the problem comes from chrome only,  I've tested it in safari and opera everything works fine.

**Comment by rtarta** [comment]
@Proxy08  coudl you use twillo turn and stund services.

**Comment by rtarta** [comment]
@muaz-khan  we need to force ? is it possible to force allways turn and stun server ?
