### ISSUE TITLE
demo video-and-screen-sharing does not work

### ISSUE THREAD

**Issue by Yang03** [muaz-khan/RTCMultiConnection#786]
hi 
when i  run the demo `video-and-screen-sharing`, does not work , i found `getTracks` undefined , `getTracks` is `mediaStream.getTracks` ?

thank you

**Comment by thornzz** [comment]
Have you solved it?

**Comment by truongtin** [comment]
Have you had resolved this issue? @thornzz  @Yang03

**Comment by thornzz** [comment]
This library no more updated and no answer from Muaz. I changed my library to janus. No more problem.

**Comment by Yang03** [comment]
@truongtin I forgot, but i have repo https://github.com/Yang03/webrtc-desktop-share-viewer
