### ISSUE TITLE
Cannot get server to change address from localhost

### ISSUE THREAD

**Issue by laurence73** [muaz-khan/RTCMultiConnection#794]
Hi Muaz

I have created my own Node.js server on Microsoft Azure using your suggested steps. I have got the server running but it constantly says (on the server after running "node server.js") "Socket.io is listening at: http://localhost:9001" - I need it to be listening at the servers address - https://xxxxx.azurewebsites.net:9001 - I have checked all the config files and js files in the installation and dont see where to make it use the servers actual address? Can you help please? I have read all your installation guides too.

Thanks

**Comment by rtarta** [comment]
just set;
 connection.socketURL = 'https://xxxxx.azurewebsites.net:9001/';
after set others.
@laurence73

**Comment by laurence73** [comment]
@rtarta thanks for reply - I have set this in the HTML already of course but the server is saying this when I run "node server.js" - this is a server issue. where can I change server.js or socket.io.js? to listen to the azure server?

**Comment by rtarta** [comment]
@laurence73  Hi, could you please show your server side code if you set client side socketurl as remote address.

**Comment by rtarta** [comment]
@laurence73  no problem.
