### ISSUE TITLE
[Guide] Setting up your Socket.io server - Nginx

### ISSUE THREAD

**Issue by Teranode** [muaz-khan/RTCMultiConnection#812]
First make sure your nginx server is set up properly. I will not be showing you how to set up the server, you should already know this,

1. In the location block of the website you're going to be using add:
```
        location ~* \.io {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
      
            proxy_pass http://localhost:9001;
            proxy_redirect off;
      
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
```

2. Create a folder(name it anything, in this example ill call it "signal") somewhere within your website's location, follow the example below..
```
mkdir signal
cd signal
git clone https://github.com/muaz-khan/RTCMultiConne                                                                                                                                                             ction-Server.git ./
npm install
node server
```

3 (optional). the server will then proceed to start. If you want to enable ssl you need the ssl key and ssl cert, put that in the config.json located in the signal folder, and change the location block proxy_pass to `proxy_pass https://localhost:9001;`

your socket url will look like this when submitting:
`connection.socketURL = '/';`

**Comment by muaz-khan** [comment]
Created wiki-page:
* https://github.com/muaz-khan/RTCMultiConnection-Server/wiki/Nginx-Configuration
