### ISSUE TITLE
Suddenly can not connect the video visit

### ISSUE THREAD

**Issue by ravipatel07** [muaz-khan/RTCMultiConnection#813]
We are using the RTCMultiConnection for video call. But suddenly the video visit can't be connected. So is there any way to find out why it's not connected? 
Also, how can I find the visit is connected to peer-to-peer or through turn server? How can I add the log to identify the visit are disconnected through any reason?

**Comment by restorepro** [comment]
Make sure that your application is loaded using HTTPS and not HTTP. That will cause this error... Can you post the stack trace?
