### ISSUE TITLE
connection.onstreamended never called on Safari

### ISSUE THREAD

**Issue by ifcall** [muaz-khan/RTCMultiConnection#836]
Using any demo based on RTCMultiConnection, i noticed that when remote stream disconnect, in Safari there is no call to the connection.onstreamended function.

I have check everywhere on the code and i have no idea what happen with Safari.

**Comment by 2gen** [comment]
I too am having this issue. Safari 13.0.3 on macOS High Sierra v 10.13.6. @ifcall you closed this issue, did you figure a solution?
