### ISSUE TITLE
Make only audio after xx participants

### ISSUE THREAD

**Issue by thornzz** [muaz-khan/RTCMultiConnection#856]
Hi,

I want to if my existing participants length>10 other participants join room only audio stream not video. They will see other 10 participants video but wont stream video coz huge amount CPU usage at webrtc.

I cant change session to only audio after x amount participants. Is there any idea?

**Comment by flayds** [comment]
Hi Thornzz,

Um caminho talvez seja você verificar a quantidade de participantes e carregar parte do código de acordo com a função que deseja disponibilizar.

Um exemplo para desativar video acima de 10 participantes, também precisa realizar algumas modificações do Template, mas acho que esse seria o caminho, com JS ou a linguagem que utiliza. PHP, ASP, etc...

if (connection.getAllParticipants().length > 10){

connection.session = {
        audio: true,
	data: true,
        video: false
};

	} else {
connection.session = {
        audio: true,
	data: true,
        video: true
};

}

Acredito ter alguém mas capaz de falar sobre JS, desculpem qualquer erro e espero que tenha ajudado.

**Comment by thornzz** [comment]
Where i have to control  participants count and change live session data?? there are too many events. OnStream, OnOpen OnNewParticipant etc.. Have you got any idea?

**Comment by flayds** [comment]
Olá Thornzz,

  Sem conhecer seu código fica difícil saber ao certo tudo que precisa mudar, se puder posta-lo, talvez outras pessoas também possa ter idéias melhores.

  Se quiser pode me chamar no PV também, mas aqui podemos estar ajudando outras pessoas.

**Comment by thornzz** [comment]
Thank you for your help. We will find any other way to solve this problem.
