### ISSUE TITLE
onstream not triggered on join

### ISSUE THREAD

**Issue by jtpdev** [muaz-khan/RTCMultiConnection#862]
I'm using the latest version of *rtcmulticonnection*, using a many-to-many connection with vue and when someone join to the room, the event *onNewParticipant* is triggered, but *onstream* not.

I tried to add a stream by *addStream* but throws *RTCMultiConnection.js?cd68:683 Peer (xxxxx) does not exist. Renegotiation skipped.*

This is my *created* method:

this.connection = new RTCMultiConnection();

    this.connection.socketURL = 'http://localhost:9001/';

    this.connection.socketMessageEvent = 'video-conference';

    this.connection.session = {
        audio: true,
        video: true
    };

    this.connection.sdpConstraints.mandatory = {
      OfferToReceiveAudio: true,
      OfferToReceiveVideo: true
    };

    var bitrates = 512;
    var resolutions = 'Ultra-HD';
    var videoConstraints = {};

    if (resolutions == 'HD') {
        videoConstraints = {
            width: {
                ideal: 1280
            },
            height: {
                ideal: 720
            },
            frameRate: 30
        };
    }

    if (resolutions == 'Ultra-HD') {
        videoConstraints = {
            width: {
                ideal: 1920
            },
            height: {
                ideal: 1080
            },
            frameRate: 30
        };
    }

    this.connection.mediaConstraints = {
        video: videoConstraints,
        audio: true
    };

    var CodecsHandler = this.connection.CodecsHandler;

    this.connection.processSdp = (sdp) => {
        var codecs = 'vp8';

        if (codecs.length) {
            sdp = CodecsHandler.preferCodec(sdp, codecs.toLowerCase());
        }

        if (resolutions == 'HD') {
            sdp = CodecsHandler.setApplicationSpecificBandwidth(sdp, {
                audio: 128,
                video: bitrates,
                screen: bitrates
            });

            sdp = CodecsHandler.setVideoBitrates(sdp, {
                min: bitrates * 8 * 1024,
                max: bitrates * 8 * 1024,
            });
        }

        if (resolutions == 'Ultra-HD') {
            sdp = CodecsHandler.setApplicationSpecificBandwidth(sdp, {
                audio: 128,
                video: bitrates,
                screen: bitrates
            });

            sdp = CodecsHandler.setVideoBitrates(sdp, {
                min: bitrates * 8 * 1024,
                max: bitrates * 8 * 1024,
            });
        }

        return sdp;
    };

    this.connection.onNewParticipant = (pId, userPreferences, c) => {
      console.log(pId, userPreferences, c)
    }
    this.connection.onmessage = (event) => {
      console.log(event)
    }
    // this.connection.videosContainer = this.$refs.videoChat;
    this.connection.onstream = (event) => {
      console.log(event)
      var existing = document.getElementById(event.streamid);
      if(existing && existing.parentNode) {
        existing.parentNode.removeChild(existing);
      }

      if (event.type == 'local') {
        this.videoChat.senderStream = event.stream;
        } else {
        this.videoChat.receiverStream = event.stream;
      }

      // to keep room-id in cache
      localStorage.setItem(this.connection.socketMessageEvent, this.connection.sessionid);

      chkRecordConference.parentNode.style.display = 'none';

      if(chkRecordConference.checked === true) {
        btnStopRecording.style.display = 'inline-block';
        recordingStatus.style.display = 'inline-block';

        var recorder = this.connection.recorder;
        if(!recorder) {
          recorder = RecordRTC([event.stream], {
            type: 'video'
          });
          recorder.startRecording();
          this.connection.recorder = recorder;
        }
        else {
          recorder.getInternalRecorder().addStreams([event.stream]);
        }

        if(!this.connection.recorder.streams) {
          this.connection.recorder.streams = [];
        }

        this.connection.recorder.streams.push(event.stream);
        recordingStatus.innerHTML = 'Recording ' + this.connection.recorder.streams.length + ' streams';
      }

      if(event.type === 'local') {
        this.connection.socket.on('disconnect', function() {
          if(!this.connection.getAllParticipants().length) {
            location.reload();
          }
        });
      }
    };

    this.connection.onMediaError = (e) => {
      if (e.message === 'Concurrent mic process limit.') {
          if (DetectRTC.audioInputDevices.length <= 1) {
              alert('Please select external microphone. Check github issue number 483.');
              return;
          }

          var secondaryMic = DetectRTC.audioInputDevices[1].deviceId;
          this.connection.mediaConstraints.audio = {
              deviceId: secondaryMic
          };

          this.connection.join(this.connection.sessionid);
      }
      console.log(e)
    };`

`

**Comment by Machosh** [comment]
In my case... onstream only fired on local not remoteUser.
received all of remote id, streamid,audio, but not fired onStream()

any solution?

**Comment by 4nkit-5hukla** [comment]
same here.

**Comment by 4nkit-5hukla** [comment]
> In my case... onstream only fired on local not remoteUser.
> received all of remote id, streamid,audio, but not fired onStream()
> 
> any solution?

same here.

**Comment by jtpdev** [comment]
Im my case the problem was I override the function **onNewParticipant**:

```js
this.connection.onNewParticipant = (pId, userPreferences, c) => {
  console.log(pId, userPreferences, c)
}
```

Reading the lib code, I saw that **onNewParticipant** is the place where the new participant is joinned to the stream. So, overriding it, the new participant didn't join the client stream.
