### ISSUE TITLE
validate session owner

### ISSUE THREAD

**Issue by Machosh** [muaz-khan/RTCMultiConnection#888]
Can i validate owner(open room) or not(join) when getting remote peers?

In many-to-many case.

**Comment by wnsvy223** [comment]
Yes. connection object has a value type of boolean. it's name is ' isInitiator '.
So you can set extra value and share remote peers.
if(connection.isInitiator){
       connection.extra.owner = true;
}else{
       connection.extra.owner = false;
}

**Comment by Machosh** [comment]
@wnsvy223 
Exactly what i want. Thanks!
