### ISSUE TITLE
CPU not released after video streams removed

### ISSUE THREAD

**Issue by olaviinha** [muaz-khan/RTCMultiConnection#901]
I'm doing my development in Chrome, unfortunately it has kept me so busy I have not yet tested what is the situation with other browsers.

### My app works as follows:

1. A number of participants join a room, each seeing only their own webcam. Tab CPU for each participant is around ~3%.
2. Video streams can be dynamically opened between any participants by `renegotiate` or `addStream`
3. A number of participants start viewing user-x's webcam stream. Tab CPU for user-x now goes up to ~40%. So far so good.
4. Each participant now stops viewing user-x's webcam: remove all remoteStreams, user-x even disconnects with every peer in the room. **Here comes the problem: Tab CPU for user-x still remains at ~40%**, and does not drop back to normal as would be expected.

Just to confirm: at the end of step 4, user-x's `connection.getAllParticipants();` returns `[]`, i.e. no peer connections. `connection.streamEvents` and `connection.attachStreams` return that one single localStream.

Only affective method to drop CPU back to normal at this point seems to be user-x removing own `localStream`. This returns tab CPU to 0%. The only method I've found that is. IF, however, user-x returns `localStream` and reconnects with peers who were previously viewing user-x's camera, then CPU will jump back to 40% as if some ghost streaming was still taking place.

This is the first time I've ever touched WebRTC, but my novice guess would be that either A) I fail to find what is being done to my localStream and how to stop whatever that is, or B) Chrome/WebRTC just leave some useless background processes hanging, whether it's a bug or a feature.

Key feature of this app should be that those webcam streams can be opened/closed on the fly, and that is why this problem is super bad, as CPU usage keeps piling up from each _open_ but is never released from the _closures_ or even _peer disconnects_. For the same reason stopping `localStream` seems like a bad solution to the problem at hand (as user-y may want to close viewing user-x while user-z is still viewing user-x, etc.)

Any help and tips highly appreciated!

**Comment by olavii** [comment]
I ended up working around the CPU problem by creating a `new RTCMultiConnection();` for each participants and my own backend keeping track of them (who's "online"). Now I can do `closeSocket` for each connection when no longer needed and it's keeping CPU under control. I think this method sort of defies the purpose of this library (being **Multi**Connect).

Still interested if anybody has a better solution, or if anybody can suggest another similar library for regular p2p RTCPeerConnections.

**Comment by olaviinha** [comment]
I ended up working around the CPU problem by creating a `new RTCMultiConnection()` for each participants and my own backend keeping track of who's "online". Now I can remove all streams and `closeSocket` for each connection when not needed and reconnect when needed again. It's keeping CPU under control. I think this method sort of defies the purpose of this library though, being specifically for **Multi**Connection.

Still interested if anybody has a better solution, or if anybody can suggest another similar library for regular p2p RTCPeerConnections.

**Comment by olaviinha** [comment]
Cleaning up dead issues.
