### ISSUE TITLE
RTCMulticonnection in an LXD Container

### ISSUE THREAD

**Issue by rayj00** [muaz-khan/RTCMultiConnection#905]
I am trying to run RTCMulticonnection inside of a Ubuntu 20.04 LXD Container.  I got RTCMulticonnection to install OK.

I have a subdomain configured for the container access.

However I am getting a 502 Bad Gateway error.

Any ideas how to troubleshoot this?

Thanks,

Ray

**Comment by rayj00** [comment]
So I got it working and can activate Scalable Broadcasting, but only using FireFox.  

**1. Chrome will not work at all in an insecure state.** 
**2. I cannot install a Letsencrypt certificate:** (maybe this would fix chrome?)
Waiting for verification...
Challenge failed for domain xxxx.streamingworld.us
http-01 challenge for xxxx.streamingworld.us
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: xxxx.streamingworld.us
   Type:   connection
   Detail: Fetching
   http://xxxx.streamingworld.us/.well-known/acme-challenge/el93vVWhor2Myz72j4BCME82Uu5ntSKv_3OB8wC-WOY:
   Connection refused

   **3. My android phone does nothing when I browse to the website.**

Thats it for now.   I played around with Muaz code maybe over a year ago.  He was available a lot more then than now, so I am not very confident he will address any of my issues.   

If you know of any fixes floating around for RTMMulticonnection v3.7.0  I'd appreciate it.

Ray

**Comment by rayj00** [comment]
All of the sudden I am getting this failure in Firefox.   Any ideas?   I don't think I did anything to cause this:  
server-logs You <1jjpozzwpbp9wp1mwjn> are now serving the broadcast. RTCMultiConnection.js:428:21
MediaStreamError { name: "NotReadableError", message: "Failed to allocate videosource", constraint: "", stack: "" }
 
Object { audio: true, video: true }

Ideas?

**Comment by wnsvy223** [comment]
[I found question in stackoverflow. try this](https://stackoverflow.com/questions/42568498/notreadableerror-failed-to-allocate-videosource)

**Comment by rayj00** [comment]
Thanks.  Problem mysteriously went away!  Now I have another one.  I am getting a CORS Blocked error when I use localhost:9001 for socketURL.  If I use the herokuapp.com:443 it works?
Any idea how to fix?

Thanks,

Ray

**Comment by wnsvy223** [comment]
Does the CORS error appear even if remove the connection.socketUrl ?
In API source code, if the socketUrl is not set, it automatically sets the root path.

**Comment by rayj00** [comment]
Oh wow.  I commented out the connection.socketURL line and now it works!!
Fantastic suggestion.  Thanks a lot!   I owe you a beer!

**Comment by wnsvy223** [comment]
I'm glad it's solved. Please close the issue so that people who use the RTCMulticonnection API do not get confused.

**Comment by rayj00** [comment]
Thanks to wnsvy223!
