### ISSUE TITLE
How to config iceServers, rightly...?

### ISSUE THREAD

**Issue by JayCasee** [muaz-khan/RTCMultiConnection#939]
I've installed the demo and it works, normally.

To connect the persons who are in different networks, I'm configuring `iceServers`, but it seems it is not working as I expected.

```
connection.iceServers = [];
connection.iceServers.push( {
  urls      : 'stun:ss-turn2.xirsys.com',
} );
connection.iceServers.push( {
  urls      : [ "turn:ss-turn2.xirsys.com:80?transport=udp", "turn:ss-turn2.xirsys.com:3478?transport=udp", "turn:ss-turn2.xirsys.com:80?transport=tcp", "turn:ss-turn2.xirsys.com:3478?transport=tcp", "turns:ss-turn2.xirsys.com:443?transport=tcp", "turns:ss-turn2.xirsys.com:5349?transport=tcp", ],
  credential: '****',
  username  : '****'
} );
```

The above is the way that I've added XirSys (xirsys.com) STUN and TURN servers, but different network users are still not possible to connect.

Here're my questions...
1. Is the above code has any grammar problem...?
2. Do I need to do anything else than the above configurations...?
3. Can anyone recommend me any TURN server provider like XirSys, which doesn't need to be free (I can pay the cost.) and easy to be connected with RTCMultiConnection...?

Thank you for reading my question.

**Comment by ansarnisargill** [comment]
Hi, Jay.
The way you are providing IceServers seems correct but if it is not really working then may be try adding this way

`
connection.iceServers = [
 { urls: "stun:ss-turn2.xirsys.com" },
 { urls: 'turn:ss-turn2.xirsys.com:80?transport=udp',
   credential: '****',
   username: '****'
  },
 { urls: 'turn:ss-turn2.xirsys.com:80?transport=tcp"',
   credential: '****',
   username: '****'
  },
];
`
point being try to add turn servers separately.
Also [http://numb.viagenie.ca/](http://numb.viagenie.ca/) provide turn servers which are free and work great.

**Comment by JayCasee** [comment]
Thank you really so much. Just using "numb.viagenie.ca" as the TURN server solved the problem at once...! I'm not sure, but it seems XirSys's servers are not working, properly... Thank you so much, again. : )

**Comment by ansarnisargill** [comment]
> Thank you really so much. Just using "numb.viagenie.ca" as the TURN server solved the problem at once...! I'm not sure, but it seems XirSys's servers are not working, properly... Thank you so much, again. : )

You are welcome!

**Comment by cdaetwyler** [comment]
Hi

In order to use the XirSys TURN servers, you must set the pcConfig as follows:

var pcConfig = {
    'iceServers': [//{ "urls": "stun:sp-turn1.xirsys.com" },
        { 'urls': 'stun:stun.l.google.com:19302' },
        { 'urls': 'stun:stun1.l.google.com:19302' },
        { 'urls': 'stun:stun2.l.google.com:19302' },
        { 'urls': 'stun:stun.l.google.com:19302?transport=udp' },
        { "username": “yourXirSysUsername", "urls": "turn:sp-turn1.xirsys.com:80?transport=udp", "credential":  “yourXirSysCredential" },
        { "username": "yourXirSysUsername", "urls": "turn:sp-turn1.xirsys.com:3478?transport=udp", "credential": "yourXirSysCredential" },
        { "username": "yourXirSysUsername", "urls": "turn:sp-turn1.xirsys.com:80?transport=tcp", "credential": "yourXirSysCredential" },
        { "username": "yourXirSysUsername", "urls": "turn:sp-turn1.xirsys.com:3478?transport=tcp", "credential": "yourXirSysCredential" },
        { "username": "yourXirSysUsername", "urls": "turns:sp-turn1.xirsys.com:443?transport=tcp", "credential": "yourXirSysCredential" },
        { "username": "yourXirSysUsername", "urls": "turns:sp-turn1.xirsys.com:5349?transport=tcp", "credential": "yourXirSysCredential" }
    ]
};



And further down in the code you must set the requestTurn function accordingly to the urls (not url) settings:

function requestTurn(turnURL) {
  var turnExists = false;
    for (var i in pcConfig.iceServers) {
        if (pcConfig.iceServers[i].urls.substr(0, 5) === 'turn:') {
      turnExists = true;
      turnReady = true;
      break;
    }
  }
}

And in the function createPeerConnection you must use the PCConfig as follows

function createPeerConnection(thisPeerConnection) {
    try {
        peerConnection[thisPeerConnection_txt] = new RTCPeerConnection(pcConfig);
        …



  } catch (e) {
        console.log(senderName + ': Failed to create PeerConnection ' + thisPeerConnection_txt + ', exception: ' + e.message);
        return;
  }
}

Good luck!

Christof

Christof J. Daetwyler, MD 
Developer of Online Resources for Medical Education
Co-founder & co-CEO of EnhancedLearn LLC
URL: https://EnhancedLearn.net
Email: Admin@EnhancedLearn.net
Skype: c.daetwyler
Phone US: +1 (909) 342-6483
Phone BR: +55 (62) 99319-0522
