### ISSUE TITLE
How Create(Open) Room in One Page And Use This in Another Page

### ISSUE THREAD

**Issue by ahmadfozooni** [muaz-khan/RTCMultiConnection#950]
hi muaz khan,
im very confuse to using your library, everything its ok in your demo's but when i try to use your code in my VueCLI project, i got any errors and bugs

we writing education stream system to create online class on our servers, we have student panel and student panel, teachers can create course and set time/days and student can see courses and watch their episode videos in his panel
now we going to online stream via camera and microphone to student with our teachers

i have few questions as you:

1. how can i open room in one component and use this room in another component ? 
( i want user create*open* room in his panel to start a stream and students watch his camera in student pnael in 2 different route 
like that :
open channel in TeacherPanel.Vue
join channel in StudentPanel.Vue
)

2. how can i use my own user authentication before student going to watch stream ?

3. how can i give permission to use to share his webcam with teacher and invoke his permission ?

4. how can i give permission to teacher , to ban user from stream ( user leave )

sorry for my bad english dude
please help me, thanks

**Comment by ansarnisargill** [comment]
Hi, these are functional requirements of your application which are not directly concerned with this library or project. You can reach out to me privately so I can help you in these requirements but this is not an "issue" with library itself so should close the issue. You can reach me at [My email](ansarnisargill@gmail.com)
