### ISSUE TITLE
Using the Video-broadcasting example to transmit a video file...

### ISSUE THREAD

**Issue by njss** [muaz-khan/RTCMultiConnection#972]
I would like to just stream a video file...maybe later also a canvas.
I am trying to change the video-brodcasting example, however I have no clue on how to not use the user webcamera and instead braodcast a video file + the content of a canvas...

Thank you fo any help...

**Comment by njss** [comment]
Just missing a call to addStream in my code...
It is

**Comment by ginger0106** [comment]
> 
I am facing the same problem, could you share your code? thx
