### ISSUE TITLE
Stop streaming / stop webcam

### ISSUE THREAD

**Issue by mistris** [muaz-khan/RTCMultiConnection#98]
How can I stop webcam? I want to turn off that red light. 
![image](https://cloud.githubusercontent.com/assets/3584575/13527992/e3038086-e21b-11e5-9bd1-5d91885194f6.png)

**Comment by muaz-khan** [comment]
```javascript
// RTCMultiConnection (any version)
connection.attachStreams.forEach(function(stream) {
    stream.stop();
});
```

For 3rd party apps: http://stackoverflow.com/a/11646945/552182

**Comment by mistris** [comment]
Thank you very much! :+1:
