### ISSUE TITLE
Cross-origin request blocked from own server

### ISSUE THREAD

**Issue by adares2** [muaz-khan/RTCMultiConnection#992]
I have a nginx symfony vue stack.  under mydomain.com
I implemented RTCMulticonnection with
```

<script type="application/javascript"  src="https://rtcmulticonnection.herokuapp.com/dist/RTCMultiConnection.min.js"></script>
<script type="application/javascript"  src="https://rtcmulticonnection.herokuapp.com/socket.io/socket.io.js"></script> 
```
and in my Vue File
```
this.rtcmConnection = new RTCMultiConnection();
this.rtcmConnection.socketURL = 'https://rtcmulticonnection.herokuapp.com:443/';
```
everything was working. Now i wanted to use my own server. I started one under the following domain:
```
https://mydomain.com:9001/
```
and used it with:
```
this.rtcmConnection.socketURL = 'https://mydomain.com:9001/';
```
but the information from the server could not be read

`
Cross-origin request blocked: The same-source rule forbids reading the external resource on https://mydomain.com:9001/socket.io/?userid=1k8u29ut6mgii1rzynyp&sessionid=f4f76d649bf23b3cf645aa2b853095b8&msgEventageConnection-Connection-Connection-Connection-Rocket-Multi -Message & autoCloseEntireSession = false & maxParticipantsAllowed = 1000 & extra =% 7B% 7D & EIO = 3 & transport = polling & t = NNmp4Or. (Reason: CORS header 'Access-Control-Allow-Origin' is missing)`

so i updated server.js

`ioServer(httpApp,{origins: '*:*'})`

but that didn't change anything

**Comment by adares2** [comment]
```
var iooptions = {
        allowUpgrades: true,
        transports: [ 'polling', 'websocket' ],
        pingTimeout: 9000,
        pingInterval: 3000,
        cors: {
          origin: 'https://mydomain.com',
          methods: ["GET", "POST"],
          credentials: true
        }
};

ioServer(httpApp,iooptions).on('connection', function(socket) {
    RTCMultiConnectionServer.addSocket(socket, config);
```
it works with this configuration

**Comment by haidar077** [comment]
> ```
> var iooptions = {
>         allowUpgrades: true,
>         transports: [ 'polling', 'websocket' ],
>         pingTimeout: 9000,
>         pingInterval: 3000,
>         cors: {
>           origin: 'https://mydomain.com',
>           methods: ["GET", "POST"],
>           credentials: true
>         }
> };
> 
> ioServer(httpApp,iooptions).on('connection', function(socket) {
>     RTCMultiConnectionServer.addSocket(socket, config);
> ```
> 
> it works with this configuration

it not working show error 
index.js:83 GET https://localhost:3000/socket.io/?userid=8irojvq05l&sessionid=ebc0b8c743806ec8a3e3897631d21a7c&msgEvent=canvas-dashboard-demo&socketCustomEvent=RTCMultiConnection-Custom-Message&autoCloseEntireSession=true&maxParticipantsAllowed=100&extra=%7B%22userFullName%22%3A%22Surya%20Kant%22%2C%22systemType%22%3A%22Computer%22%2C%22screenWidth%22%3A1366%2C%22screenHeight%22%3A768%2C%22roomOwner%22%3Atrue%7D&EIO=3&transport=polling&t=NSZmU1S 400 (Bad Request)

**Comment by celsoaramos** [comment]
Do you resolve this Bad Request ?
I have the same problem =\

> > ```
> > var iooptions = {
> >         allowUpgrades: true,
> >         transports: [ 'polling', 'websocket' ],
> >         pingTimeout: 9000,
> >         pingInterval: 3000,
> >         cors: {
> >           origin: 'https://mydomain.com',
> >           methods: ["GET", "POST"],
> >           credentials: true
> >         }
> > };
> > 
> > ioServer(httpApp,iooptions).on('connection', function(socket) {
> >     RTCMultiConnectionServer.addSocket(socket, config);
> > ```
> > 
> > 
> > it works with this configuration
> 
> it not working show error
> index.js:83 GET https://localhost:3000/socket.io/?userid=8irojvq05l&sessionid=ebc0b8c743806ec8a3e3897631d21a7c&msgEvent=canvas-dashboard-demo&socketCustomEvent=RTCMultiConnection-Custom-Message&autoCloseEntireSession=true&maxParticipantsAllowed=100&extra=%7B%22userFullName%22%3A%22Surya%20Kant%22%2C%22systemType%22%3A%22Computer%22%2C%22screenWidth%22%3A1366%2C%22screenHeight%22%3A768%2C%22roomOwner%22%3Atrue%7D&EIO=3&transport=polling&t=NSZmU1S 400 (Bad Request)

**Comment by er-prince** [comment]
var iooptions = {
        allowUpgrades: true,
        transports: [ 'polling', 'websocket' ],
        pingTimeout: 9000,
        pingInterval: 3000,
        cors: {
          origin: 'https://mydomain.com',
          methods: ["GET", "POST"],
          credentials: true
        },
         allowEIO3: true
};

ioServer(httpApp,iooptions).on('connection', function(socket) {
    RTCMultiConnectionServer.addSocket(socket, config);
    
    
    
    This will solve bad request error
